'use no memo'; // renders translated arrays that the React Compiler would otherwise cache across language switches

import { useMemo, useState } from 'react';
import { FlatList, Linking, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useTranslation } from 'react-i18next';
import { useAccent } from '@/hooks/use-accent';
import { useIndicStyles } from '@/hooks/use-indic-styles';
import { ScreenLayout } from '@/components/templates/ScreenLayout';
import { FeatureHeader } from '@/components/molecules/FeatureHeader';
import { EyebrowLabel } from '@/components/atoms/EyebrowLabel';
import { FONTS, RADIUS } from '@/constants/themes';
import { localizeDigits } from '@/utils/i18n';
import { getInstallMarker } from '@/utils/model-download';
import { FALLBACK_CATALOG, currentEntryId } from '@/utils/model-catalog';

type Pkg = { name: string; version: string; license: string; copyright: string[]; url: string };
// Generated by scripts/generate-licenses.mjs (yarn licenses).
// eslint-disable-next-line @typescript-eslint/no-var-requires
const LICENSES: { packages: Pkg[]; texts: Record<string, string> } = require('@/assets/legal/licenses.json');

/**
 * Hosted copies of docs/privacy.md and docs/terms.md. Set these once the
 * pages are published; the screens then link to the full text.
 */
const FULL_TEXT_URL: Record<'privacy' | 'terms', string | null> = {
  privacy: 'https://ash-larch-a05.notion.site/Astropedia-Privacy-Policy-3f4a0161464a814984a9e0f6c63f8ab4',
  terms: null,
};

/** /legal/privacy, /legal/terms, /legal/licenses. */
export default function LegalScreen() {
  const { doc } = useLocalSearchParams<{ doc: string }>();
  if (doc === 'licenses') return <Licences />;
  return <Doc kind={doc === 'terms' ? 'terms' : 'privacy'} />;
}

function Doc({ kind }: { kind: 'privacy' | 'terms' }) {
  const { theme } = useAccent();
  const styles = useIndicStyles(baseStyles);
  const { t } = useTranslation('about');
  const ns = kind === 'privacy' ? 'privacyDoc' : 'termsDoc';
  const sections = t(`${ns}.sections`, { returnObjects: true }) as { h: string; p: string }[];
  const url = FULL_TEXT_URL[kind];
  return (
    <ScreenLayout edges={['top', 'left', 'right']}>
      <FeatureHeader title={t(`${ns}.title`)} subtitle={t(`${ns}.status`)} />
      <ScrollView style={styles.flex} contentContainerStyle={styles.content}>
        {sections.map((s) => (
          <View key={s.h} style={styles.section}>
            <Text style={[styles.h, { color: theme.ink }]} accessibilityRole="header">{s.h}</Text>
            <Text style={[styles.p, { color: theme.ink2 }]}>{s.p}</Text>
          </View>
        ))}
        {url ? (
          <TouchableOpacity onPress={() => { Linking.openURL(url).catch(() => {}); }} accessibilityRole="link">
            <Text style={[styles.p, styles.link, { color: theme.accent }]}>{url}</Text>
          </TouchableOpacity>
        ) : null}
        <View style={{ height: 40 }} />
      </ScrollView>
    </ScreenLayout>
  );
}

function Licences() {
  const { theme } = useAccent();
  const styles = useIndicStyles(baseStyles);
  const { t } = useTranslation('about');
  const [open, setOpen] = useState<string | null>(null);
  const installedId = currentEntryId(FALLBACK_CATALOG, getInstallMarker());

  const textsFor = (licence: string): [string, string][] => {
    const whole = LICENSES.texts[licence];
    if (whole) return [[licence, whole]];
    return licence
      .split(/\s+(?:AND|OR)\s+|[()]/)
      .filter((id) => id && LICENSES.texts[id])
      .map((id) => [id, LICENSES.texts[id]]);
  };

  const header = useMemo(() => (
    <View>
      <Text style={[styles.p, styles.intro, { color: theme.ink2 }]}>{t('licences.intro')}</Text>
      <EyebrowLabel style={styles.sectionLabel}>{t('licences.models')}</EyebrowLabel>
      <View style={[styles.card, { backgroundColor: theme.surface, borderColor: theme.hairline }]}>
        {FALLBACK_CATALOG.map((e, i) => (
          <View key={e.id} style={[styles.model, i > 0 && { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.hairline }]}>
            <View style={styles.modelTop}>
              <Text style={[styles.pkgName, { color: theme.ink }]}>{e.name}</Text>
              {e.id === installedId ? (
                <Text style={[styles.tag, { color: theme.accent, borderColor: theme.accent }]}>{t('licences.installed')}</Text>
              ) : null}
            </View>
            <TouchableOpacity onPress={() => { Linking.openURL(e.license.url).catch(() => {}); }} accessibilityRole="link">
              <Text style={[styles.meta, styles.link, { color: theme.accent }]}>{e.license.name}</Text>
            </TouchableOpacity>
            {e.adapter === 'gemma21' ? (
              <Text style={[styles.meta, { color: theme.muted }]}>{t('model.gemmaNotice')}</Text>
            ) : e.license.notice ? (
              <Text style={[styles.meta, { color: theme.muted }]}>{e.license.notice}</Text>
            ) : null}
          </View>
        ))}
      </View>
      <EyebrowLabel style={[styles.sectionLabel, styles.sectionGap]}>
        {`${t('licences.libraries')} · ${localizeDigits(t('licences.count', { count: LICENSES.packages.length }))}`}
      </EyebrowLabel>
    </View>
  ), [styles, theme, t, installedId]);

  return (
    <ScreenLayout edges={['top', 'left', 'right']}>
      <FeatureHeader title={t('licences.title')} />
      <FlatList
        style={styles.flex}
        contentContainerStyle={styles.content}
        data={LICENSES.packages}
        keyExtractor={(p) => `${p.name}@${p.version}`}
        ListHeaderComponent={header}
        ListFooterComponent={<View style={{ height: 40 }} />}
        initialNumToRender={20}
        renderItem={({ item: p }) => {
          const key = `${p.name}@${p.version}`;
          const expanded = open === key;
          return (
            <TouchableOpacity
              onPress={() => setOpen(expanded ? null : key)}
              style={[styles.pkg, { borderBottomColor: theme.hairline }]}
              accessibilityRole="button"
              accessibilityState={{ expanded }}
              accessibilityLabel={`${p.name} ${p.version}, ${p.license}`}
              accessibilityHint={t('licences.viewLicence')}
            >
              <View style={styles.modelTop}>
                <Text style={[styles.pkgName, styles.flex, { color: theme.ink }]} numberOfLines={1}>{p.name}</Text>
                <Text style={[styles.meta, { color: theme.muted }]}>{p.license}</Text>
              </View>
              {p.version ? <Text style={[styles.meta, { color: theme.faint }]}>{p.version}</Text> : null}
              {expanded ? (
                <View style={styles.expanded}>
                  {p.copyright.map((c) => <Text key={c} style={[styles.meta, { color: theme.ink2 }]}>{c}</Text>)}
                  {p.url ? (
                    <Text
                      style={[styles.meta, styles.link, { color: theme.accent }]}
                      onPress={() => { Linking.openURL(p.url).catch(() => {}); }}
                    >
                      {p.url}
                    </Text>
                  ) : null}
                  {textsFor(p.license).map(([id, text]) => (
                    <Text key={id} style={[styles.licenceText, { color: theme.muted, backgroundColor: theme.surface2 }]} selectable>
                      {text}
                    </Text>
                  ))}
                </View>
              ) : null}
            </TouchableOpacity>
          );
        }}
      />
    </ScreenLayout>
  );
}

const baseStyles = StyleSheet.create({
  flex: { flex: 1 },
  content: { paddingHorizontal: 22, paddingTop: 18 },
  section: { marginBottom: 20, gap: 6 },
  h: { fontFamily: FONTS.sansMedium, fontSize: 15.5, lineHeight: 22 },
  p: { fontFamily: FONTS.sansRegular, fontSize: 14, lineHeight: 21 },
  link: { textDecorationLine: 'underline' },
  intro: { marginBottom: 20 },
  sectionLabel: { marginBottom: 10 },
  sectionGap: { marginTop: 24 },
  card: { borderRadius: RADIUS.card, borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: 18, overflow: 'hidden' },
  model: { paddingVertical: 14, gap: 4 },
  modelTop: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  tag: {
    fontFamily: FONTS.sansRegular, fontSize: 10.5, borderWidth: StyleSheet.hairlineWidth,
    borderRadius: RADIUS.pill, paddingHorizontal: 8, paddingVertical: 1, overflow: 'hidden',
  },
  pkg: { paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth },
  pkgName: { fontFamily: FONTS.sansRegular, fontSize: 14 },
  meta: { fontFamily: FONTS.sansRegular, fontSize: 12, lineHeight: 17 },
  expanded: { marginTop: 8, gap: 6 },
  licenceText: { fontFamily: FONTS.monoRegular, fontSize: 10.5, lineHeight: 15, padding: 10, borderRadius: 8, overflow: 'hidden' },
});
