/** Generated from the romanization sheets (scratchpad roman/gen.py); hand-written Latin forms of the agent's table sentences. */
export const HI_ITEMS: readonly (readonly [string, string])[] = [
  ['मैं समझ सकता हूँ, यह समय आसान नहीं रहा।', 'Main samajh sakta hoon, yeh samay aasaan nahi raha.'],
  ['मैं समझ सकता हूँ, इतना इंतज़ार आसान नहीं।', 'Main samajh sakta hoon, itna intezaar aasaan nahi.'],
  ['चार्ट में इसकी मज़बूत संभावना दिखती है, हालाँकि कुछ भी पक्का नहीं होता।', 'Chart mein iski mazboot sambhavna dikhti hai, haalanki kuch bhi pakka nahi hota.'],
  ['चार्ट में इसकी अच्छी संभावना है, और लगातार मेहनत से यह और बढ़ती है।', 'Chart mein iski achhi sambhavna hai, aur lagaataar mehnat se yeh aur badhti hai.'],
  ['आपके चार्ट में यह जल्दी नहीं, धीरे-धीरे होता दिखता है, इसलिए यहाँ लगातार मेहनत ज़्यादा काम आएगी।', 'Aapke chart mein yeh jaldi nahi, dheere-dheere hota dikhta hai, isliye yahan lagaataar mehnat zyada kaam aayegi.'],
  ['उनके डॉक्टरों के संपर्क में रहें, और अपनी नींद व आराम का भी ध्यान रखें।', 'Unke doctors ke sampark mein rahein, aur apni neend aur aaram ka bhi dhyaan rakhein.'],
  ['आपके चार्ट में इस मामले के लिए सहायक समय दिखता है, हालाँकि फ़ैसला तथ्यों और आपके वकील की तैयारी पर टिका है।', 'Aapke chart mein is maamle ke liye sahayak samay dikhta hai, haalanki faisla tathyon aur aapke vakeel ki taiyari par tika hai.'],
  ['आपके चार्ट में इस मामले को ठीक-ठाक साथ मिलता दिखता है; सबसे ज़्यादा मायने तथ्यों और अच्छे वकील के हैं।', 'Aapke chart mein is maamle ko theek-thaak saath milta dikhta hai; sabse zyada maayne tathyon aur achhe vakeel ke hain.'],
  ['आपके चार्ट में इस मामले के लिए धीमा समय दिखता है, इसलिए धैर्य और अच्छे वकील की सबसे ज़्यादा ज़रूरत है।', 'Aapke chart mein is maamle ke liye dheema samay dikhta hai, isliye dhairya aur achhe vakeel ki sabse zyada zaroorat hai.'],
  ['हाँ, {option} आपके चार्ट के सबसे अच्छे विकल्पों में से है।', 'Haan, {option} aapke chart ke sabse achhe vikalpon mein se hai.'],
  ['{option} आपके लिए ठीक रह सकता है, हालाँकि यह आपके चार्ट की पहली पसंद नहीं है।', '{option} aapke liye theek reh sakta hai, haalanki yeh aapke chart ki pehli pasand nahi hai.'],
  ['{option} आपके चार्ट के मज़बूत विकल्पों में नहीं है; दूसरे क्षेत्र आगे दिखते हैं।', '{option} aapke chart ke mazboot vikalpon mein nahi hai; doosre kshetra aage dikhte hain.'],
  ['सबसे सहायक समय {start} से {end} तक है।', 'Sabse sahayak samay {start} se {end} tak hai.'],
  ['असल में यह दूर नहीं है: अच्छा समय {start} में शुरू हो रहा है, इसलिए अभी से तैयारी शुरू करें।', 'Asal mein yeh door nahi hai: achha samay {start} mein shuru ho raha hai, isliye abhi se taiyari shuru karein.'],
  ['आख़िरी फ़ैसला आपके कागज़ात और नियमों पर होता है, इसलिए कागज़ात पूरे और सही रखें।', 'Aakhri faisla aapke kaagzaat aur niyamon par hota hai, isliye kaagzaat poore aur sahi rakhein.'],
  ['कृपया किसी वकील को साथ रखें; हर कानूनी कदम पर वही सही राह दिखा सकते हैं।', 'Kripya kisi vakeel ko saath rakhein; har kaanooni kadam par wahi sahi raah dikha sakte hain.'],
  ['किसी काउंसलर या भरोसेमंद व्यक्ति से खुलकर बात करना सच में मदद करता है।', 'Kisi counsellor ya bharosemand vyakti se khul kar baat karna sach mein madad karta hai.'],
  ['अगर कभी बहुत भारी लगे, तो टेली-मानस (14416) मुफ़्त और गोपनीय है।', 'Agar kabhi bahut bhaari lage, to Tele-MANAS (14416) muft aur gopniya hai.'],
  ['बड़े आर्थिक फ़ैसले के लिए किसी वित्तीय सलाहकार की मदद से योजना बनाएँ।', 'Bade aarthik faisle ke liye kisi financial adviser ki madad se yojana banayein.'],
  ['किसी भी बीमारी के लिए डॉक्टर से ज़रूर मिलें।', 'Kisi bhi bimari ke liye doctor se zaroor milein.'],
  ['इसके साथ अपने डॉक्टर या फ़र्टिलिटी विशेषज्ञ की सलाह लेते रहें; चिकित्सा से जुड़ी बातें वही सबसे अच्छी तरह समझा सकते हैं।', 'Iske saath apne doctor ya fertility specialist ki salah lete rahein; ilaaj se judi baatein wahi sabse achhi tarah samjha sakte hain.'],
  ['आप जो बता रहे हैं, उसमें तुरंत इलाज की ज़रूरत है: अभी 112 पर कॉल करें या सबसे पास के अस्पताल या डॉक्टर के पास जाएँ। चार्ट से इसका अंदाज़ा कभी नहीं लगाया जा सकता, और इसमें देर नहीं करनी चाहिए।', 'Aap jo bata rahe hain, usmein turant ilaaj ki zaroorat hai: abhi 112 par call karein ya sabse paas ke hospital ya doctor ke paas jaayein. Chart se iska andaaza kabhi nahi lagaya ja sakta, aur ismein der nahi karni chahiye.'],
  ['आपकी सुरक्षा सबसे पहले है। अगर आप ख़तरे में हैं, तो 112 या महिला हेल्पलाइन 181 पर कॉल करें, और किसी भरोसेमंद व्यक्ति से बात करें। कोई भी ग्रह-गणना आपको ख़तरे में रहने की वजह न बने, और इसमें आपकी कोई ग़लती नहीं है।', 'Aapki suraksha sabse pehle hai. Agar aap khatre mein hain, to 112 ya mahila helpline 181 par call karein, aur kisi bharosemand vyakti se baat karein. Koi bhi grah-ganana aapko khatre mein rehne ki wajah na bane, aur ismein aapki koi galti nahi hai.'],
  ['कोई काउंसलर आपके अगले कदम सुरक्षित तरीके से, आपकी अपनी रफ़्तार से तय करने में मदद कर सकता है।', 'Koi counsellor aapke agle kadam surakshit tareeke se, aapki apni raftaar se tay karne mein madad kar sakta hai.'],
  ['इसमें किसी की ग़लती ढूँढ़ने की ज़रूरत नहीं।', 'Ismein kisi ki galti dhoondhne ki zaroorat nahi.'],
  ['फ़ैसला आपका अपना है, और इसके लिए समय लेना ठीक है।', 'Faisla aapka apna hai, aur iske liye samay lena theek hai.'],
  ['वही अपनाएँ जो आपकी अपनी आस्था से मेल खाए; किसी भी रस्म से ज़्यादा आपकी मर्ज़ी मायने रखती है।', 'Wahi apnayein jo aapki apni aastha se mel khaaye; kisi bhi rasm se zyada aapki marzi maayne rakhti hai.'],
  ['बताने के लिए धन्यवाद।', 'Batane ke liye dhanyavaad.'],
  ['आपका स्वागत है, ख़ुशी हुई कि यह काम आया। जब चाहें पूछिए।', 'Aapka swagat hai, khushi hui ki yeh kaam aaya. Jab chahein poochhiye.'],
  ['मैं ठीक हूँ, धन्यवाद! मैं सागा हूँ, आपका ज्योतिष साथी। क्या आप अपने करियर, रिश्तों या आने वाले साल के बारे में जानना चाहेंगे?', 'Main theek hoon, dhanyavaad! Main Saga hoon, aapka jyotish saathi. Kya aap apne career, rishton ya aane wale saal ke baare mein jaanna chahenge?'],
  ['यह मेरे दायरे से बाहर है; मैं आपकी कुंडली के बारे में बात करने के लिए हूँ। चाहें तो आपके करियर की ताकत या इस साल के सबसे अच्छे समय के बारे में बता सकता हूँ।', 'Yeh mere daayre se bahar hai; main aapki kundli ke baare mein baat karne ke liye hoon. Chahein to aapke career ki taakat ya is saal ke sabse achhe samay ke baare mein bata sakta hoon.'],
  ['मैं लॉटरी नंबर या शेयर बाज़ार की टिप्स नहीं देता: कोई कुंडली यह नहीं बता सकती, और इस पर पैसा लगाना सुरक्षित नहीं।', 'Main lottery number ya share bazaar ki tips nahi deta: koi kundli yeh nahi bata sakti, aur is par paisa lagana surakshit nahi.'],
  ['माफ़ कीजिए, यह जवाब काम नहीं आया। बताइए आप क्या जानना चाहते हैं, जैसे कौन सा करियर आपके लिए सही है या बदलाव कब संभव है, मैं साफ़-साफ़ बताऊँगा।', 'Maaf kijiye, yeh jawab kaam nahi aaya. Bataiye aap kya jaanna chahte hain, jaise kaun sa career aapke liye sahi hai ya badlaav kab sambhav hai, main saaf-saaf bataunga.'],
  ['मैं मदद के लिए हूँ। अपनी कुंडली के बारे में कुछ भी पूछिए, जैसे कौन सा करियर आपके लिए सही है या बदलाव कब संभव है।', 'Main madad ke liye hoon. Apni kundli ke baare mein kuch bhi poochhiye, jaise kaun sa career aapke liye sahi hai ya badlaav kab sambhav hai.'],
  ['हाँ, आपके चार्ट में शादी साफ़ दिखती है; सवाल सिर्फ़ समय का है, होने या न होने का नहीं।', 'Haan, aapke chart mein shaadi saaf dikhti hai; sawaal sirf samay ka hai, hone ya na hone ka nahi.'],
  ['माफ़ कीजिए अगर बात साफ़ नहीं थी; सीधे शब्दों में कहूँ तो:', 'Maaf kijiye agar baat saaf nahi thi; seedhe shabdon mein kahoon to:'],
  ['जाति, रंग, धर्म या आप किससे प्यार करेंगे, यह कुंडली तय नहीं करती, और मैं इनका अंदाज़ा नहीं लगाऊँगा।', 'Jaati, rang, dharm ya aap kisse pyaar karenge, yeh kundli tay nahi karti, aur main inka andaaza nahi lagaunga.'],
  ['हाँ, यह ज़रूर बताया जा सकता है कि आपका साथी स्वभाव से कैसा होगा और मुलाकात कहाँ होने की संभावना है।', 'Haan, yeh zaroor bataya ja sakta hai ki aapka saathi swabhav se kaisa hoga aur mulaqat kahan hone ki sambhavna hai.'],
  ['आप कौन हैं और किससे प्यार करते हैं, यह आप खुद तय करते हैं; कुंडली यह तय नहीं करती, और यहाँ हर जवाब का सम्मान है। चाहें तो मैं आपके रिश्तों या आने वाले साल के बारे में बता सकता हूँ।', 'Aap kaun hain aur kisse pyaar karte hain, yeh aap khud tay karte hain; kundli yeh tay nahi karti, aur yahan har jawab ka sammaan hai. Chahein to main aapke rishton ya aane wale saal ke baare mein bata sakta hoon.'],
  ['कुंडली से किसी का नाम या पहला अक्षर पता नहीं चलता, इसलिए मैं अंदाज़ा नहीं लगाऊँगा।', 'Kundli se kisi ka naam ya pehla akshar pata nahi chalta, isliye main andaaza nahi lagaunga.'],
  ['मैं बच्चे का लिंग नहीं बताता, मज़ाक में भी नहीं: भारत में जन्म से पहले यह जानना क़ानूनन मना है, क्योंकि इसका ग़लत इस्तेमाल हुआ है, और कोई कुंडली इसे दिखा भी नहीं सकती।', 'Main bachche ka ling nahi batata, mazaak mein bhi nahi: Bharat mein janam se pehle yeh jaanna kaanoonan mana hai, kyunki iska galat istemaal hua hai, aur koi kundli ise dikha bhi nahi sakti.'],
  ['इसके बजाय मैं आपके परिवार और घर के आने वाले महीनों के बारे में ख़ुशी से बता सकता हूँ।', 'Iske bajaye main aapke parivaar aur ghar ke aane wale mahinon ke baare mein khushi se bata sakta hoon.'],
  ['मुझे बहुत दुख है कि वे इतने बीमार हैं।', 'Mujhe bahut dukh hai ki woh itne beemar hain.'],
  ['कौन सी बीमारी है या कितनी गंभीर है, यह कुंडली से नहीं बताया जा सकता; यह सिर्फ़ डॉक्टर की जाँच से पता चलता है।', 'Kaun si bimari hai ya kitni gambhir hai, yeh kundli se nahi bataya ja sakta; yeh sirf doctor ki jaanch se pata chalta hai.'],
  ['डॉक्टर से पूछे बिना कोई दवा बंद या कम न करें: कोई रत्न या उपाय इलाज की जगह नहीं ले सकता।', 'Doctor se poochhe bina koi dawa band ya kam na karein: koi ratna ya upaay ilaaj ki jagah nahi le sakta.'],
  ['यहाँ सर्जन की राय सबसे पहले है; कुंडली से यह नहीं बताया जा सकता कि ऑपरेशन कैसा रहेगा।', 'Yahan surgeon ki raay sabse pehle hai; kundli se yeh nahi bataya ja sakta ki operation kaisa rahega.'],
  ['सबसे ज़्यादा मदद आराम, डॉक्टर की हर बात मानने और परिवार के साथ रहने से मिलती है।', 'Sabse zyada madad aaram, doctor ki har baat maanne aur parivaar ke saath rehne se milti hai.'],
  ['मुझे दुख है कि {name} की तबीयत ठीक नहीं है। कुंडली से इलाज का नतीजा नहीं बताया जा सकता; यह उनका इलाज कर रहे डॉक्टर ही बता सकते हैं।', 'Mujhe dukh hai ki {name} ki tabiyat theek nahi hai. Kundli se ilaaj ka nateeja nahi bataya ja sakta; yeh unka ilaaj kar rahe doctor hi bata sakte hain.'],
  ['उनके पास रहना, उनकी दिनचर्या शांत रखना और अपनी नींद व आराम का ध्यान रखना पूरे परिवार की मदद करता है।', 'Unke paas rehna, unki dinacharya shaant rakhna aur apni neend aur aaram ka dhyaan rakhna poore parivaar ki madad karta hai.'],
  ['आपके चार्ट से किसी और के मन की बात नहीं पढ़ी जा सकती; यह वही बता सकते हैं।', 'Aapke chart se kisi aur ke mann ki baat nahi padhi ja sakti; yeh wahi bata sakte hain.'],
  ['जानने का सबसे पक्का तरीका है उनसे शांति और ईमानदारी से, बिना दबाव के बात करना।', 'Jaanne ka sabse pakka tareeka hai unse shaanti aur imaandari se, bina dabaav ke baat karna.'],
  ['पुराने ग्रंथ किसी देश का नाम नहीं बताते, इसलिए मैं कोई देश नहीं चुनूँगा; चार्ट यह दिखाता है कि विदेश में रहने का झुकाव कितना है और कब।', 'Purane granth kisi desh ka naam nahi batate, isliye main koi desh nahi chununga; chart yeh dikhata hai ki videsh mein rehne ka jhukaav kitna hai aur kab.'],
  ['काल सर्प उन पुराने ग्रंथों में नहीं है जिन पर यह ऐप चलता है, इसलिए इससे डरने की कोई बात नहीं।', 'Kaal Sarp un purane granthon mein nahi hai jin par yeh app chalta hai, isliye isse darne ki koi baat nahi.'],
  ['अगर आप पंडित जी की सलाह को मानते हैं, तो यह आपका निर्णय है; मन की शांति के लिए सादा अनुशासन और दया काफ़ी है।', 'Agar aap pandit ji ki salah ko maante hain, to yeh aapka nirnay hai; mann ki shaanti ke liye saada anushasan aur daya kaafi hai.'],
  ['गृह प्रवेश या शादी जैसे मौकों का दिन परंपरा से परिवार के पुरोहित तय करते हैं; मुहूर्त टैब काम शुरू करने, खरीदारी, हस्ताक्षर और यात्रा जैसे कामों के लिए है।', 'Griha pravesh ya shaadi jaise mauqon ka din parampara se parivaar ke purohit tay karte hain; Muhurat tab kaam shuru karne, khareedari, hastakshar aur yatra jaise kaamon ke liye hai.'],
  ['जिस दिन को आप खुद चुनते हैं, जैसे हस्ताक्षर या कोई रस्म, उसके लिए मुहूर्त टैब अच्छे दिन बताता है।', 'Jis din ko aap khud chunte hain, jaise hastakshar ya koi rasm, uske liye Muhurat tab achhe din batata hai.'],
  ['मैं समझता हूँ कि आप एक तारीख चाहते हैं, पर कुंडली किसी घटना को महीने और समय-सीमा तक ही बता सकती है, किसी एक तारीख तक नहीं।', 'Main samajhta hoon ki aap ek tareekh chahte hain, par kundli kisi ghatna ko mahine aur samay-seema tak hi bata sakti hai, kisi ek tareekh tak nahi.'],
  ['हाँ, फिर भी आपके चार्ट से काफ़ी कुछ बताया जा सकता है।', 'Haan, phir bhi aapke chart se kaafi kuch bataya ja sakta hai.'],
  ['जन्म समय के बिना भी चार्ट से काम का जवाब मिल जाता है।', 'Janam samay ke bina bhi chart se kaam ka jawab mil jaata hai.'],
  ['उसके बाद रिकवरी और ऊर्जा के लिए आपके चार्ट में {start} से {end} तक {kind} समय है।', 'Uske baad recovery aur oorja ke liye aapke chart mein {start} se {end} tak {kind} samay hai.'],
  ['जन्म समय के बिना मैं आपकी चंद्र राशि से घर गिनता हूँ; इससे भी काफ़ी काम की तस्वीर मिलती है, बस समय अनुमानित रहता है।', 'Janam samay ke bina main aapki Chandra raashi se ghar ginta hoon; isse bhi kaafi kaam ki tasveer milti hai, bas samay anumaanit rehta hai.'],
  ['अगर जन्म का समय मिल जाए (जन्म प्रमाणपत्र, अस्पताल का रिकॉर्ड या परिवार की याद से), तो उसे प्रोफ़ाइल में जोड़ें, जवाब और सटीक होंगे।', 'Agar janam ka samay mil jaaye (janam praman patra, hospital ka record ya parivaar ki yaad se), to use profile mein jodein, jawab aur sateek honge.'],
  ['यह अनुमानित इसलिए है क्योंकि जन्म समय के बिना लग्न और घर तय नहीं होते, और जीवन-चक्र की तारीखें थोड़ी खिसक सकती हैं।', 'Yeh anumaanit isliye hai kyunki janam samay ke bina lagna aur ghar tay nahi hote, aur jeevan-chakra ki tareekhen thodi khisak sakti hain.'],
  ['क्या यह आपके अनुभव से मेल खाता है? अगर हाँ, तो इससे यह भी पता चलता है कि आपका जन्म समय सही है।', 'Kya yeh aapke anubhav se mel khaata hai? Agar haan, to isse yeh bhi pata chalta hai ki aapka janam samay sahi hai.'],
  ['पीछे देखें तो {year} एक भारी दौर में आता है: {why}।', 'Peechhe dekhein to {year} ek bhaari daur mein aata hai: {why}.'],
  ['पीछे देखें तो {year} आपके चार्ट में काफ़ी सहारा देने वाला साल था: {why}।', 'Peechhe dekhein to {year} aapke chart mein kaafi sahara dene wala saal tha: {why}.'],
  ['आपके चार्ट में सरकारी नौकरी के लिए अच्छा साथ है: अधिकार का ग्रह मज़बूत है।', 'Aapke chart mein sarkari naukri ke liye achha saath hai: adhikaar ka grah mazboot hai.'],
  ['आपके चार्ट में सरकारी नौकरी के लिए अच्छा साथ है: अधिकार का ग्रह, जो सरकार का प्रतीक है, मज़बूत है और आपके काम वाले पहलू से जुड़ा है।', 'Aapke chart mein sarkari naukri ke liye achha saath hai: adhikaar ka grah, jo sarkar ka prateek hai, mazboot hai aur aapke kaam wale pehlu se juda hai.'],
  ['आपके चार्ट में सरकारी नौकरी की ठीक-ठाक संभावना है; तैयारी बहुत कुछ तय करेगी।', 'Aapke chart mein sarkari naukri ki theek-thaak sambhavna hai; taiyari bahut kuch tay karegi.'],
  ['आपके चार्ट में सरकारी नौकरी की ठीक-ठाक संभावना है: अधिकार का ग्रह स्थिर है पर बहुत प्रबल नहीं, इसलिए तैयारी बहुत कुछ तय करेगी।', 'Aapke chart mein sarkari naukri ki theek-thaak sambhavna hai: adhikaar ka grah sthir hai par bahut prabal nahi, isliye taiyari bahut kuch tay karegi.'],
  ['सरकारी नौकरी चार्ट का सबसे मज़बूत झुकाव नहीं है, इसलिए एक प्राइवेट विकल्प भी खुला रखें।', 'Sarkari naukri chart ka sabse mazboot jhukaav nahi hai, isliye ek private vikalp bhi khula rakhein.'],
  ['सरकारी नौकरी चार्ट का सबसे मज़बूत झुकाव नहीं है; आपके अनुकूल क्षेत्रों में प्राइवेट नौकरियाँ ज़्यादा सहज दिखती हैं, इसलिए दोनों रास्ते खुले रखें।', 'Sarkari naukri chart ka sabse mazboot jhukaav nahi hai; aapke anukool kshetron mein private naukriyan zyada sahaj dikhti hain, isliye dono raaste khule rakhein.'],
  ['नियमित मॉक टेस्ट दें और कमज़ोर हिस्सों का रिवीज़न करते रहें।', 'Niyamit mock test dein aur kamzor hisson ka revision karte rahein.'],
  ['आने वाले महीनों में परीक्षा जैसे माहौल में मॉक टेस्ट दें और कमज़ोर हिस्सों का लगातार रिवीज़न करें; ज़्यादा घंटों से ज़्यादा नियमितता मायने रखती है।', 'Aane wale mahinon mein pariksha jaise maahaul mein mock test dein aur kamzor hisson ka lagaataar revision karein; zyada ghanton se zyada niyamitta maayne rakhti hai.'],
  ['अगर घरवाले शादी के लिए दबाव डाल रहे हैं, तो उन्हें बताना ठीक है कि आप पहले पढ़ाई पूरी करना चाहते हैं; कोई टीचर, स्कूल काउंसलर या चाइल्डलाइन (1098) उनसे बात करने में आपकी मदद कर सकते हैं।', 'Agar gharwale shaadi ke liye dabaav daal rahe hain, to unhe batana theek hai ki aap pehle padhai poori karna chahte hain; koi teacher, school counsellor ya Childline (1098) unse baat karne mein aapki madad kar sakte hain.'],
  ['अगर आप परीक्षा देते हैं, तो लंबे घंटों से ज़्यादा रोज़ की शांत पढ़ाई और अभ्यास काम आता है; इस उम्र में सलाहकार या अनुबंध वाली भूमिकाएँ भी देखने लायक हैं।', 'Agar aap pariksha dete hain, to lambe ghanton se zyada roz ki shaant padhai aur abhyaas kaam aata hai; is umar mein salahkaar ya contract wali bhoomikayein bhi dekhne laayak hain.'],
  ['हर हफ़्ते मॉक टेस्ट और लगातार रिवीज़न से तैयारी करें।', 'Har hafte mock test aur lagaataar revision se taiyari karein.'],
  ['रोज़ का तय समय, हर हफ़्ते एक मॉक टेस्ट और लगातार रिवीज़न के साथ तैयारी करें, और एक प्राइवेट विकल्प भी खुला रखें।', 'Roz ka tay samay, har hafte ek mock test aur lagaataar revision ke saath taiyari karein, aur ek private vikalp bhi khula rakhein.'],
  ['हर महीने सबसे पहले एक तय हिस्सा बचाएँ, तीन महीने के खर्च जितनी बचत अलग रखें, और कमज़ोर महीनों में उधार देने या बड़े दाँव से बचें।', 'Har mahine sabse pehle ek tay hissa bachayein, teen mahine ke kharche jitni bachat alag rakhein, aur kamzor mahinon mein udhaar dene ya bade daanv se bachein.'],
  ['हर कर्ज़ की सूची बनाएँ, सबसे महँगा पहले चुकाएँ, और किस्त छूटने से पहले बैंक से रीस्ट्रक्चरिंग की बात करें; चुकाते हुए भी हर महीने थोड़ी बचत करें।', 'Har karz ki list banayein, sabse mehnga pehle chukayein, aur kisht chhootne se pehle bank se restructuring ki baat karein; chukaate hue bhi har mahine thodi bachat karein.'],
  ['शांति से और लिखित में बात आगे बढ़ाएँ, और जो पैसा दिया उसका हिसाब रखें; चार्ट बेहतर समय बता सकता है, सामने वाले का फ़ैसला नहीं।', 'Shaanti se aur likhit mein baat aage badhayein, aur jo paisa diya uska hisaab rakhein; chart behtar samay bata sakta hai, saamne wale ka faisla nahi.'],
  ['पक्का करने से पहले बजट, लोन और बीमा के कागज़ात देख लें और टेस्ट ड्राइव लें; गाड़ी लेने के दिन के लिए मुहूर्त टैब देखें।', 'Pakka karne se pehle budget, loan aur beema ke kaagzaat dekh lein aur test drive lein; gaadi lene ke din ke liye Muhurat tab dekhein.'],
  ['{who} के साथ आपके रिश्ते में भरोसे का संकेत है, इसलिए साथ मिलने की अच्छी संभावना है, हालाँकि उनकी अपनी स्थिति भी मायने रखती है।', '{who} ke saath aapke rishte mein bharose ka sanket hai, isliye saath milne ki achhi sambhavna hai, haalanki unki apni sthiti bhi maayne rakhti hai.'],
  ['साथ मिलना संभव है, पर साफ़ और शांत बातचीत ज़रूरी होगी: आपके चार्ट में {who} के साथ रिश्ते में कुछ खिंचाव है।', 'Saath milna sambhav hai, par saaf aur shaant baatcheet zaroori hogi: aapke chart mein {who} ke saath rishte mein kuch khinchaav hai.'],
  ['पक्का करने से पहले बजट, कागज़ात और कानूनी मालिकाना हक़ जाँच लें; रजिस्ट्री के दिन के लिए मुहूर्त टैब देखें।', 'Pakka karne se pehle budget, kaagzaat aur kaanooni maalikana haq jaanch lein; registry ke din ke liye Muhurat tab dekhein.'],
  ['आपके चार्ट में साझेदारी को ठीक-ठाक साथ मिलता है: साझेदारी वाला पहलू और आपका अपना पहलू मेल खाते हैं। हर हिस्सेदारी और ज़िम्मेदारी लिखित में तय करें।', 'Aapke chart mein saajhedari ko theek-thaak saath milta hai: saajhedari wala pehlu aur aapka apna pehlu mel khaate hain. Har hissedari aur zimmedari likhit mein tay karein.'],
  ['आपके चार्ट में साझेदारी थोड़ी धीमी दिखती है; नियंत्रण अपने हाथ में रखना आपके लिए बेहतर है, इसलिए आगे बढ़ें तो साफ़ अनुबंध और छोटी शुरुआत करें।', 'Aapke chart mein saajhedari thodi dheemi dikhti hai; niyantran apne haath mein rakhna aapke liye behtar hai, isliye aage badhein to saaf anubandh aur chhoti shuruaat karein.'],
  ['अभी से आवेदन शुरू करें और उसी समय में बदलाव करें।', 'Abhi se aavedan shuru karein aur usi samay mein badlaav karein.'],
  ['मज़बूत समय शुरू होते ही बदलाव को साथ मिलता है, इसलिए अभी से आवेदन शुरू करें और उसी समय में बदलाव करें।', 'Mazboot samay shuru hote hi badlaav ko saath milta hai, isliye abhi se aavedan shuru karein aur usi samay mein badlaav karein.'],
  ['अभी जहाँ हैं वहीं आगे बढ़ना बेहतर है, बदलाव मज़बूत समय में करें।', 'Abhi jahan hain wahin aage badhna behtar hai, badlaav mazboot samay mein karein.'],
  ['अभी जहाँ हैं वहीं आगे बढ़ना बेहतर है और मज़बूत समय में बदलाव करें; तब तक विकल्प तैयार रखें।', 'Abhi jahan hain wahin aage badhna behtar hai aur mazboot samay mein badlaav karein; tab tak vikalp taiyaar rakhein.'],
  ['हाथ में ऑफ़र आने से पहले नौकरी न छोड़ें: अभी आवेदन करें ताकि बदलाव उसी समय में हो, और मौजूदा आमदनी बनाए रखें।', 'Haath mein offer aane se pehle naukri na chhodein: abhi aavedan karein taaki badlaav usi samay mein ho, aur maujooda aamdani banaye rakhein.'],
  ['हर हफ़्ते बात करने का एक शांत समय तय करें, पहले सुनें, और झगड़े के बीच बड़े फ़ैसले न लें।', 'Har hafte baat karne ka ek shaant samay tay karein, pehle sunein, aur jhagde ke beech bade faisle na lein.'],
  ['यहाँ उनका फ़ैसला सबसे ज़्यादा मायने रखता है; जो आपके हाथ में है उस पर ध्यान दें और बिना दबाव के रिश्ते को मौका दें।', 'Yahan unka faisla sabse zyada maayne rakhta hai; jo aapke haath mein hai us par dhyaan dein aur bina dabaav ke rishte ko mauka dein.'],
  ['माता-पिता से जल्दी और शांति से बात करें, उन्हें उस व्यक्ति को जानने का मौका दें, और उन्हें समय दें।', 'Mata-pita se jaldi aur shaanti se baat karein, unhe us vyakti ko jaanne ka mauka dein, aur unhe samay dein.'],
  ['छोटी आदतें अपनाएँ: हफ़्ते में एक बार साथ खाना, और कौन क्या करेगा इस पर साफ़ और नरम बात।', 'Chhoti aadatein apnayein: hafte mein ek baar saath khaana, aur kaun kya karega is par saaf aur naram baat.'],
  ['अगर मामला पहले से चल रहा है, तो {start} से {end} तक का समय चीज़ें सुलझाने के लिए सबसे अच्छा दिखता है।', 'Agar maamla pehle se chal raha hai, to {start} se {end} tak ka samay cheezein suljhaane ke liye sabse achha dikhta hai.'],
  ['चार्ट में आपके साझेदारी वाले पहलू पर तनाव का एक दौर दिखता है, जो लगभग {start} से हल्का होता है; आपकी शादी का फ़ैसला चार्ट नहीं करता।', 'Chart mein aapke saajhedari wale pehlu par tanaav ka ek daur dikhta hai, jo lagbhag {start} se halka hota hai; aapki shaadi ka faisla chart nahi karta.'],
  ['तो असली सवाल यह है कि आपकी शादी आगे कैसी रहेगी: {start} से {end} तक का समय आप दोनों के लिए खास तौर पर अच्छा है।', 'To asli sawaal yeh hai ki aapki shaadi aage kaisi rahegi: {start} se {end} tak ka samay aap dono ke liye khaas taur par achha hai.'],
  ['अगर आप संतान की योजना बना रहे हैं, तो यह समय उसके लिए भी अच्छा है।', 'Agar aap santaan ki yojana bana rahe hain, to yeh samay uske liye bhi achha hai.'],
  ['आप दोनों के {score} गुण 36 में से मिलते हैं, जिसे परंपरा में {verdict} माना जाता है।', 'Aap dono ke {score} gun 36 mein se milte hain, jise parampara mein {verdict} maana jaata hai.'],
  ['आपकी सबसे अच्छी बातें हैं: {good}।', 'Aapki sabse achhi baatein hain: {good}.'],
  ['जिस एक बात पर काम करना है: {work}।', 'Jis ek baat par kaam karna hai: {work}.'],
  ['कई ख़ुश जोड़ों के गुण कम मिलते हैं; आपस की बातचीत और साथ, इस संख्या से ज़्यादा मायने रखते हैं।', 'Kai khush jodon ke gun kam milte hain; aapas ki baatcheet aur saath, is sankhya se zyada maayne rakhte hain.'],
  ['शादी करनी है या नहीं, यह आपका फ़ैसला है; सिर्फ़ गुणों की संख्या से यह तय नहीं होना चाहिए।', 'Shaadi karni hai ya nahi, yeh aapka faisla hai; sirf gunon ki sankhya se yeh tay nahi hona chahiye.'],
  ['नाड़ी दोष की जो बात परिवार कर रहा है: {nadi}। पूरी तस्वीर के साथ उनसे शांति से बात करें।', 'Naadi dosh ki jo baat parivaar kar raha hai: {nadi}. Poori tasveer ke saath unse shaanti se baat karein.'],
  ['पूरा ब्योरा कम्पैटिबिलिटी स्क्रीन पर है।', 'Poora byora Compatibility screen par hai.'],
  ['मिलान के लिए मुझे उनकी जन्म तिथि, समय और जगह चाहिए: उन्हें प्रोफ़ाइल में जोड़ें, फिर कम्पैटिबिलिटी स्क्रीन खोलें या मुझसे दोबारा पूछें।', 'Milaan ke liye mujhe unki janam tithi, samay aur jagah chahiye: unhe profile mein jodein, phir Compatibility screen kholein ya mujhse dobara poochhein.'],
  ['इसे मज़बूत करने के लिए हर हफ़्ते योजनाओं और चिंताओं पर एक इत्मीनान वाली बातचीत रखें, और असहमति आने से पहले तय करें कि उसे कैसे सँभालेंगे।', 'Ise mazboot karne ke liye har hafte yojanaon aur chintaon par ek itminaan wali baatcheet rakhein, aur asahmati aane se pehle tay karein ki use kaise sambhalenge.'],
  ['इसका जवाब देने के लिए मुझे उनके अपने जन्म का ब्योरा चाहिए। उन्हें प्रोफ़ाइल में जोड़ें, फिर उनकी चैट में पूछें।', 'Iska jawab dene ke liye mujhe unke apne janam ka byora chahiye. Unhe profile mein jodein, phir unki chat mein poochhein.'],
  ['आपके दो प्रोफ़ाइल सहेजे हैं: {names}। आप कौन सी बात कर रहे हैं? उनकी चैट खोलकर पूछें या मुझे नाम बताएँ।', 'Aapke do profile save hain: {names}. Aap kaun si baat kar rahe hain? Unki chat khol kar poochhein ya mujhe naam batayein.'],
  ['यह ख़ुशी आपके बच्चों की अपनी कुंडली से दिखती है; अपने बेटे या बेटी का जन्म ब्योरा जोड़ें तो मैं उनके परिवार का समय देख सकता हूँ। आपकी अपनी कुंडली घर में सुखद साल दिखाती है, और इन्हें कैसे जीना है, यह आपका फ़ैसला है।', 'Yeh khushi aapke bachchon ki apni kundli se dikhti hai; apne bete ya beti ka janam byora jodein to main unke parivaar ka samay dekh sakta hoon. Aapki apni kundli ghar mein sukhad saal dikhati hai, aur inhe kaise jeena hai, yeh aapka faisla hai.'],
  ['इन सालों को कैसे बिताना है, यह आपका फ़ैसला है; चार्ट इत्मीनान, परिवार के साथ समय और अपने अनुभव बाँटने की ओर इशारा करता है।', 'In saalon ko kaise bitaana hai, yeh aapka faisla hai; chart itminaan, parivaar ke saath samay aur apne anubhav baantne ki or ishara karta hai.'],
  ['अगर आप इस बारे में सोच रहे हैं, तो किसी फ़र्टिलिटी विशेषज्ञ डॉक्टर से सलाह लें।', 'Agar aap is baare mein soch rahe hain, to kisi fertility specialist doctor se salah lein.'],
  ['तब तक नियमित नींद और रोज़ थोड़ी सैर सबसे ज़्यादा मदद करते हैं।', 'Tab tak niyamit neend aur roz thodi sair sabse zyada madad karte hain.'],
  ['तब तक नियमित नींद, रोज़ थोड़ी सैर और हर दिन कुछ शांत समय सबसे ज़्यादा मदद करते हैं।', 'Tab tak niyamit neend, roz thodi sair aur har din kuch shaant samay sabse zyada madad karte hain.'],
  ['आप जो महसूस कर रहे हैं, उसका कुछ हिस्सा आपके चार्ट के मौजूदा दौर से मेल खाता है: {why}।', 'Aap jo mehsoos kar rahe hain, uska kuch hissa aapke chart ke maujooda daur se mel khaata hai: {why}.'],
  ['आपके चार्ट में अभी कम ऊर्जा वाला दौर दिखता है: {why}।', 'Aapke chart mein abhi kam oorja wala daur dikhta hai: {why}.'],
  ['जल्दी गुस्सा अक्सर ज़्यादा जोश के साथ आता है: रोज़ व्यायाम, जवाब देने से पहले दस साँसों का ठहराव और पूरी नींद इस ऊर्जा को सही दिशा देते हैं।', 'Jaldi gussa aksar zyada josh ke saath aata hai: roz vyayaam, jawab dene se pehle das saanson ka thehraav aur poori neend is oorja ko sahi disha dete hain.'],
  ['आपके लिए मन की शांति पाना संभव दिखता है, और यह सादे, नियमित अभ्यास से बढ़ती है।', 'Aapke liye mann ki shaanti paana sambhav dikhta hai, aur yeh saade, niyamit abhyaas se badhti hai.'],
  ['आपको कुछ महँगा करने की ज़रूरत नहीं। {planet} के लिए पारंपरिक उपाय मुफ़्त हैं: {items}।', 'Aapko kuch mehnga karne ki zaroorat nahi. {planet} ke liye paaramparik upaay muft hain: {items}.'],
  ['ये ऐसे उपाय हैं जिनमें कोई रस्म नहीं: {items}।', 'Ye aise upaay hain jinmein koi rasm nahi: {items}.'],
  ['ये सब मुफ़्त और वैकल्पिक हैं; जो आपकी आस्था से मेल खाएँ, वही अपनाएँ, बाकी आपकी मेहनत करेगी।', 'Ye sab muft aur vaikalpik hain; jo aapki aastha se mel khaayein, wahi apnayein, baaki aapki mehnat karegi.'],
  ['परंपरा में {gem} को {planet} से जोड़ा जाता है, पर यह ज़रूरी नहीं: डर से कभी रत्न न पहनें, और यह मेहनत या इलाज की जगह नहीं लेता। फिर भी सोचें तो किसी जानकार से पूछें और ज़्यादा ख़र्च न करें।', 'Parampara mein {gem} ko {planet} se joda jaata hai, par yeh zaroori nahi: darr se kabhi ratna na pehnein, aur yeh mehnat ya ilaaj ki jagah nahi leta. Phir bhi sochein to kisi jaankaar se poochhein aur zyada kharcha na karein.'],
  ['कोई भी रत्न चीज़ों को जल्दी नहीं करवाता; अच्छे समय में नियमित दिनचर्या और मेहनत कहीं ज़्यादा काम करती है।', 'Koi bhi ratna cheezon ko jaldi nahi karwata; achhe samay mein niyamit dinacharya aur mehnat kahin zyada kaam karti hai.'],
  ['आज आपका शुभ रंग {colour} है और शुभ अंक {number}, जो {planet} से जुड़ा है।', 'Aaj aapka shubh rang {colour} hai aur shubh ank {number}, jo {planet} se juda hai.'],
  ['आपका शुभ अंक {number} है, जो आपकी चंद्र राशि के ग्रह {planet} से आता है; आज का अंक {today} है।', 'Aapka shubh ank {number} hai, jo aapki Chandra raashi ke grah {planet} se aata hai; aaj ka ank {today} hai.'],
  ['आपका शुभ दिन {weekday} है, जो आपकी चंद्र राशि के ग्रह {planet} का दिन है।', 'Aapka shubh din {weekday} hai, jo aapki Chandra raashi ke grah {planet} ka din hai.'],
  ['आज का सबसे अच्छा समय {time} है।', 'Aaj ka sabse achha samay {time} hai.'],
  ['इसे एक हल्का इशारा समझें, कोई नियम नहीं; टुडे स्क्रीन पर यह रोज़ दिखता है।', 'Ise ek halka ishara samjhein, koi niyam nahi; Today screen par yeh roz dikhta hai.'],
  ['{activity} के लिए आने वाले सबसे अच्छे दिन हैं {days}, शुभ तिथि पर और राहु काल से बचकर।', '{activity} ke liye aane wale sabse achhe din hain {days}, shubh tithi par aur Rahu Kaal se bach kar.'],
  ['अगले कुछ दिनों में {activity} के लिए कोई साफ़ समय नहीं है; मुहूर्त टैब पर आगे के हफ़्ते देखें।', 'Agle kuch dinon mein {activity} ke liye koi saaf samay nahi hai; Muhurat tab par aage ke hafte dekhein.'],
  ['ये दिन आपकी अपनी कुंडली से भी मेल खाते हैं: उस दिन का नक्षत्र आपके जन्म नक्षत्र से गिनने पर शुभ है (तारा बल), और चंद्रमा आपकी जन्म राशि से अच्छी जगह पर है (चंद्र बल)।', 'Ye din aapki apni kundli se bhi mel khaate hain: us din ka nakshatra aapke janam nakshatra se ginne par shubh hai (Tara Bal), aur Chandrama aapki janam raashi se achhi jagah par hai (Chandra Bal).'],
  ['ये दिन आपके जन्म नक्षत्र से गिनने पर अशुभ ताराओं से भी बचते हैं (तारा बल); जन्म राशि से चंद्रमा की स्थिति औसत है, इसलिए दिए गए समय में ही काम करें।', 'Ye din aapke janam nakshatra se ginne par ashubh taraon se bhi bachte hain (Tara Bal); janam raashi se Chandrama ki sthiti ausat hai, isliye diye gaye samay mein hi kaam karein.'],
  ['आगे के साफ़ दिनों में से किसी में भी आपके जन्म नक्षत्र से गिनने पर शुभ तारा नहीं है, इसलिए ये पंचांग के हिसाब से सबसे अच्छे दिन हैं; दिए गए समय में ही काम करें।', 'Aage ke saaf dinon mein se kisi mein bhi aapke janam nakshatra se ginne par shubh tara nahi hai, isliye ye panchang ke hisaab se sabse achhe din hain; diye gaye samay mein hi kaam karein.'],
  ['और विकल्प मुहूर्त टैब में मिलेंगे।', 'Aur vikalp Muhurat tab mein milenge.'],
  ['ऑपरेशन की तारीख़ पहले डॉक्टर तय करते हैं; मुहूर्त तभी मायने रखता है जब डॉक्टर विकल्प दें।', 'Operation ki tareekh pehle doctor tay karte hain; muhurat tabhi maayne rakhta hai jab doctor vikalp dein.'],
  ['हाँ: आपके चार्ट में मंगल एक पारंपरिक मांगलिक स्थिति में है।', 'Haan: aapke chart mein Mangal ek paaramparik Manglik sthiti mein hai.'],
  ['हल्का सा: मंगल एक नज़रिए से मांगलिक स्थिति में है, मुख्य नज़रिए से नहीं।', 'Halka sa: Mangal ek nazariye se Manglik sthiti mein hai, mukhya nazariye se nahi.'],
  ['मंगल मांगलिक स्थिति में है, पर आपके चार्ट में यह रद्द हो जाता है ({why}), इसलिए यह लागू नहीं होता।', 'Mangal Manglik sthiti mein hai, par aapke chart mein yeh radd ho jaata hai ({why}), isliye yeh laagu nahi hota.'],
  ['नहीं: आपके चार्ट में मंगल मांगलिक स्थिति में नहीं है।', 'Nahi: aapke chart mein Mangal Manglik sthiti mein nahi hai.'],
  ['यह बहुत आम है, लगभग आधी कुंडलियों में होता है, और असल में इसका मतलब बस कुंडली ध्यान से मिलाना है; यह कोई अशुभ संकेत नहीं।', 'Yeh bahut aam hai, lagbhag aadhi kundliyon mein hota hai, aur asal mein iska matlab bas kundli dhyaan se milaana hai; yeh koi ashubh sanket nahi.'],
  ['आप अभी साढ़ेसाती में हैं, इसके {phase} चरण में; यह लगभग {end} में खत्म होती है।', 'Aap abhi Sade Sati mein hain, iske {phase} charan mein; yeh lagbhag {end} mein khatam hoti hai.'],
  ['आप अभी साढ़ेसाती में नहीं हैं; अगली लगभग {start} में शुरू होगी।', 'Aap abhi Sade Sati mein nahi hain; agli lagbhag {start} mein shuru hogi.'],
  ['यह धीमा, ज़्यादा मेहनत माँगने वाला दौर है, ख़ासकर ऊर्जा, मन और पैसे के लिए; यह शादी, नौकरी या पढ़ाई नहीं रोकता।', 'Yeh dheema, zyada mehnat maangne wala daur hai, khaas kar oorja, mann aur paise ke liye; yeh shaadi, naukri ya padhai nahi rokta.'],
  ['साढ़ेसाती वह लगभग साढ़े सात साल का समय है जब शनि आपकी चंद्र राशि और उसके दोनों ओर की राशियों से गुज़रता है।', 'Sade Sati woh lagbhag saadhe saat saal ka samay hai jab Shani aapki Chandra raashi aur uske dono or ki raashiyon se guzarta hai.'],
  ['अभी आपकी {maha} की महादशा {end} तक चल रही है, और उसमें {antar} की अंतर्दशा {aEnd} तक।', 'Abhi aapki {maha} ki mahadasha {end} tak chal rahi hai, aur usmein {antar} ki antardasha {aEnd} tak.'],
  ['सीधे शब्दों में, यह दौर आपके जीवन का ध्यान {area} पर रखता है।', 'Seedhe shabdon mein, yeh daur aapke jeevan ka dhyaan {area} par rakhta hai.'],
  ['चार्ट के उस हिस्से में {planet} आपके {area} वाले पहलू में {nature} लाता है: {effect}', 'Chart ke us hisse mein {planet} aapke {area} wale pehlu mein {nature} laata hai: {effect}'],
  ['{year} में सबसे मज़बूत समय {a1}{a2} के लिए दिखता है: इनके सबसे अच्छे दौर इसी साल में आते हैं।', '{year} mein sabse mazboot samay {a1}{a2} ke liye dikhta hai: inke sabse achhe daur isi saal mein aate hain.'],
  ['उस समय पैसे और ऊर्जा को सँभालकर चलें, क्योंकि शनि आपकी चंद्र राशि पर दबाव डालता है।', 'Us samay paise aur oorja ko sambhal kar chalein, kyunki Shani aapki Chandra raashi par dabaav daalta hai.'],
  ['{month} में आपके जीवन-चक्र का एक नया हिस्सा भी शुरू होता है, जो ध्यान {area} की ओर ले जाता है।', '{month} mein aapke jeevan-chakra ka ek naya hissa bhi shuru hota hai, jo dhyaan {area} ki or le jaata hai.'],
  ['उस साल {a1} को सबसे पहले रखें।', 'Us saal {a1} ko sabse pehle rakhein.'],
  ['आपके लिए एक सादा अभ्यास ठीक रहेगा: {practice}।', 'Aapke liye ek saada abhyaas theek rahega: {practice}.'],
  ['उस समय {planetObl} की अंतर्दशा चलती है, जो आपके चार्ट में {topic} से जुड़ी है: {link}।', 'Us samay {planetObl} ki antardasha chalti hai, jo aapke chart mein {topic} se judi hai: {link}.'],
  ['इस इंटरव्यू का नतीजा इस पर निर्भर है कि वह कैसा गया और कंपनी को क्या चाहिए; चार्ट सिर्फ़ यह दिखाता है कि यह समय आपका कितना साथ देता है।', 'Is interview ka nateeja is par nirbhar hai ki woh kaisa gaya aur company ko kya chahiye; chart sirf yeh dikhata hai ki yeh samay aapka kitna saath deta hai.'],
  ['उसी समय बृहस्पति और शनि दोनों चार्ट के उस पहलू का साथ देते हैं, जो काम बनने का पुराना संकेत है।', 'Usi samay Brihaspati aur Shani dono chart ke us pehlu ka saath dete hain, jo kaam banne ka purana sanket hai.'],
  ['उस समय विकास का ग्रह बृहस्पति भी चार्ट के उस पहलू का साथ देता है।', 'Us samay vikas ka grah Brihaspati bhi chart ke us pehlu ka saath deta hai.'],
  ['उस समय बृहस्पति और शनि का योगदान कम है, इसलिए ज़्यादातर काम जीवन-चक्र करता है।', 'Us samay Brihaspati aur Shani ka yogdaan kam hai, isliye zyadatar kaam jeevan-chakra karta hai.'],
  ['यह देर से इसलिए आता है क्योंकि अभी का जीवन-चक्र किसी और तरफ़ इशारा करता है: {now}।', 'Yeh der se isliye aata hai kyunki abhi ka jeevan-chakra kisi aur taraf ishara karta hai: {now}.'],
  ['इससे पहले {start} से {end} का एक विकल्प भी है; यह थोड़ा हल्का है, पर इसका फ़ायदा उठाना ठीक रहेगा।', 'Isse pehle {start} se {end} ka ek vikalp bhi hai; yeh thoda halka hai, par iska fayda uthana theek rahega.'],
  ['अभी {planetObl} की अंतर्दशा {end} तक चल रही है; यह बड़े कदमों से ज़्यादा हुनर और तैयारी के लिए अच्छी है।', 'Abhi {planetObl} ki antardasha {end} tak chal rahi hai; yeh bade kadmon se zyada hunar aur taiyari ke liye achhi hai.'],
  ['इसके अलावा आपका चार्ट {start} से {end} तक {area} के लिए भी सक्रिय है।', 'Iske alawa aapka chart {start} se {end} tak {area} ke liye bhi sakriya hai.'],
  ['जिस {start} से {end} के समय की बात मैंने की,', 'Jis {start} se {end} ke samay ki baat maine ki,'],
  ['आपके चार्ट में सिर्फ़ यात्राएँ नहीं, लंबे समय तक विदेश में रहने का असली झुकाव दिखता है।', 'Aapke chart mein sirf yatrayein nahi, lambe samay tak videsh mein rehne ka asli jhukaav dikhta hai.'],
  ['आपका चार्ट विदेश में हमेशा के लिए बसने से ज़्यादा काम के मौकों और यात्राओं का साथ देता है।', 'Aapka chart videsh mein hamesha ke liye basne se zyada kaam ke mauqon aur yatraon ka saath deta hai.'],
  ['आपका चार्ट विदेश यात्रा और पढ़ाई की ओर झुकता है, पर लंबे समय का ठिकाना घर के पास।', 'Aapka chart videsh yatra aur padhai ki or jhukta hai, par lambe samay ka thikana ghar ke paas.'],
  ['{a} और {b} में से आपका चार्ट {pick} की ओर झुकता है: {why}।', '{a} aur {b} mein se aapka chart {pick} ki or jhukta hai: {why}.'],
  ['{a} और {b} दोनों को आपका चार्ट लगभग बराबर साथ देता है, इसलिए अपनी रुचि और एक छोटे अनुभव से फ़ैसला करें।', '{a} aur {b} dono ko aapka chart lagbhag barabar saath deta hai, isliye apni ruchi aur ek chhote anubhav se faisla karein.'],
  ['आपका चार्ट {kind} की ओर झुकता है: {why}।', 'Aapka chart {kind} ki or jhukta hai: {why}.'],
  ['आपके चार्ट में पद और काम के लिए एक सहायक योग भी है: {how}।', 'Aapke chart mein pad aur kaam ke liye ek sahayak yog bhi hai: {how}.'],
  ['धन के लिए भी एक सहायक योग है: {how}।', 'Dhan ke liye bhi ek sahayak yog hai: {how}.'],
  ['आपके चार्ट का एक सहायक योग इसे और बढ़ाता है: {how}।', 'Aapke chart ka ek sahayak yog ise aur badhata hai: {how}.'],
  ['ज्ञान का ग्रह आपके चंद्रमा के साथ मज़बूती से खड़ा है, जो सहारे और अच्छे नाम का संकेत है', 'gyaan ka grah aapke Chandrama ke saath mazbooti se khada hai, jo sahare aur achhe naam ka sanket hai'],
  ['{p} अपनी सबसे अच्छी स्थिति में एक प्रमुख जगह पर है, जो एक सहज, मज़बूत अंदाज़ देता है', '{p} apni sabse achhi sthiti mein ek pramukh jagah par hai, jo ek sahaj, mazboot andaaz deta hai'],
  ['आपके पद और भाग्य को चलाने वाले ग्रह साथ मिलकर काम करते हैं', 'aapke pad aur bhagya ko chalane wale grah saath milkar kaam karte hain'],
  ['आपकी आमदनी और भाग्य के ग्रह आपस में जुड़े हैं', 'aapki aamdani aur bhagya ke grah aapas mein jude hain'],
  ['मुश्किलें मेहनत के बाद तरक्की में बदल जाती हैं', 'mushkilein mehnat ke baad tarakki mein badal jaati hain'],
  ['आपके जीवन के दो हिस्से एक-दूसरे का गहरा साथ देते हैं', 'aapke jeevan ke do hisse ek-doosre ka gehra saath dete hain'],
  ['चार्ट का एक कमज़ोर पहलू नरम पड़ता है और मेहनत से ताकत बन सकता है', 'chart ka ek kamzor pehlu naram padta hai aur mehnat se taakat ban sakta hai'],
  ['नारंगी', 'naarangi'],
  ['सफ़ेद', 'safed'],
  ['लाल', 'laal'],
  ['हरा', 'hara'],
  ['पीला', 'peela'],
  ['नीला', 'neela'],
  ['सूर्य', 'Surya'],
  ['चंद्रमा', 'Chandrama'],
  ['मंगल', 'Mangal'],
  ['बुध', 'Budh'],
  ['बृहस्पति', 'Brihaspati'],
  ['शुक्र', 'Shukra'],
  ['शनि', 'Shani'],
  ['राहु', 'Rahu'],
  ['केतु', 'Ketu'],
  ['माणिक', 'maanik'],
  ['मोती', 'moti'],
  ['मूंगा', 'moonga'],
  ['पन्ना', 'panna'],
  ['पुखराज', 'pukhraj'],
  ['हीरा', 'heera'],
  ['नीलम', 'neelam'],
  ['गोमेद', 'gomed'],
  ['लहसुनिया', 'lehsuniya'],
  ['नया काम शुरू करने', 'naya kaam shuru karne'],
  ['हस्ताक्षर करने', 'hastakshar karne'],
  ['खरीदारी', 'khareedari'],
  ['यात्रा', 'yatra'],
  ['बहुत अच्छा मिलान', 'bahut achha milaan'],
  ['अच्छा मिलान', 'achha milaan'],
  ['औसत मिलान', 'ausat milaan'],
  ['कम गुण', 'kam gun'],
  ['मिलते-जुलते मूल्य', 'milte-julte moolya'],
  ['एक-दूसरे की प्राथमिकताओं का सम्मान', 'ek-doosre ki praathmiktaon ka sammaan'],
  ['एक-दूसरे की ओर सहज खिंचाव', 'ek-doosre ki or sahaj khinchaav'],
  ['फ़ैसलों में बराबरी', 'faislon mein barabari'],
  ['साथ में अच्छा भाग्य', 'saath mein achha bhagya'],
  ['मुश्किल समय में धैर्य', 'mushkil samay mein dhairya'],
  ['रोज़मर्रा का सहज साथ', 'rozmarra ka sahaj saath'],
  ['रोज़ की आदतें और सहजता', 'roz ki aadatein aur sahajta'],
  ['दोस्ताना सोच', 'dostana soch'],
  ['एक-दूसरे का नज़रिया समझना', 'ek-doosre ka nazariya samajhna'],
  ['मिलते-जुलते स्वभाव', 'milte-julte swabhav'],
  ['तनाव में बातचीत', 'tanaav mein baatcheet'],
  ['एक-दूसरे का साथ देने वाली चंद्र राशियाँ', 'ek-doosre ka saath dene wali Chandra raashiyan'],
  ['पैसे और परिवार की योजनाएँ', 'paise aur parivaar ki yojanayein'],
  ['भावनाओं का स्वस्थ तालमेल', 'bhaavnaon ka swasth taalmel'],
  ['एक-दूसरे को जगह देना', 'ek-doosre ko jagah dena'],
  ['अधिकार का ग्रह', 'adhikaar ka grah'],
  ['मन का ग्रह', 'mann ka grah'],
  ['ऊर्जा का ग्रह', 'oorja ka grah'],
  ['बुद्धि का ग्रह', 'buddhi ka grah'],
  ['विकास का ग्रह', 'vikas ka grah'],
  ['प्रेम और सुख का ग्रह', 'prem aur sukh ka grah'],
  ['अनुशासन का ग्रह', 'anushasan ka grah'],
  ['महत्वाकांक्षा का बिंदु', 'mahatvakanksha ka bindu'],
  ['एकाग्रता और गहराई का बिंदु', 'ekagrata aur gehraai ka bindu'],
  ['यह आपके {area} वाले पहलू को चलाता है', 'yeh aapke {area} wale pehlu ko chalata hai'],
  ['यह आपके {area} वाले पहलू में है', 'yeh aapke {area} wale pehlu mein hai'],
  ['आप दोनों की कुंडली में यह पारंपरिक नियमों से रद्द हो जाता है', 'aap dono ki kundli mein yeh paaramparik niyamon se radd ho jaata hai'],
  ['यह कागज़ पर है, पर यह आठ में से एक बात है और सेहत या संतान के बारे में कुछ पक्का नहीं कहती', 'yeh kaagaz par hai, par yeh aath mein se ek baat hai aur sehat ya santaan ke baare mein kuch pakka nahi kehti'],
  ['आप दोनों की कुंडली में नाड़ी दोष नहीं है', 'aap dono ki kundli mein naadi dosh nahi hai'],
  ['मंगल अपनी राशि में है', 'Mangal apni raashi mein hai'],
  ['मंगल उच्च का है', 'Mangal uchch ka hai'],
  ['उस राशि का पारंपरिक अपवाद लागू होता है', 'us raashi ka paaramparik apvaad laagu hota hai'],
  ['बृहस्पति उस स्थिति की रक्षा करता है', 'Brihaspati us sthiti ki raksha karta hai'],
  ['पहले', 'pehle'],
  ['बीच के (सबसे भारी)', 'beech ke (sabse bhaari)'],
  ['आख़िरी', 'aakhri'],
  ['अधिकार और अहं', 'adhikaar aur aham'],
  ['भावना और परवाह', 'bhaavna aur parvaah'],
  ['ऊर्जा और जोश', 'oorja aur josh'],
  ['सोच और बातचीत', 'soch aur baatcheet'],
  ['विकास और समझ', 'vikas aur samajh'],
  ['सुख और आकर्षण', 'sukh aur aakarshan'],
  ['ज़िम्मेदारी और धैर्य', 'zimmedari aur dhairya'],
  ['तेज़ इच्छाएँ और अलग रास्ते', 'tez ichchhayein aur alag raaste'],
  ['वैराग्य और गहराई', 'vairagya aur gehraai'],
  ['इसे समझदारी से साधना होता है, यह कोई अशुभ संकेत नहीं।', 'ise samajhdari se saadhna hota hai, yeh koi ashubh sanket nahi.'],
  ['और हाँ, आपके चार्ट में यह सच में वहीं है।', 'Aur haan, aapke chart mein yeh sach mein wahin hai.'],
  ['हालाँकि आपके अपने चार्ट में यह कहीं और है, इसलिए यह सामान्य बात है।', 'Haalanki aapke apne chart mein yeh kahin aur hai, isliye yeh saamanya baat hai.'],
  ['रास्ते की बात करें तो आपका चार्ट इस ओर झुकता है: {label}, क्योंकि {why}।', 'Raaste ki baat karein to aapka chart is or jhukta hai: {label}, kyunki {why}.'],
  ['आपके लिए पैसा सबसे सहज रूप से {items} से आता है।', 'Aapke liye paisa sabse sahaj roop se {items} se aata hai.'],
  ['चार्ट में अभी यह दिखता है: {items}। यह एक दौर है, अंत नहीं।', 'Chart mein abhi yeh dikhta hai: {items}. Yeh ek daur hai, ant nahi.'],
  ['इसमें दिखता है: {items}।', 'Ismein dikhta hai: {items}.'],
  ['{who} के साथ आपके चार्ट में दिखता है: {items}।', '{who} ke saath aapke chart mein dikhta hai: {items}.'],
  ['इसका कुछ हिस्सा मौजूदा दौर से है: {why}।', 'Iska kuch hissa maujooda daur se hai: {why}.'],
  ['यह क्षेत्र', 'yeh kshetra'],
  ['मज़बूत, सहायक', 'mazboot, sahayak'],
  ['अच्छी संभावना वाला सहायक', 'achhi sambhavna wala sahayak'],
  ['आपकी सेहत के लिए सबसे ज़्यादा मदद करने वाली आदतें हैं: {items}।', 'Aapki sehat ke liye sabse zyada madad karne wali aadatein hain: {items}.'],
  ['अभी आप इस दौर में हैं: {items}।', 'Abhi aap is daur mein hain: {items}.'],
  ['अगर यह उनके अपने मामले की बात है, तो उनका जन्म ब्योरा जोड़ें, फिर मैं उनकी कुंडली सीधे देख सकूँगा।', 'Agar yeh unke apne maamle ki baat hai, to unka janam byora jodein, phir main unki kundli seedhe dekh sakunga.'],
  ['{p} की अंतर्दशा {e} तक चलती है', '{p} ki antardasha {e} tak chalti hai'],
  ['आईटी', 'IT'],
  ['फ़ाइनेंस', 'finance'],
  ['पढ़ाना', 'padhana'],
  ['कॉर्पोरेट नौकरी', 'corporate naukri'],
  ['इंजीनियरिंग', 'engineering'],
  ['डिज़ाइन', 'design'],
  ['मेडिकल', 'medical'],
  ['सरकारी नौकरी', 'sarkari naukri'],
  ['सेल्स', 'sales'],
  ['प्राइवेट नौकरी', 'private naukri'],
  ['एमबीए', 'MBA'],
  ['एमएस', 'MS'],
  ['साइंस', 'science'],
  ['कॉमर्स', 'commerce'],
  ['ध्यान', 'dhyaan'],
  ['भक्ति', 'bhakti'],
  ['भाई', 'bhai'],
  ['बहन', 'behen'],
  ['पिता', 'pita'],
  ['माँ', 'maa'],
  ['माता-पिता', 'mata-pita'],
  ['भाई-बहन', 'bhai-behen'],
  ['ससुराल वालों', 'sasural walon'],
  ['घर वालों', 'ghar walon'],
  ['अधिकार और नेतृत्व का ग्रह', 'adhikaar aur netritva ka grah'],
  ['देखभाल और भावनाओं का ग्रह', 'dekhbhaal aur bhaavnaon ka grah'],
  ['ऊर्जा और साहस का ग्रह', 'oorja aur saahas ka grah'],
  ['बुद्धि और संवाद का ग्रह', 'buddhi aur samvaad ka grah'],
  ['ज्ञान और विकास का ग्रह', 'gyaan aur vikas ka grah'],
  ['सौंदर्य और रचनात्मकता का ग्रह', 'saundarya aur rachnatmakta ka grah'],
  ['अनुशासन और मेहनत का ग्रह', 'anushasan aur mehnat ka grah'],
  ['महत्वाकांक्षा और नए रास्तों का बिंदु', 'mahatvakanksha aur naye raaston ka bindu'],
  ['बारीक नवांश चार्ट में आपके काम वाले पहलू की दिशा {p} तय करता है', 'baareek navamsha chart mein aapke kaam wale pehlu ki disha {p} tay karta hai'],
  ['आपके करियर चार्ट में काम की बागडोर {p} के हाथ में है', 'aapke career chart mein kaam ki baagdor {p} ke haath mein hai'],
  ['आपके सूर्य से गिनने पर भी आपके {area} वाले पहलू की दिशा {p} तय करता है', 'aapke Surya se ginne par bhi aapke {area} wale pehlu ki disha {p} tay karta hai'],
  ['आपके चंद्रमा से गिनने पर भी आपके {area} वाले पहलू की दिशा {p} तय करता है', 'aapke Chandrama se ginne par bhi aapke {area} wale pehlu ki disha {p} tay karta hai'],
  ['आपके चार्ट में जीवनसाथी का संकेत {p} देता है', 'aapke chart mein jeevansaathi ka sanket {p} deta hai'],
  ['विवाह चार्ट भी {p} की ओर इशारा करता है', 'vivah chart bhi {p} ki or ishara karta hai'],
  ['चार्ट का एक बारीक हिस्सा भी {p} की ओर इशारा करता है', 'chart ka ek baareek hissa bhi {p} ki or ishara karta hai'],
  ['{p} आपके चार्ट के एक सहायक योग का हिस्सा है', '{p} aapke chart ke ek sahayak yog ka hissa hai'],
  ['आपके {area} वाले पहलू की दिशा {p} तय करता है', 'aapke {area} wale pehlu ki disha {p} tay karta hai'],
  ['{p} की नज़र आपके {area} वाले पहलू पर है', '{p} ki nazar aapke {area} wale pehlu par hai'],
  ['{p} आपके {area} वाले पहलू को चलाने वाले ग्रह के साथ बैठा है', '{p} aapke {area} wale pehlu ko chalane wale grah ke saath baitha hai'],
  ['आपके चार्ट में काम की दिशा {p} दिखाता है', 'aapke chart mein kaam ki disha {p} dikhata hai'],
  ['{p} आपके चार्ट में मज़बूत है', '{p} aapke chart mein mazboot hai'],
  ['{p} स्वाभाविक रूप से जीवन के इस पहलू से जुड़ा है', '{p} swabhavik roop se jeevan ke is pehlu se juda hai'],
  ['सरकारी और नेतृत्व वाले काम', 'sarkari aur netritva wale kaam'],
  ['सरकारी, प्रशासन और नेतृत्व वाले काम', 'sarkari, prashasan aur netritva wale kaam'],
  ['सिविल सेवा, सरकारी विभाग, टीम लीड या मैनेजर, नीति से जुड़ा काम', 'civil seva, sarkari vibhaag, team lead ya manager, neeti se juda kaam'],
  ['सिविल सेवा', 'civil seva'],
  ['सरकारी विभाग', 'sarkari vibhaag'],
  ['टीम लीड या मैनेजर', 'team lead ya manager'],
  ['नीति से जुड़ा काम', 'neeti se juda kaam'],
  ['सेवा और लोगों से जुड़ा काम', 'seva aur logon se juda kaam'],
  ['देखभाल, सेवा और लोगों से जुड़ा काम', 'dekhbhaal, seva aur logon se juda kaam'],
  ['स्वास्थ्य सेवा, होटल और पर्यटन, कस्टमर सर्विस, एचआर', 'swasthya seva, hotel aur paryatan, customer service, HR'],
  ['स्वास्थ्य सेवा', 'swasthya seva'],
  ['होटल और पर्यटन', 'hotel aur paryatan'],
  ['कस्टमर सर्विस', 'customer service'],
  ['एचआर', 'HR'],
  ['इंजीनियरिंग और तकनीकी काम', 'engineering aur takneeki kaam'],
  ['इंजीनियरिंग, तकनीकी और जोश वाले काम', 'engineering, takneeki aur josh wale kaam'],
  ['मैकेनिकल या सिविल इंजीनियरिंग, रक्षा या पुलिस, सर्जरी, खेल, रियल एस्टेट', 'mechanical ya civil engineering, raksha ya police, surgery, khel, real estate'],
  ['मैकेनिकल या सिविल इंजीनियरिंग', 'mechanical ya civil engineering'],
  ['रक्षा या पुलिस', 'raksha ya police'],
  ['सर्जरी', 'surgery'],
  ['खेल', 'khel'],
  ['रियल एस्टेट', 'real estate'],
  ['टेक्नोलॉजी और डेटा', 'technology aur data'],
  ['टेक्नोलॉजी, डेटा और संवाद से जुड़ा काम', 'technology, data aur samvaad se juda kaam'],
  ['सॉफ़्टवेयर, डेटा एनालिसिस, लेखन और कंटेंट, सेल्स, अकाउंट्स', 'software, data analysis, lekhan aur content, sales, accounts'],
  ['सॉफ़्टवेयर', 'software'],
  ['डेटा एनालिसिस', 'data analysis'],
  ['लेखन और कंटेंट', 'lekhan aur content'],
  ['अकाउंट्स', 'accounts'],
  ['सलाह और वित्त का काम', 'salah aur vitt ka kaam'],
  ['शिक्षा, कानून, वित्त और सलाह से जुड़ा काम', 'shiksha, kaanoon, vitt aur salah se juda kaam'],
  ['पढ़ाना या ट्रेनिंग, कानून, बैंकिंग और वित्त, कंसल्टिंग, काउंसलिंग', 'padhana ya training, kaanoon, banking aur vitt, consulting, counselling'],
  ['पढ़ाना या ट्रेनिंग', 'padhana ya training'],
  ['कानून', 'kaanoon'],
  ['बैंकिंग और वित्त', 'banking aur vitt'],
  ['कंसल्टिंग', 'consulting'],
  ['काउंसलिंग', 'counselling'],
  ['डिज़ाइन और रचनात्मक मीडिया', 'design aur rachnatmak media'],
  ['डिज़ाइन, कला, मीडिया और रचनात्मक काम', 'design, kala, media aur rachnatmak kaam'],
  ['UI/UX या प्रोडक्ट डिज़ाइन, ग्राफ़िक डिज़ाइन, मीडिया और मार्केटिंग, फ़ैशन', 'UI/UX ya product design, graphic design, media aur marketing, fashion'],
  ['UI/UX या प्रोडक्ट डिज़ाइन', 'UI/UX ya product design'],
  ['ग्राफ़िक डिज़ाइन', 'graphic design'],
  ['मीडिया और मार्केटिंग', 'media aur marketing'],
  ['फ़ैशन', 'fashion'],
  ['संचालन और सिस्टम का काम', 'sanchaalan aur system ka kaam'],
  ['संचालन, सिस्टम और लंबे समय वाले व्यवस्थित काम', 'sanchaalan, system aur lambe samay wale vyavasthit kaam'],
  ['संचालन और प्रोजेक्ट मैनेजमेंट, इन्फ्रास्ट्रक्चर या बैकएंड इंजीनियरिंग, मैन्युफैक्चरिंग, सरकारी सेवा, रिसर्च', 'sanchaalan aur project management, infrastructure ya backend engineering, manufacturing, sarkari seva, research'],
  ['संचालन और प्रोजेक्ट मैनेजमेंट', 'sanchaalan aur project management'],
  ['इन्फ्रास्ट्रक्चर या बैकएंड इंजीनियरिंग', 'infrastructure ya backend engineering'],
  ['मैन्युफैक्चरिंग', 'manufacturing'],
  ['सरकारी सेवा', 'sarkari seva'],
  ['रिसर्च', 'research'],
  ['नई टेक्नोलॉजी और एआई', 'nayi technology aur AI'],
  ['नई टेक्नोलॉजी, एआई, विदेशी कंपनियाँ और अलग रास्ते', 'nayi technology, AI, videshi companiyan aur alag raaste'],
  ['एआई और नई टेक्नोलॉजी, स्टार्टअप, विदेशी या मल्टीनेशनल कंपनी, डिजिटल मीडिया', 'AI aur nayi technology, startup, videshi ya multinational company, digital media'],
  ['एआई और नई टेक्नोलॉजी', 'AI aur nayi technology'],
  ['स्टार्टअप', 'startup'],
  ['विदेशी या मल्टीनेशनल कंपनी', 'videshi ya multinational company'],
  ['डिजिटल मीडिया', 'digital media'],
  ['रिसर्च और खास तकनीकी काम', 'research aur khaas takneeki kaam'],
  ['रिसर्च, कोडिंग और खास तकनीकी काम', 'research, coding aur khaas takneeki kaam'],
  ['रिसर्च, कोडिंग, डेटा साइंस, किसी खास तकनीक में महारत', 'research, coding, data science, kisi khaas technique mein mahaarat'],
  ['कोडिंग', 'coding'],
  ['डेटा साइंस', 'data science'],
  ['किसी खास तकनीक में महारत', 'kisi khaas technique mein mahaarat'],
  ['आत्मविश्वासी, उसूलों वाला और नेतृत्व करने वाला', 'aatmavishvaasi, usoolon wala aur netritva karne wala'],
  ['ख्याल रखने वाला, भावुक और परिवार से जुड़ा', 'khayal rakhne wala, bhaavuk aur parivaar se juda'],
  ['ऊर्जावान, सीधी बात करने वाला और रक्षा करने वाला', 'oorjavaan, seedhi baat karne wala aur raksha karne wala'],
  ['हाज़िरजवाब, बातूनी और समझदार', 'haazirjawab, baatooni aur samajhdaar'],
  ['समझदार, दयालु और पढ़ा-लिखा', 'samajhdaar, dayalu aur padha-likha'],
  ['आकर्षक, कलात्मक और प्यार करने वाला', 'aakarshak, kalaatmak aur pyaar karne wala'],
  ['परिपक्व, ज़िम्मेदार और वफ़ादार, शायद उम्र में थोड़ा बड़ा', 'paripakva, zimmedaar aur wafadaar, shayad umar mein thoda bada'],
  ['महत्वाकांक्षी और अलग सोच वाला, शायद अलग माहौल से', 'mahatvakankshi aur alag soch wala, shayad alag maahaul se'],
  ['शांत, आध्यात्मिक और आत्मनिर्भर', 'shaant, aadhyatmik aur aatmanirbhar'],
  ['शायद पहला कदम आप खुद उठाएँगे', 'shayad pehla kadam aap khud uthayenge'],
  ['परिवार के ज़रिए', 'parivaar ke zariye'],
  ['दोस्तों, भाई-बहनों या सोशल मीडिया के ज़रिए', 'doston, bhai-behenon ya social media ke zariye'],
  ['घर के पास, परिवार के जान-पहचान वालों से', 'ghar ke paas, parivaar ke jaan-pehchaan walon se'],
  ['प्रेम, पढ़ाई या किसी साझा शौक के ज़रिए', 'prem, padhai ya kisi saajha shauk ke zariye'],
  ['काम की जगह पर या सेवा के दौरान', 'kaam ki jagah par ya seva ke dauraan'],
  ['रिश्ते की बात या किसी साझेदारी के ज़रिए', 'rishte ki baat ya kisi saajhedari ke zariye'],
  ['अचानक, अनपेक्षित तरीके से', 'achanak, anapekshit tareeke se'],
  ['यात्रा, गुरुओं या पढ़ाई की जगह के ज़रिए', 'yatra, guruon ya padhai ki jagah ke zariye'],
  ['काम या करियर के दायरे में', 'kaam ya career ke daayre mein'],
  ['दोस्तों और जान-पहचान के बड़े दायरे से', 'doston aur jaan-pehchaan ke bade daayre se'],
  ['घर से दूर, विदेश में या ऑनलाइन', 'ghar se door, videsh mein ya online'],
  ['स्थिर वेतन, सरकारी काम या ऊँचे पद', 'sthir vetan, sarkari kaam ya oonche pad'],
  ['लोगों से जुड़ा काम, खाना, होटल या रोज़मर्रा की चीज़ें', 'logon se juda kaam, khaana, hotel ya rozmarra ki cheezein'],
  ['प्रॉपर्टी, इंजीनियरिंग या तकनीकी हुनर', 'property, engineering ya takneeki hunar'],
  ['हुनर, व्यापार, फ्रीलांसिंग और कमीशन', 'hunar, vyapar, freelancing aur commission'],
  ['सलाह, पढ़ाना, वित्त और लंबे समय के निवेश', 'salah, padhana, vitt aur lambe samay ke nivesh'],
  ['रचनात्मक काम, डिज़ाइन, सौंदर्य, लग्ज़री सामान या कला', 'rachnatmak kaam, design, saundarya, luxury saamaan ya kala'],
  ['लंबे समय का स्थिर काम और धीरे-धीरे की बचत', 'lambe samay ka sthir kaam aur dheere-dheere ki bachat'],
  ['टेक्नोलॉजी, विदेशी स्रोत या नए ज़माने के काम (सट्टे से दूर रहें)', 'technology, videshi srot ya naye zamaane ke kaam (satte se door rahein)'],
  ['खास हुनर या रिसर्च, और कभी-कभी अचानक फ़ायदा', 'khaas hunar ya research, aur kabhi-kabhi achanak fayda'],
  ['राजनीति विज्ञान, लोक प्रशासन या मैनेजमेंट', 'rajneeti vigyaan, lok prashasan ya management'],
  ['राजनीति विज्ञान या मैनेजमेंट', 'rajneeti vigyaan ya management'],
  ['मनोविज्ञान, नर्सिंग, होटल मैनेजमेंट या फ़ूड साइंस', 'manovigyaan, nursing, hotel management ya food science'],
  ['मनोविज्ञान, नर्सिंग या होटल मैनेजमेंट', 'manovigyaan, nursing ya hotel management'],
  ['इंजीनियरिंग, मेडिकल या स्पोर्ट्स साइंस', 'engineering, medical ya sports science'],
  ['इंजीनियरिंग या मेडिकल', 'engineering ya medical'],
  ['कंप्यूटर साइंस, गणित, कॉमर्स, भाषाएँ या पत्रकारिता', 'computer science, ganit, commerce, bhashayein ya patrakarita'],
  ['कंप्यूटर साइंस, गणित या कॉमर्स', 'computer science, ganit ya commerce'],
  ['कानून, वित्त, शिक्षा, मैनेजमेंट या दर्शन', 'kaanoon, vitt, shiksha, management ya darshan'],
  ['कानून, वित्त या शिक्षा', 'kaanoon, vitt ya shiksha'],
  ['डिज़ाइन, ललित कला, संगीत, फ़ैशन या आर्किटेक्चर', 'design, lalit kala, sangeet, fashion ya architecture'],
  ['डिज़ाइन, ललित कला या आर्किटेक्चर', 'design, lalit kala ya architecture'],
  ['सिविल या मैकेनिकल इंजीनियरिंग, भूविज्ञान, रिसर्च या लोक प्रशासन', 'civil ya mechanical engineering, bhoovigyaan, research ya lok prashasan'],
  ['सिविल इंजीनियरिंग या रिसर्च', 'civil engineering ya research'],
  ['कंप्यूटर साइंस और एआई, विदेशी भाषाएँ, एविएशन या मीडिया', 'computer science aur AI, videshi bhashayein, aviation ya media'],
  ['कंप्यूटर साइंस और एआई, या मीडिया', 'computer science aur AI, ya media'],
  ['रिसर्च, गणित, कोडिंग या जीव विज्ञान', 'research, ganit, coding ya jeev vigyaan'],
  ['रिसर्च, कोडिंग या जीव विज्ञान', 'research, coding ya jeev vigyaan'],
  ['नेतृत्व और आत्मविश्वास', 'netritva aur aatmavishvaas'],
  ['अहं; कभी-कभी दूसरों को आगे आने दें', 'aham; kabhi-kabhi doosron ko aage aane dein'],
  ['सहानुभूति और लोगों की परवाह', 'sahanubhooti aur logon ki parvaah'],
  ['मूड का उतार-चढ़ाव; आराम का ध्यान रखें', 'mood ka utaar-chadhaav; aaram ka dhyaan rakhein'],
  ['साहस और जोश', 'saahas aur josh'],
  ['अधीरता और जल्दी गुस्सा', 'adheerta aur jaldi gussa'],
  ['तेज़ दिमाग और बातचीत का हुनर', 'tez dimaag aur baatcheet ka hunar'],
  ['ज़रूरत से ज़्यादा सोचना', 'zaroorat se zyada sochna'],
  ['समझदारी और दूसरों को राह दिखाने का गुण', 'samajhdaari aur doosron ko raah dikhane ka gun'],
  ['ज़रूरत से ज़्यादा वादे करना', 'zaroorat se zyada vaade karna'],
  ['अच्छी पसंद, आकर्षण और तालमेल', 'achhi pasand, aakarshan aur taalmel'],
  ['आराम की ज़्यादा चाह', 'aaram ki zyada chaah'],
  ['अनुशासन, धैर्य और टिके रहने की ताकत', 'anushasan, dhairya aur tike rehne ki taakat'],
  ['खुद पर शक और टालमटोल', 'khud par shak aur taalmatol'],
  ['महत्वाकांक्षा और नए विचार', 'mahatvakanksha aur naye vichaar'],
  ['बेचैनी', 'bechaini'],
  ['एकाग्रता, गहराई और अंतर्ज्ञान', 'ekagrata, gehraai aur antargyaan'],
  ['दूरी बना लेना; लोगों से जुड़े रहें', 'doori bana lena; logon se jude rahein'],
  ['सुबह की धूप, समय पर उठना और दिल व आँखों का ख्याल', 'subah ki dhoop, samay par uthna aur dil aur aankhon ka khayal'],
  ['अच्छी नींद, भरपूर पानी और मन का आराम', 'achhi neend, bharpoor paani aur mann ka aaram'],
  ['तनाव निकालने के लिए नियमित व्यायाम, और चोट से बचाव', 'tanaav nikaalne ke liye niyamit vyayaam, aur chot se bachaav'],
  ['स्क्रीन से ब्रेक, साँस के अभ्यास और मन का सुकून', 'screen se break, saans ke abhyaas aur mann ka sukoon'],
  ['हल्का खाना और वज़न व शुगर पर नज़र', 'halka khaana aur wazan aur sugar par nazar'],
  ['संतुलित भोजन, कम मीठा और भरपूर पानी', 'santulit bhojan, kam meetha aur bharpoor paani'],
  ['स्ट्रेचिंग, गरमाहट और नियमित दिनचर्या, जोड़ों और हड्डियों के लिए', 'stretching, garmahat aur niyamit dinacharya, jodon aur haddiyon ke liye'],
  ['तय दिनचर्या और कम स्क्रीन टाइम, ताकि बेचैनी घटे', 'tay dinacharya aur kam screen time, taaki bechaini ghate'],
  ['सादा खाना, पाचन का ख्याल और नियमित जाँच', 'saada khaana, paachan ka khayal aur niyamit jaanch'],
  ['राजधानी या प्रशासनिक शहर', 'rajdhani ya prashasnik shehar'],
  ['पानी या समुद्र के पास की जगह', 'paani ya samudra ke paas ki jagah'],
  ['व्यस्त औद्योगिक या टेक शहर', 'vyast audyogik ya tech shehar'],
  ['व्यापारिक शहर', 'vyapaarik shehar'],
  ['शिक्षा और संस्कृति वाला शहर', 'shiksha aur sanskriti wala shehar'],
  ['रौनक वाला, रचनात्मक और खुला शहर', 'raunak wala, rachnatmak aur khula shehar'],
  ['पुराना, शांत या औद्योगिक शहर', 'purana, shaant ya audyogik shehar'],
  ['बड़ा अंतरराष्ट्रीय शहर', 'bada antarrashtriya shehar'],
  ['शांत, छोटी जगह', 'shaant, chhoti jagah'],
  ['विदेश में रहना या काम करना', 'videsh mein rehna ya kaam karna'],
  ['अपने ही इलाके के पास जीवन बनाना', 'apne hi ilaake ke paas jeevan banana'],
  ['विदेश में काम के मौके या यात्राएँ, पर जड़ें घर पर', 'videsh mein kaam ke mauke ya yatrayein, par jadein ghar par'],
  ['आपके साझेदारी और मेहनत वाले पहलू मज़बूत हैं, और व्यापार का ग्रह उनका साथ देता है', 'aapke saajhedari aur mehnat wale pehlu mazboot hain, aur vyapar ka grah unka saath deta hai'],
  ['आपके रोज़ के काम और करियर वाले पहलू व्यापार वाले पहलू से ज़्यादा स्थिर हैं', 'aapke roz ke kaam aur career wale pehlu vyapar wale pehlu se zyada sthir hain'],
  ['आपके करियर और व्यापार वाले पहलू लगभग बराबर मज़बूत हैं', 'aapke career aur vyapar wale pehlu lagbhag barabar mazboot hain'],
  ['अपना व्यापार या स्वतंत्र काम', 'apna vyapar ya swatantra kaam'],
  ['नौकरी, किसी संस्था में स्थिर तरक्की के साथ', 'naukri, kisi sanstha mein sthir tarakki ke saath'],
  ['पहले नौकरी, साथ में धीरे-धीरे बढ़ने वाला छोटा व्यापार', 'pehle naukri, saath mein dheere-dheere badhne wala chhota vyapar'],
  ['अहं और अलग सोच, जिसमें समय के साथ सम्मान बढ़ता है', 'aham aur alag soch, jismein samay ke saath sammaan badhta hai'],
  ['गहरी परवाह, पर भावनाओं का कुछ उतार-चढ़ाव', 'gehri parvaah, par bhaavnaon ka kuch utaar-chadhaav'],
  ['जल्दी गुस्सा और पक्की राय, पर भीतर सच्ची वफ़ादारी', 'jaldi gussa aur pakki raay, par bheetar sachchi wafadaari'],
  ['बहुत बातें और बहस, जहाँ साफ़ शब्द ज़्यादातर बात सुलझा देते हैं', 'bahut baatein aur behas, jahan saaf shabd zyadatar baat suljha dete hain'],
  ['अपनापन, मार्गदर्शन और सच्चा सहारा', 'apnapan, margdarshan aur sachcha sahara'],
  ['स्नेह और मेल-जोल की चाह', 'sneh aur mel-jol ki chaah'],
  ['ज़िम्मेदारियाँ और थोड़ी दूरी, कोई स्थायी दरार नहीं', 'zimmedariyan aur thodi doori, koi sthaayi daraar nahi'],
  ['उलझे संकेत और बेचैनी, जो ईमानदारी से शांत होती है', 'uljhe sanket aur bechaini, jo imaandari se shaant hoti hai'],
  ['थोड़ी भावनात्मक दूरी, जहाँ एक-दूसरे को जगह देना मदद करता है', 'thodi bhaavnaatmak doori, jahan ek-doosre ko jagah dena madad karta hai'],
  ['ससुराल', 'sasural'],
  ['घर', 'ghar'],
  ['अपने उदाहरण से राह दिखाना और उसूलों पर चलना', 'apne udaharan se raah dikhana aur usoolon par chalna'],
  ['सुबह की धूप में कुछ शांत पल, दिन का संकल्प लेने के लिए', 'subah ki dhoop mein kuch shaant pal, din ka sankalp lene ke liye'],
  ['भक्ति और दूसरों की देखभाल', 'bhakti aur doosron ki dekhbhaal'],
  ['हर सुबह कुछ मिनट प्रार्थना, संगीत या जप', 'har subah kuch minute prarthana, sangeet ya jap'],
  ['अनुशासित अभ्यास और साहस', 'anushaasit abhyaas aur saahas'],
  ['रोज़ एक ही समय पर योग या सैर, एक साधना की तरह', 'roz ek hi samay par yoga ya sair, ek saadhna ki tarah'],
  ['सीखना, लिखना और सिखाना', 'seekhna, likhna aur sikhaana'],
  ['हर रात दस मिनट डायरी लिखना', 'har raat das minute diary likhna'],
  ['ज्ञान और समझ बाँटना', 'gyaan aur samajh baantna'],
  ['रोज़ किसी अच्छी किताब की कुछ पंक्तियाँ पढ़ना और सीखी बात बाँटना', 'roz kisi achhi kitaab ki kuch panktiyan padhna aur seekhi baat baantna'],
  ['सुंदरता, संगीत और कला के ज़रिए भक्ति', 'sundarta, sangeet aur kala ke zariye bhakti'],
  ['गाना, संगीत या शांत समय के लिए एक छोटी साफ़ जगह रखना', 'gaana, sangeet ya shaant samay ke liye ek chhoti saaf jagah rakhna'],
  ['सेवा और लगातार, ईमानदार काम', 'seva aur lagaataar, imaandaar kaam'],
  ['हर दिन दस शांत मिनट और सेवा का एक काम', 'har din das shaant minute aur seva ka ek kaam'],
  ['खुले मन से नए रास्ते और विचार तलाशना', 'khule mann se naye raaste aur vichaar talaashna'],
  ['किसी एक अभ्यास को पूरा एक महीना करके देखना, फिर परखना', 'kisi ek abhyaas ko poora ek mahina karke dekhna, phir parakhna'],
  ['ध्यान और भीतर की शांति', 'dhyaan aur bheetar ki shaanti'],
  ['सुबह या रात दस मिनट चुपचाप बैठना', 'subah ya raat das minute chupchaap baithna'],
  ['जल्दी उठकर सुबह की धूप में बैठना, पिता और बड़ों का सम्मान, और चाहें तो गायत्री मंत्र या आदित्य हृदय', 'jaldi uth kar subah ki dhoop mein baithna, pita aur badon ka sammaan, aur chahein to Gayatri mantra ya Aditya Hriday'],
  ['जल्दी उठना, सुबह की धूप लेना और हर हफ़्ते किसी बुज़ुर्ग की मदद करना', 'jaldi uthna, subah ki dhoop lena aur har hafte kisi buzurg ki madad karna'],
  ['नियमित नींद, पानी के पास कुछ समय, माँ से बात करना, और चाहें तो शिव की प्रार्थना; किसी ज़रूरतमंद को पानी या दूध देना', 'niyamit neend, paani ke paas kuch samay, maa se baat karna, aur chahein to Shiv ki prarthana; kisi zaroorat-mand ko paani ya doodh dena'],
  ['नियमित नींद, पानी के पास समय और माँ से बात करना', 'niyamit neend, paani ke paas samay aur maa se baat karna'],
  ['रोज़ व्यायाम, गुस्से को खेल में बदलना, भाई-बहनों की मदद, और चाहें तो हनुमान चालीसा', 'roz vyayaam, gusse ko khel mein badalna, bhai-behenon ki madad, aur chahein to Hanuman Chalisa'],
  ['रोज़ व्यायाम, ऊर्जा के लिए कोई खेल और भाई-बहनों की मदद', 'roz vyayaam, oorja ke liye koi khel aur bhai-behenon ki madad'],
  ['रोज़ कुछ नया सीखना, हिसाब साफ़ रखना, विद्यार्थियों की मदद, और चाहें तो विष्णु सहस्रनाम', 'roz kuch naya seekhna, hisaab saaf rakhna, vidyarthiyon ki madad, aur chahein to Vishnu Sahasranaam'],
  ['रोज़ कुछ सीखना, हिसाब साफ़ रखना और किसी विद्यार्थी की मदद', 'roz kuch seekhna, hisaab saaf rakhna aur kisi vidyarthi ki madad'],
  ['पढ़ना या पढ़ाना, गुरुओं का सम्मान, किताबें या भोजन दान, और चाहें तो गुरुवार की प्रार्थना', 'padhna ya padhana, guruon ka sammaan, kitaabein ya bhojan daan, aur chahein to Guruvaar ki prarthana'],
  ['पढ़ना या पढ़ाना, किसी गुरु का धन्यवाद और किताबें दान', 'padhna ya padhana, kisi guru ka dhanyavaad aur kitaabein daan'],
  ['कला या संगीत, घर साफ़ और सुंदर रखना, साथी का सम्मान, और चाहें तो लक्ष्मी पूजा', 'kala ya sangeet, ghar saaf aur sundar rakhna, saathi ka sammaan, aur chahein to Lakshmi puja'],
  ['कला या संगीत, साफ़-सुथरा घर और साथी के प्रति नरमी', 'kala ya sangeet, saaf-suthra ghar aur saathi ke prati narmi'],
  ['कला या संगीत, घर और काम की जगह साफ़ और सुंदर रखना, साथ काम करने वालों से शालीन व्यवहार, और चाहें तो लक्ष्मी पूजा', 'kala ya sangeet, ghar aur kaam ki jagah saaf aur sundar rakhna, saath kaam karne walon se shaaleen vyavhaar, aur chahein to Lakshmi puja'],
  ['कला या संगीत, साफ़-सुथरी काम की जगह और साथ काम करने वालों से शालीन व्यवहार', 'kala ya sangeet, saaf-suthri kaam ki jagah aur saath kaam karne walon se shaaleen vyavhaar'],
  ['अनुशासन और समय की पाबंदी, बुज़ुर्गों या मज़दूरों की सेवा, और चाहें तो शनिवार को हनुमान चालीसा', 'anushasan aur samay ki paabandi, buzurgon ya mazdooron ki seva, aur chahein to Shanivaar ko Hanuman Chalisa'],
  ['नियमित दिनचर्या, समय की पाबंदी और बुज़ुर्गों या मज़दूरों की मदद में समय देना', 'niyamit dinacharya, samay ki paabandi aur buzurgon ya mazdooron ki madad mein samay dena'],
  ['स्क्रीन और नशे से दूरी, ईमानदारी, जानवरों की मदद, और चाहें तो दुर्गा की प्रार्थना', 'screen aur nashe se doori, imaandaari, jaanwaron ki madad, aur chahein to Durga ki prarthana'],
  ['कम स्क्रीन टाइम, ईमानदारी और जानवरों की मदद', 'kam screen time, imaandaari aur jaanwaron ki madad'],
  ['ध्यान, बेसहारा जानवरों की देखभाल, और चाहें तो गणेश वंदना', 'dhyaan, besahara jaanwaron ki dekhbhaal, aur chahein to Ganesh vandana'],
  ['कुछ मिनट शांत बैठना और बेसहारा जानवरों की देखभाल', 'kuch minute shaant baithna aur besahara jaanwaron ki dekhbhaal'],
  ['लव मैरिज', 'love marriage'],
  ['अरेंज मैरिज, जिसमें प्यार धीरे-धीरे बढ़ता है', 'arranged marriage, jismein pyaar dheere-dheere badhta hai'],
  ['परिवार की रज़ामंदी वाली लव मैरिज', 'parivaar ki razaamandi wali love marriage'],
  ['आपके प्रेम वाले और साझेदारी वाले पहलू को चलाने वाले ग्रह साथ काम करते हैं', 'aapke prem wale aur saajhedari wale pehlu ko chalane wale grah saath kaam karte hain'],
  ['प्रेम का ग्रह आपके रोमांस वाले पहलू के ग्रह के साथ है', 'prem ka grah aapke romance wale pehlu ke grah ke saath hai'],
  ['आपके साझेदारी वाले पहलू में अलग सोच की झलक है', 'aapke saajhedari wale pehlu mein alag soch ki jhalak hai'],
  ['आपका साझेदारी वाला पहलू परिवार, परंपरा और आशीर्वाद से जुड़ा है', 'aapka saajhedari wala pehlu parivaar, parampara aur aashirvaad se juda hai'],
  ['ज्ञान का ग्रह आपके साझेदारी वाले पहलू पर नज़र रखता है', 'gyaan ka grah aapke saajhedari wale pehlu par nazar rakhta hai'],
  ['कोई एक झुकाव हावी नहीं, इसलिए मुलाकात का तरीका खुला है', 'koi ek jhukaav haavi nahi, isliye mulaqat ka tareeka khula hai'],
  ['इन दोनों के अलावा, आपका चार्ट सबसे ज़्यादा इन क्षेत्रों का साथ देता है: {items}।', 'In dono ke alawa, aapka chart sabse zyada in kshetron ka saath deta hai: {items}.'],
  ['इन दोनों के अलावा, आपका चार्ट सबसे ज़्यादा इन विषयों का साथ देता है: {items}।', 'In dono ke alawa, aapka chart sabse zyada in vishayon ka saath deta hai: {items}.'],
  ['इन दोनों के अलावा, आपका चार्ट इस ओर इशारा करता है: {items}।', 'In dono ke alawa, aapka chart is or ishara karta hai: {items}.'],
  ['आपके चार्ट का सबसे साफ़ झुकाव इन क्षेत्रों की ओर है: {items}।', 'Aapke chart ka sabse saaf jhukaav in kshetron ki or hai: {items}.'],
  ['आपके लिए सबसे अच्छे क्षेत्र हैं: {items}।', 'Aapke liye sabse achhe kshetra hain: {items}.'],
  ['आपका चार्ट ऐसे जीवनसाथी की ओर इशारा करता है जो {items} हो।', 'Aapka chart aise jeevansaathi ki or ishara karta hai jo {items} ho.'],
  ['आपके लिए सही व्यक्ति शायद {items} होगा।', 'Aapke liye sahi vyakti shayad {items} hoga.'],
  ['आपकी कमाई के सबसे अच्छे स्रोत हैं: {items}।', 'Aapki kamaai ke sabse achhe srot hain: {items}.'],
  ['आपके लिए सबसे अच्छे विषय हैं: {items}।', 'Aapke liye sabse achhe vishay hain: {items}.'],
  ['पढ़ाई के लिए आपका चार्ट {items} का साथ देता है।', 'Padhai ke liye aapka chart {items} ka saath deta hai.'],
  ['आपकी सबसे बड़ी ताकतें हैं: {items}।', 'Aapki sabse badi taakatein hain: {items}.'],
  ['आपमें सबसे खास बात है: {items}।', 'Aapmein sabse khaas baat hai: {items}.'],
  ['आपका चार्ट कहता है कि {items} का ध्यान रखें।', 'Aapka chart kehta hai ki {items} ka dhyaan rakhein.'],
  ['आपके चार्ट का झुकाव है: {items}।', 'Aapke chart ka jhukaav hai: {items}.'],
  ['आपके चार्ट का रुझान है: {items}।', 'Aapke chart ka rujhaan hai: {items}.'],
  ['आपका चार्ट इस ओर झुकता है: {items}।', 'Aapka chart is or jhukta hai: {items}.'],
  ['आपके लिए बेहतर है: {items}।', 'Aapke liye behtar hai: {items}.'],
  ['{who} के साथ रिश्ते में है: {items}।', '{who} ke saath rishte mein hai: {items}.'],
  ['आपके रिश्तों में चार्ट दिखाता है: {items}। यह एक दौर है, अंत नहीं।', 'Aapke rishton mein chart dikhata hai: {items}. Yeh ek daur hai, ant nahi.'],
  ['आपके रिश्तों में बार-बार दिखता है: {items}।', 'Aapke rishton mein baar-baar dikhta hai: {items}.'],
  ['आपके चार्ट में आपकी राह यह दिखती है: {items}।', 'Aapke chart mein aapki raah yeh dikhti hai: {items}.'],
  ['आपके जीवन को अर्थ देने वाला विषय है: {items}।', 'Aapke jeevan ko arth dene wala vishay hai: {items}.'],
  ['आपके लिए सबसे सरल उपाय हैं: {items}।', 'Aapke liye sabse saral upaay hain: {items}.'],
  ['आपको सबसे ज़्यादा सहारा देता है: {items}।', 'Aapko sabse zyada sahara deta hai: {items}.'],
  ['आपके लिए ज़्यादा संभावित रास्ता है: {items}।', 'Aapke liye zyada sambhavit raasta hai: {items}.'],
  ['आप जो महसूस कर रहे हैं, वह आपके जीवन के मौजूदा चक्र से आता है: {items}।', 'Aap jo mehsoos kar rahe hain, woh aapke jeevan ke maujooda chakra se aata hai: {items}.'],
  ['अभी ऐसा क्यों लग रहा है, इसकी वजह है: {items}।', 'Abhi aisa kyun lag raha hai, iski wajah hai: {items}.'],
  ['इन भूमिकाओं पर ध्यान दें: {examples}।', 'In bhoomikaon par dhyaan dein: {examples}.'],
  ['ऐसा इसलिए है क्योंकि {reasons}।', 'Aisa isliye hai kyunki {reasons}.'],
  ['मुलाकात शायद {meet} होगी।', 'Mulaqat shayad {meet} hogi.'],
  ['जिस बात का ध्यान रखना है: {weak}।', 'Jis baat ka dhyaan rakhna hai: {weak}.'],
  ['आपके लिए सही जगह होगी: {place}।', 'Aapke liye sahi jagah hogi: {place}.'],
  ['रास्ता जो भी चुनें, आपके लिए सबसे अच्छा क्षेत्र है: {field}।', 'Raasta jo bhi chunein, aapke liye sabse achha kshetra hai: {field}.'],
  ['कदम बढ़ाने का अच्छा समय {start} से {end} तक है।', 'Kadam badhaane ka achha samay {start} se {end} tak hai.'],
  ['इन हुनरों को अपने बायोडाटा में सबसे ऊपर रखें और वहीं आवेदन करें जहाँ ये काम का मुख्य हिस्सा हों।', 'In hunaron ko apne biodata mein sabse upar rakhein aur wahin aavedan karein jahan ye kaam ka mukhya hissa hon.'],
  ['किसी तय तस्वीर के बजाय इन गुणों को देखें, और भरोसे को अपने समय पर बढ़ने दें।', 'Kisi tay tasveer ke bajaye in gunon ko dekhein, aur bharose ko apne samay par badhne dein.'],
  ['पहले इन्हीं पर ध्यान दें, हर महीने तय हिस्सा बचाएँ, और जोखिम वाले दाँव छोटे रखें।', 'Pehle inhi par dhyaan dein, har mahine tay hissa bachayein, aur jokhim wale daanv chhote rakhein.'],
  ['लंबी डिग्री से पहले इनमें से पहले विषय का एक छोटा कोर्स करके देखें।', 'Lambi degree se pehle inmein se pehle vishay ka ek chhota course karke dekhein.'],
  ['काम और रिश्तों में इन्हीं पर भरोसा करें, और ऐसे काम चुनें जिनमें ये रोज़ काम आएँ।', 'Kaam aur rishton mein inhi par bharosa karein, aur aise kaam chunein jinmein ye roz kaam aayein.'],
  ['बड़े बदलावों से ज़्यादा रोज़ की छोटी आदतें मायने रखती हैं।', 'Bade badlaavon se zyada roz ki chhoti aadatein maayne rakhti hain.'],
  ['पहले कुछ समय जाकर देखें, और फ़ैसला तब करें जब यह कदम आपके काम के लिए भी सही लगे।', 'Pehle kuch samay jaakar dekhein, aur faisla tab karein jab yeh kadam aapke kaam ke liye bhi sahi lage.'],
  ['बड़ा पैसा लगाने से पहले छोटे स्तर पर आज़माकर देखें।', 'Bada paisa lagane se pehle chhote star par aazma kar dekhein.'],
  ['छोटी शुरुआत करें और इसे रोज़ करें; अर्थ बड़े फ़ैसलों से ज़्यादा अभ्यास से आता है।', 'Chhoti shuruaat karein aur ise roz karein; arth bade faislon se zyada abhyaas se aata hai.'],
  ['परिवार से जल्दी और खुलकर बात करें; रास्ता जो भी हो, इससे मदद मिलती है।', 'Parivaar se jaldi aur khul kar baat karein; raasta jo bhi ho, isse madad milti hai.'],
  ['अभी की धीमी चाल नाकामी नहीं, तैयारी है; नियमित रहें और जो शुरू करें उसे पूरा करें।', 'Abhi ki dheemi chaal naakaami nahi, taiyari hai; niyamit rahein aur jo shuru karein use poora karein.'],
  ['कुल मिलाकर आपके लिए सहायक चक्र', 'kul milaakar aapke liye sahayak chakra'],
  ['ऐसा चक्र जो देता कम और मेहनत ज़्यादा माँगता है', 'aisa chakra jo deta kam aur mehnat zyada maangta hai'],
  ['अभी लंबा और छोटा चक्र अलग-अलग दिशाओं में खींचते हैं, इसलिए खिंचाव ज़्यादा है।', 'Abhi lamba aur chhota chakra alag-alag dishaon mein kheenchte hain, isliye khinchaav zyada hai.'],
  ['दोनों चक्र मिलकर खर्च और मेहनत बढ़ाते हैं।', 'Dono chakra milkar kharcha aur mehnat badhaate hain.'],
  ['{start} से शुरू होने वाला अगला छोटा चक्र {topic} से जुड़ा है, इसलिए तब रास्ते खुलते हैं।', '{start} se shuru hone wala agla chhota chakra {topic} se juda hai, isliye tab raaste khulte hain.'],
  ['अगला छोटा चक्र {start} में शुरू होता है और ध्यान फिर बदलता है।', 'Agla chhota chakra {start} mein shuru hota hai aur dhyaan phir badalta hai.'],
  ['आपका {P} का लंबा दौर, जो जीवन का ध्यान {area} पर रखता है', 'aapka {P} ka lamba daur, jo jeevan ka dhyaan {area} par rakhta hai'],
  ['{end} तक {P} का छोटा दौर, जिसका ध्यान {area} पर है', '{end} tak {P} ka chhota daur, jiska dhyaan {area} par hai'],
  ['आपकी चंद्र राशि पर शनि का गोचर, एक धीमा दौर जो धैर्य और अच्छी आदतों का फल देता है', 'aapki Chandra raashi par Shani ka gochar, ek dheema daur jo dhairya aur achhi aadaton ka phal deta hai'],
  ['शनि का ऐसा गोचर जो बदलाव लाता है और धैर्य माँगता है', 'Shani ka aisa gochar jo badlaav laata hai aur dhairya maangta hai'],
  ['घर और मन की शांति के मामले में शनि धैर्य माँगता है', 'ghar aur mann ki shaanti ke maamle mein Shani dhairya maangta hai'],
  ['आपकी चंद्र राशि पर शनि का गोचर, मन के लिए धीमा और परखने वाला समय, जो {end} के आसपास हल्का होगा', 'aapki Chandra raashi par Shani ka gochar, mann ke liye dheema aur parakhne wala samay, jo {end} ke aas-paas halka hoga'],
  ['शनि का भारी गोचर, अचानक बदलावों के साथ, जो {end} के आसपास हटेगा', 'Shani ka bhaari gochar, achanak badlaavon ke saath, jo {end} ke aas-paas hatega'],
  ['घर और मन की शांति पर शनि का दबाव, जो {end} के आसपास हटेगा', 'ghar aur mann ki shaanti par Shani ka dabaav, jo {end} ke aas-paas hatega'],
  ['यह चक्र {topic} को ज़्यादा सहारा नहीं देता, इसीलिए चीज़ें धीमी लगती हैं।', 'Yeh chakra {topic} ko zyada sahara nahi deta, isiliye cheezein dheemi lagti hain.'],
  ['यह चक्र {topic} का साथ देता है, इसलिए अभी की लगातार मेहनत नींव बनाती है।', 'Yeh chakra {topic} ka saath deta hai, isliye abhi ki lagaataar mehnat neenv banati hai.'],
  ['आपके करियर', 'aapke career'],
  ['व्यापार', 'vyapar'],
  ['धन', 'dhan'],
  ['शादी', 'shaadi'],
  ['सेहत', 'sehat'],
  ['घर और संपत्ति', 'ghar aur sampatti'],
  ['परिवार बढ़ने', 'parivaar badhne'],
  ['विदेश जाने', 'videsh jaane'],
  ['कानूनी मामलों', 'kaanooni maamlon'],
  ['आपकी योजनाओं', 'aapki yojanaon'],
  ['साफ़ कहूँ तो आपकी सबसे मज़बूत दिशा है: {item}।', 'Saaf kahoon to aapki sabse mazboot disha hai: {item}.'],
  ['आपके चार्ट में साथी के ये गुण दिखते हैं: {item}।', 'Aapke chart mein saathi ke ye gun dikhte hain: {item}.'],
  ['जैसा बताया, आपका पैसा सबसे सहज रूप से {item} से आता है।', 'Jaisa bataya, aapka paisa sabse sahaj roop se {item} se aata hai.'],
  ['जैसा बताया, आपकी सबसे बड़ी ताकत है: {item}।', 'Jaisa bataya, aapki sabse badi taakat hai: {item}.'],
  ['उनमें ये गुण भी हो सकते हैं: {item}, क्योंकि {why}।', 'Unmein ye gun bhi ho sakte hain: {item}, kyunki {why}.'],
  ['एक और ताकत है {item}, क्योंकि {why}।', 'Ek aur taakat hai {item}, kyunki {why}.'],
  ['इन पर भी नज़र डालें: {examples}।', 'In par bhi nazar daalein: {examples}.'],
  ['इनमें से एक भूमिका चुनें, अगले एक महीने में उसका मुख्य हुनर सीखें और किसी छोटे प्रोजेक्ट में दिखाएँ।', 'Inmein se ek bhoomika chunein, agle ek mahine mein uska mukhya hunar seekhein aur kisi chhote project mein dikhayein.'],
  ['देखें कि ये गुण रोज़ के व्यवहार में किसमें दिखते हैं, सिर्फ़ पहली मुलाकात में नहीं।', 'Dekhein ki ye gun roz ke vyavhaar mein kismein dikhte hain, sirf pehli mulaqat mein nahi.'],
  ['इनमें से पहले वाले से कमाई का एक छोटा ज़रिया शुरू करें, और हर फ़ायदे का कुछ हिस्सा बचाएँ।', 'Inmein se pehle wale se kamaai ka ek chhota zariya shuru karein, aur har fayde ka kuch hissa bachayein.'],
  ['चुनने से पहले इन क्षेत्रों में काम कर रहे दो लोगों से बात करें।', 'Chunne se pehle in kshetron mein kaam kar rahe do logon se baat karein.'],
  ['किसी दोस्त से पूछें कि उन्हें ये बातें आपमें कहाँ दिखती हैं, और इस हफ़्ते इन्हें सोच-समझकर काम में लाएँ।', 'Kisi dost se poochhein ki unhe ye baatein aapmein kahan dikhti hain, aur is hafte inhe soch-samajh kar kaam mein laayein.'],
  ['एक आदत चुनें और दूसरी जोड़ने से पहले तीन हफ़्ते तक उसे निभाएँ।', 'Ek aadat chunein aur doosri jodne se pehle teen hafte tak use nibhayein.'],
  ['फ़ैसले से पहले वहाँ मिलने वाले काम की तुलना अभी के काम से करें।', 'Faisle se pehle wahan milne wale kaam ki tulna abhi ke kaam se karein.'],
  ['आइडिया आज़माते समय स्थिर आमदनी बनाए रखें, और उसे तभी बढ़ाएँ जब वह अपना खर्च खुद निकालने लगे।', 'Idea aazmaate samay sthir aamdani banaye rakhein, aur use tabhi badhayein jab woh apna kharcha khud nikaalne lage.'],
  ['इस हफ़्ते उनके लिए एक काम चुनें, उनके पहल करने का इंतज़ार किए बिना।', 'Is hafte unke liye ek kaam chunein, unke pehal karne ka intezaar kiye bina.'],
  ['दोनों अपनी सबसे बड़ी ज़रूरत लिखें, और एक बार में एक बात पर बात करें।', 'Dono apni sabse badi zaroorat likhein, aur ek baar mein ek baat par baat karein.'],
  ['लिखते रहें कि किस बात से दिन सार्थक लगा; उसी में आपकी राह दिखेगी।', 'Likhte rahein ki kis baat se din saarthak laga; usi mein aapki raah dikhegi.'],
  ['एक अभ्यास चुनें और दूसरा जोड़ने से पहले उसे चालीस दिन निभाएँ।', 'Ek abhyaas chunein aur doosra jodne se pehle use chaalees din nibhayein.'],
  ['उस व्यक्ति को जल्दी परिवार से मिलवाएँ, ताकि दोनों तरफ़ भरोसा बने।', 'Us vyakti ko jaldi parivaar se milwayein, taaki dono taraf bharosa bane.'],
  ['इस समय में हुनर और बचत बढ़ाएँ; अगला चक्र अभी की तैयारी का फल देता है।', 'Is samay mein hunar aur bachat badhayein; agla chakra abhi ki taiyari ka phal deta hai.'],
  ['एक और अच्छा विकल्प है {item}, क्योंकि {why}।', 'Ek aur achha vikalp hai {item}, kyunki {why}.'],
  ['चाहें तो इनमें से किसी एक के बारे में विस्तार से, या समय के बारे में पूछिए।', 'Chahein to inmein se kisi ek ke baare mein vistaar se, ya samay ke baare mein poochhiye.'],
  ['अब तक की बातों में, अगला आज़माने लायक विकल्प है: {item}।', 'Ab tak ki baaton mein, agla aazmaane laayak vikalp hai: {item}.'],
  ['कर्ज़ से छुटकारे', 'karz se chhutkaare'],
  ['पैसा वापस मिलने', 'paisa wapas milne'],
  ['लोन मंज़ूर होने', 'loan manzoor hone'],
  ['गाड़ी लेने', 'gaadi lene'],
  ['रिश्ते में सुधार', 'rishte mein sudhaar'],
  ['शिक्षा', 'shiksha'],
  ['पढ़ाई', 'padhai'],
  ['प्रेम', 'prem'],
  ['संतान', 'santaan'],
  ['उनकी', 'unki'],
  ['प्रेम जीवन', 'prem jeevan'],
  ['नई नौकरी', 'nayi naukri'],
  ['करियर में तरक्की', 'career mein tarakki'],
  ['घर या संपत्ति', 'ghar ya property'],
  ['सेहत में सुधार', 'sehat mein sudhaar'],
  ['भाग्य', 'bhagya'],
  ['उस समय रिश्तों की बात आगे बढ़ाएँ और परिवार व दोस्तों को बताएँ कि आप तैयार हैं।', 'Us samay rishton ki baat aage badhayein aur parivaar aur doston ko batayein ki aap taiyaar hain.'],
  ['उस समय लोगों से मिलें-जुलें और दिल खुला रखें।', 'Us samay logon se milein-julein aur dil khula rakhein.'],
  ['उससे पहले के महीनों में अपना बायोडाटा तैयार करें, हुनर बढ़ाएँ और आवेदन भेजते रहें।', 'Usse pehle ke mahinon mein apna biodata taiyaar karein, hunar badhayein aur aavedan bhejte rahein.'],
  ['उससे पहले अपना काम सबके सामने रखें, और समय आने पर साफ़ तौर पर तरक्की की बात करें।', 'Usse pehle apna kaam sabke saamne rakhein, aur samay aane par saaf taur par tarakki ki baat karein.'],
  ['उससे पहले योजना बनाएँ और बचत करें, और शुरुआत या विस्तार उसी समय करें।', 'Usse pehle yojana banayein aur bachat karein, aur shuruaat ya vistaar usi samay karein.'],
  ['तब तक नियमित बचत करें और जोखिम भरे दाँव से बचें; उस समय फ़ायदा आसानी से मिलता है।', 'Tab tak niyamit bachat karein aur jokhim bhare daanv se bachein; us samay fayda aasaani se milta hai.'],
  ['उससे पहले जगह देख लें और पैसों का इंतज़ाम कर लें, ताकि उसी समय सौदा पक्का कर सकें।', 'Usse pehle jagah dekh lein aur paison ka intezaam kar lein, taaki usi samay sauda pakka kar sakein.'],
  ['उससे पहले दोनों अपनी सेहत का ध्यान रखें, और चिकित्सा से जुड़ी हर बात डॉक्टर से पूछें।', 'Usse pehle dono apni sehat ka dhyaan rakhein, aur ilaaj se judi har baat doctor se poochhein.'],
  ['उससे पहले रोज़ थोड़ा-थोड़ा पढ़ना उस समय सबसे ज़्यादा काम आएगा।', 'Usse pehle roz thoda-thoda padhna us samay sabse zyada kaam aayega.'],
  ['उससे पहले कागज़ात, बचत और आवेदन तैयार रखें।', 'Usse pehle kaagzaat, bachat aur aavedan taiyaar rakhein.'],
  ['तब तक नियमित नींद, भोजन और व्यायाम सबसे ज़्यादा मदद करते हैं।', 'Tab tak niyamit neend, bhojan aur vyayaam sabse zyada madad karte hain.'],
  ['अपने कागज़ात ठीक रखें और वकील की सलाह मानें; हो सके तो ज़रूरी कदम उसी समय उठाएँ।', 'Apne kaagzaat theek rakhein aur vakeel ki salah maanein; ho sake to zaroori kadam usi samay uthayein.'],
  ['जो काम आपके लिए सबसे ज़रूरी हैं, उन्हें उसी समय शुरू करें।', 'Jo kaam aapke liye sabse zaroori hain, unhe usi samay shuru karein.'],
  ['व्यक्तित्व', 'vyaktitva'],
  ['धन और परिवार', 'dhan aur parivaar'],
  ['मेहनत और हुनर', 'mehnat aur hunar'],
  ['घर-परिवार', 'ghar-parivaar'],
  ['रचनात्मकता और पढ़ाई', 'rachnatmakta aur padhai'],
  ['रोज़ के काम और सेहत', 'roz ke kaam aur sehat'],
  ['साझेदारी', 'saajhedari'],
  ['बदलाव', 'badlaav'],
  ['भाग्य और ज्ञान', 'bhagya aur gyaan'],
  ['करियर', 'career'],
  ['लाभ और दोस्तों', 'laabh aur doston'],
  ['विदेश और खर्च', 'videsh aur kharch'],
  ['रविवार', 'Sunday'],
  ['सोमवार', 'Monday'],
  ['मंगलवार', 'Tuesday'],
  ['बुधवार', 'Wednesday'],
  ['गुरुवार', 'Thursday'],
  ['शुक्रवार', 'Friday'],
  ['शनिवार', 'Saturday'],
  ['गुरु', 'Guru'],
  ['{a}, और साथ ही {b}', '{a}, aur saath hi {b}'],
  ['{a} और {b}', '{a} aur {b}'],
  ['और {x}', 'aur {x}'],
  ['{a}, {b}', '{a}, {b}'],
  ['{a} या {b}', '{a} ya {b}'],
  ['{a}, {b} ({c})', '{a}, {b} ({c})'],
  ['{a}; {b}', '{a}; {b}'],
  ['{p} की अंतर्दशा {s} से {e} तक चली, और शनि आपकी चंद्र राशि पर दबाव डाल रहा था', '{p} ki antardasha {s} se {e} tak chali, aur Shani aapki Chandra raashi par dabaav daal raha tha'],
  ['{p} की अंतर्दशा {s} से {e} तक चली', '{p} ki antardasha {s} se {e} tak chali'],
  ['नमस्ते! मैं सागा हूँ। अपनी कुंडली के बारे में कुछ भी पूछिए — प्यार, काम, पैसा, परिवार, या आने वाले महीने कैसे रहेंगे।', 'Namaste! Main Saga hoon. Apni kundli ke baare mein kuch bhi poochhiye — pyaar, kaam, paisa, parivaar, ya aane wale mahine kaise rahenge.'],
  ['नमस्ते! मैं सागा हूँ। {name} की कुंडली के बारे में कुछ भी पूछिए — प्यार, काम, पैसा, परिवार, या आने वाले महीने कैसे रहेंगे।', 'Namaste! Main Saga hoon. {name} ki kundli ke baare mein kuch bhi poochhiye — pyaar, kaam, paisa, parivaar, ya aane wale mahine kaise rahenge.'],
  ['मुझे सच में अच्छा लगा कि आपने मुझे बताया। आपको यह अकेले नहीं सहना है। कृपया अभी किसी से बात करें: टेली-मानस को 14416 (या 1-800-891-4416) पर कॉल करें। यह मुफ़्त है, 24×7 खुला है और आप अपनी भाषा में बात कर सकते हैं। अगर आप ख़तरे में हैं या इन विचारों पर कुछ कर बैठ सकते हैं, तो अभी 112 पर कॉल करें। हो सके तो किसी भरोसेमंद व्यक्ति को बताएँ और उनके साथ रहें।', 'Mujhe sach mein achha laga ki aapne mujhe bataya. Aapko yeh akele nahi sehna hai. Kripya abhi kisi se baat karein: Tele-MANAS ko 14416 (ya 1-800-891-4416) par call karein. Yeh muft hai, 24×7 khula hai aur aap apni bhasha mein baat kar sakte hain. Agar aap khatre mein hain ya in vichaaron par kuch kar baith sakte hain, to abhi 112 par call karein. Ho sake to kisi bharosemand vyakti ko batayein aur unke saath rahein.'],
  ['इसके लिए डॉक्टर से ज़रूर मिलें।', 'Iske liye doctor se zaroor milein.'],
  ['इस मामले में किसी वकील से ज़रूर सलाह लें।', 'Is maamle mein kisi vakeel se zaroor salah lein.'],
  ['बच्चा बेटा होगा या बेटी, यह कोई कुंडली नहीं बता सकती, और भारत में जन्म से पहले बच्चे का लिंग जानना क़ानूनन मना है। हर बच्चा एक आशीर्वाद है। चाहें तो पूछिए कि आने वाले महीने आपके परिवार और घर के लिए कैसे रहेंगे।', 'Bachcha beta hoga ya beti, yeh koi kundli nahi bata sakti, aur Bharat mein janam se pehle bachche ka ling jaanna kaanoonan mana hai. Har bachcha ek aashirvaad hai. Chahein to poochhiye ki aane wale mahine aapke parivaar aur ghar ke liye kaise rahenge.'],
  ['कुंडली से किसी का नाम या नाम का पहला अक्षर पता नहीं चलता, इसलिए उसका अंदाज़ा लगाना ठीक नहीं। हाँ, यह ज़रूर देखा जा सकता है कि प्यार और शादी का समय कब बेहतर है और कैसा साथी आपके लिए सही रहेगा। इनमें से कुछ भी पूछिए।', 'Kundli se kisi ka naam ya naam ka pehla akshar pata nahi chalta, isliye uska andaaza lagana theek nahi. Haan, yeh zaroor dekha ja sakta hai ki pyaar aur shaadi ka samay kab behtar hai aur kaisa saathi aapke liye sahi rahega. Inmein se kuch bhi poochhiye.'],
  ['माफ़ कीजिए अगर बात साफ़ नहीं थी; सीधे शब्दों में कहूँ तो: {x}', 'Maaf kijiye agar baat saaf nahi thi; seedhe shabdon mein kahoon to: {x}'],
  ['मुझे दुख है कि उनकी तबीयत ठीक नहीं है।', 'Mujhe dukh hai ki unki tabiyat theek nahi hai.'],
  ['कुंडली से इलाज का नतीजा नहीं बताया जा सकता; यह उनका इलाज कर रहे डॉक्टर ही बता सकते हैं।', 'Kundli se ilaaj ka nateeja nahi bataya ja sakta; yeh unka ilaaj kar rahe doctor hi bata sakte hain.'],
  ['क्या यह आपके अनुभव से मेल खाता है? अगर हाँ, तो इससे यह पढ़ाई और पक्की होती है।', 'Kya yeh aapke anubhav se mel khata hai? Agar haan, to isse yeh reading aur pakki hoti hai.'],
  ['जिस काम की ओर बढ़ना है उसका एक ज़रूरी हुनर चुनें, अगले एक महीने में सीखें और किसी छोटे प्रोजेक्ट में दिखाएँ।', 'Jis kaam ki or badhna hai uska ek zaroori hunar chunein, agle ek mahine mein seekhein aur kisi chhote project mein dikhayein.'],
  ['{year} में सबसे मज़बूत समय {a1} के लिए दिखता है: इसका सबसे अच्छा दौर इसी साल में आता है।', '{year} mein sabse mazboot samay {a1} ke liye dikhta hai: iska sabse achha daur isi saal mein aata hai.'],
  ['हर महीने तय हिस्सा बचाएँ और कमज़ोर महीनों में बड़े दाँव से बचें।', 'Har mahine tay hissa bachayein aur kamzor mahinon mein bade daanv se bachein.'],
  ['बड़े आर्थिक फ़ैसले से पहले किसी वित्तीय सलाहकार से बात करें।', 'Bade aarthik faisle se pehle kisi financial adviser se baat karein.'],
  ['जन्म समय के बिना मैं चंद्र राशि से घर गिनता हूँ; फिर भी काम की तस्वीर मिलती है, बस समय अनुमानित है।', 'Janam samay ke bina main Chandra raashi se ghar ginta hoon; phir bhi kaam ki tasveer milti hai, bas samay anumaanit hai.'],
  ['जन्म का समय मिल जाए तो उसे प्रोफ़ाइल में जोड़ें, जवाब और सटीक होंगे।', 'Janm ka samay mil jaye to use profile mein jodein, jawab aur sateek honge.'],
  ['जन्म समय मिल जाए तो उसे प्रोफ़ाइल में जोड़ें, जवाब और सटीक होंगे।', 'Janm samay mil jaye to use profile mein jodein, jawab aur sateek honge.'],
  ['उस सहायक समय में बात आगे बढ़ाने से अच्छी उम्मीद है।', 'Us sahayak samay mein baat aage badhane se achhi ummeed hai.'],
  ['यह हल्का दौर है, बहुत मज़बूत नहीं, इसलिए छोटे और नियमित कदम मायने रखते हैं।', 'Yeh halka daur hai, bahut mazboot nahi, isliye chhote aur niyamit kadam mayne rakhte hain.'],
  ['इसका एक और हिस्सा: {x}।', 'Iska ek aur hissa: {x}.'],
  ['यहाँ भी आपका {P} वाला दौर काम करता है, और इस बार {link}।', 'Yahan bhi aapka {P} wala daur kaam karta hai, aur is baar {link}.'],
  ['आपके चार्ट में यह दौर है: {x}।', 'Aapke chart mein yeh daur hai: {x}.'],
  ['अगर {a} और {b} में से एक चुनना हो, तो थोड़े अंतर से {pick}: {why}।', 'Agar {a} aur {b} mein se ek chunna ho, to thode antar se {pick}: {why}.'],
  ['यह भी आपके {P} वाले दौर में आता है, उसी वजह से।', 'Yeh bhi aapke {P} wale daur mein aata hai, usi wajah se.'],
  ['कोई एक काम चुनें जो आप लंबे समय से करना चाहते थे, और उसे हर हफ़्ते एक तय समय दें।', 'Koi ek kaam chunein jo aap lambe samay se karna chahte the, aur use har hafte ek tay samay dein.'],
];
