/** Generated from the romanization sheets (scratchpad roman/gen.py); hand-written Latin forms of the agent's table sentences. */
export const BN_ITEMS: readonly (readonly [string, string])[] = [
  ['{who}{areaGen} জন্য সবচেয়ে ভালো সময় {start} থেকে {end}, বিশেষ করে {peak} নাগাদ।', '{who}{areaGen} jonno sobcheye bhalo somoy {start} theke {end}, bishesh kore {peak} nagad.'],
  ['{who}পরিস্থিতি সবচেয়ে ভালো হয় {start} থেকে {end}, বিশেষ করে {peak} নাগাদ।', '{who}Poristhiti sobcheye bhalo hoy {start} theke {end}, bishesh kore {peak} nagad.'],
  ['{who}{areaGen} জন্য সবচেয়ে ভালো সময় {start} থেকে {end}, আর সবচেয়ে সম্ভাব্য মাস {peak}।', '{who}{areaGen} jonno sobcheye bhalo somoy {start} theke {end}, ar sobcheye sombhabbo mash {peak}.'],
  ['{nameGen} {areaGen} জন্য সবচেয়ে ভালো সময় {start} থেকে {end}, বিশেষ করে {peak} নাগাদ।', '{nameGen} {areaGen} jonno sobcheye bhalo somoy {start} theke {end}, bishesh kore {peak} nagad.'],
  ['এই সময়টা পড়ে আপনার জীবনের {P}-এর পর্বে, আর {link}।', 'Ei somoyta pore apnar jiboner {P}-er porbe, ar {link}.'],
  ['এই সময়টা পড়ে আপনার জীবনের {P}-এর পর্বে, যা আপনার চার্টে {areaGen} সঙ্গে যুক্ত।', 'Ei somoyta pore apnar jiboner {P}-er porbe, ja apnar charte {areaGen} sathe jukto.'],
  ['ওই সময়টা ছিল আপনার জীবনের {P}-এর পর্বে, আর {link}।', 'Oi somoyta chhilo apnar jiboner {P}-er porbe, ar {link}.'],
  ['ওই সময়টা ছিল আপনার জীবনের {P}-এর পর্বে, যা আপনার চার্টে {areaGen} সঙ্গে যুক্ত।', 'Oi somoyta chhilo apnar jiboner {P}-er porbe, ja apnar charte {areaGen} sathe jukto.'],
  ['তখন বৃহস্পতি আর শনি দুজনেরই সমর্থন থাকে।', 'Tokhon Brihoshpoti ar Shoni dujoneri somorthon thake.'],
  ['তখন বৃহস্পতির সমর্থনও থাকে।', 'Tokhon Brihoshpotir somorthon-o thake.'],
  ['এই সময়টা স্থির, খুব জোরালো নয়; আরও জোরালো সময় {start} থেকে {end}।', 'Ei somoyta sthir, khub joralo noy; aro joralo somoy {start} theke {end}.'],
  ['এই সময়টা স্থির, খুব জোরালো নয়; আরও জোরালো সময় আসে {start} নাগাদ।', 'Ei somoyta sthir, khub joralo noy; aro joralo somoy ase {start} nagad.'],
  ['সময়টা খুব জোরালো নয়, তবে স্থির, তাই চেষ্টাটাই আসল।', 'Somoyta khub joralo noy, tobe sthir, tai cheshtatai asol.'],
  ['তার আগে {start} থেকে {end} একটা ছোট সুযোগও আছে।', 'Tar age {start} theke {end} ekta chhoto shujog-o ache.'],
  ['তার পরের ভালো সময় {start} থেকে {end}।', 'Tar porer bhalo somoy {start} theke {end}.'],
  ['হ্যাঁ, সামনের মাসগুলোয় এর ভালো সমর্থন আছে।', 'Hyan, samner mashgulote er bhalo somorthon ache.'],
  ['সামনের কয়েক মাসে এর জোর কম; ভালো সময় আসে একটু পরে।', 'Samner koek mashe er jor kom; bhalo somoy ase ektu pore.'],
  ['এই বছর নয়; আরও জোরালো সময় আসে পরে।', 'Ei bochhor noy; aro joralo somoy ase pore.'],
  ['হ্যাঁ, সামনের মাসগুলোয় এর স্থির সমর্থন আছে, যদিও খুব জোরালো নয়।', 'Hyan, samner mashgulote er sthir somorthon ache, jodio khub joralo noy.'],
  ['জন্মসময় ছাড়া এই তারিখগুলো আনুমানিক; সেটা যোগ করলে আরও নিখুঁত হবে।', 'Jonmo somoy chhara ei tarikhgulo anumanik; seta jog korle aro nikhut hobe.'],
  ['তার আগের মাসগুলো {nameGen} প্রস্তুতির জন্য ভালো।', 'Tar ager mashgulo {nameGen} prostutir jonno bhalo.'],
  ['কুষ্ঠি দিয়ে দুর্ঘটনা বলা যায় না, আর আমি তা আন্দাজও করব না। সাধারণ সাবধানতাই সবচেয়ে ভালো সুরক্ষা; চাইলে সামনের বছর নিয়ে জিজ্ঞেস করুন।', 'Kushti diye durghotona bola jay na, ar ami ta andajo korbo na. Sadharon sabdhanotai sobcheye bhalo surokkha; chaile samner bochhor niye jiggesh korun.'],
  ['কোনো গ্রহের হিসেবই বলতে পারে না কেউ কতদিন বাঁচবেন, আর আমি আন্দাজও করব না।', 'Kono grohor hisebi bolte pare na keu kotodin banchben, ar ami andajo korbo na.'],
  ['{who}পিছনে তাকালে, {areaGen} জন্য সবচেয়ে জোরালো সময় ছিল {start} থেকে {end}।', '{who}Pichhone takale, {areaGen} jonno sobcheye joralo somoy chhilo {start} theke {end}.'],
  ['এর জন্য সবচেয়ে ভালো সময় {start} থেকে {end}, বিশেষ করে {peak} নাগাদ।', 'Er jonno sobcheye bhalo somoy {start} theke {end}, bishesh kore {peak} nagad.'],
  ['{start} থেকে {end}-এর মধ্যে সবচেয়ে সম্ভাব্য মাস {peak}।', '{start} theke {end}-er moddhe sobcheye sombhabbo mash {peak}.'],
  ['পিছনে তাকালে, এর জন্য সবচেয়ে জোরালো সময় ছিল {start} থেকে {end}।', 'Pichhone takale, er jonno sobcheye joralo somoy chhilo {start} theke {end}.'],
  ['{name}-এর ক্ষেত্রে:', '{name}-er khetre:'],
  ['তখন জীবনের সেই পর্ব চলবে, যা {areaGen} সঙ্গে জড়িত।', 'Tokhon jiboner sei porbo cholbe, ja {areaGen} sathe jorito.'],
  ['ঠিক তখনই দুই বড়, ধীর গতির গ্রহ একসঙ্গে এর পাশে থাকে, যা কাজ এগোনোর পুরনো লক্ষণ।', 'Thik tokhoni dui boro, dhir gotir groho ekshathe er pashe thake, ja kaj egonor puronon lokkhon.'],
  ['তখন বৃদ্ধির গ্রহও এর পাশে থাকে।', 'Tokhon briddhir groho-o er pashe thake.'],
  ['চার্টে {areaGen} জন্য ভালো সমর্থন দেখা যায়।', 'Charte {areaGen} jonno bhalo somorthon dekha jay.'],
  ['চার্টে {area} তাড়াহুড়ো করে নয়, ধৈর্যের সঙ্গে আসে বলে দেখা যায়।', 'Charte {area} taratari kore noy, dhoirjer sathe ase bole dekha jay.'],
  ['সামনের পাঁচ বছরে খুব জোরালো কোনো সময় দেখা যাচ্ছে না, তাই শান্ত সময়গুলোর মধ্যে এটাই সবচেয়ে ভালো।', 'Samner pach bochhore khub joralo kono somoy dekha jachhe na, tai shanto somoygulor moddhe etai sobcheye bhalo.'],
  ['আরও জোরালো সময় আসে {start} নাগাদ।', 'Aro joralo somoy ase {start} nagad.'],
  ['সেটা এখনও কিছুটা দূরে; তার আগের বছরগুলো প্রস্তুতির জন্য ভালো।', 'Seta ekhono kichhuta dure; tar ager bochhorgulo prostutir jonno bhalo.'],
  ['সেই সময় পেরিয়ে গেলে, পরের ভালো সময় {start} থেকে {end}।', 'Sei somoy periye gele, porer bhalo somoy {start} theke {end}.'],
  ['জন্মের সময় দেওয়া নেই, তাই এই তারিখগুলো আনুমানিক। আরও নিখুঁত উত্তরের জন্য প্রোফাইলে জন্মের সময় যোগ করুন।', 'Jonmer somoy deoa nei, tai ei tarikhgulo anumanik. Aro nikhut uttorer jonno profile-e jonmer somoy jog korun.'],
  ['জন্মস্থান দেওয়া নেই, তাই এই তারিখগুলো আনুমানিক।', 'Jonmosthan deoa nei, tai ei tarikhgulo anumanik.'],
  ['গ্রহের হিসেবে মাস আর সময়ের পরিসর বলা যায়, নির্দিষ্ট একটা দিন নয়।', 'Grohor hishebe mash ar somoyer porisor bola jay, nirdishto ekta din noy.'],
  ['{age} বছর বয়সে বিয়ে বা প্রেমের চেয়ে পড়াশোনা, বন্ধু আর পরিবারের দিকে মন দেওয়ার সময়।', '{age} bochhor boyoshe biye ba premer cheye porashona, bondhu ar paribarer dike mon deoar somoy.'],
  ['এই বয়সে সন্তান জন্মের সময় আমি বলি না। বরং পরিবারের আনন্দ আর সংসারের সামনের বছরগুলো নিয়ে জিজ্ঞেস করুন।', 'Ei boyoshe santan jonmer somoy ami boli na. Borong paribarer anondo ar shongsharer samner bochhorgulo niye jiggesh korun.'],
  ['কোনো গ্রহের হিসেবই বলতে পারে না কেউ কতদিন বাঁচবেন, আর আমি আন্দাজও করব না। স্বাস্থ্য বা ভবিষ্যৎ নিয়ে দুশ্চিন্তা থাকলে সামনের বছরগুলো নিয়ে জিজ্ঞেস করুন, আর শরীরের ব্যাপারে অবশ্যই ডাক্তার দেখান।', 'Kono grohor hisebi bolte pare na keu kotodin banchben, ar ami andajo korbo na. Shasthyo ba bhobishyot niye dushchinta thakle samner bochhorgulo niye jiggesh korun, ar shorirer byapare oboshyoi daktar dekhan.'],
  ['এর উত্তর দিতে ওঁর নিজের জন্মের তথ্য লাগবে। ওঁকে প্রোফাইলে যোগ করে ওঁর চ্যাটে জিজ্ঞেস করুন। এখানে যে চার্ট খোলা আছে সেটা {owner}।', 'Er uttor dite onar nijer jonmer tottho lagbe. Onake profile-e jog kore onar chat-e jiggesh korun. Ekhane je chart khola ache seta {owner}.'],
  ['আপনার', 'apnar'],
  ['{name}-এর', '{name}-er'],
  ['আমি তোমার পাশে আছি। এই শ্লোকটির সঙ্গে একটু থামো; তোমার মনের কথাটির সঙ্গেই এটা জড়িয়ে আছে।', 'Ami tomar pashe achhi. Ei shloktir sathe ektu thamo; tomar moner kothatir sathei eta joriye ache.'],
  ['জীবনের যেকোনো বিষয়ে "কবে" জিজ্ঞেস করুন, আমি চার্টে সবচেয়ে ভালো সময় খুঁজে দেব।', 'Jiboner jekono bishoye "kobe" jiggesh korun, ami charte sobcheye bhalo somoy khunje debo.'],
  ['বুঝতে পারছি, সময়টা সহজ যাচ্ছে না।', 'Bujhte parchhi, somoyta sohoj jachhe na.'],
  ['বুঝতে পারছি, এতদিনের অপেক্ষা সহজ নয়।', 'Bujhte parchhi, etodiner opekkha sohoj noy.'],
  ['চার্টে এর জোরালো সম্ভাবনা দেখা যায়, যদিও কিছুই নিশ্চিত নয়।', 'Charte er joralo sombhabona dekha jay, jodio kichhui nishchit noy.'],
  ['চার্টে এর ভালো সম্ভাবনা আছে, আর টানা চেষ্টায় তা আরও বাড়ে।', 'Charte er bhalo sombhabona ache, ar tana cheshtay ta aro bare.'],
  ['আপনার চার্টে এটা তাড়াতাড়ি নয়, ধীরে ধীরে হতে দেখা যায়, তাই এখানে টানা চেষ্টাই বেশি কাজে দেবে।', 'Apnar charte eta taratari noy, dhire dhire hote dekha jay, tai ekhane tana cheshtai beshi kaje debe.'],
  ['ওঁর ডাক্তারদের সঙ্গে যোগাযোগ রাখুন, আর নিজের ঘুম ও বিশ্রামের দিকেও খেয়াল রাখুন।', 'Onar daktarder sathe jogajog rakhun, ar nijer ghum o bishramer dikeo kheyal rakhun.'],
  ['আপনার চার্টে মামলার জন্য সহায়ক সময় দেখা যায়, যদিও রায় নির্ভর করে তথ্য আর আপনার উকিলের প্রস্তুতির ওপর।', 'Apnar charte mamlar jonno sohayok somoy dekha jay, jodio ray nirbhor kore tottho ar apnar ukiler prostutir opor.'],
  ['আপনার চার্টে মামলার জন্য মোটামুটি সমর্থন দেখা যায়; সবচেয়ে জরুরি তথ্য আর একজন ভালো উকিল।', 'Apnar charte mamlar jonno motamuti somorthon dekha jay; sobcheye joruri tottho ar ekjon bhalo ukil.'],
  ['আপনার চার্টে মামলার জন্য ধীর সময় দেখা যায়, তাই ধৈর্য আর একজন ভালো উকিলই সবচেয়ে জরুরি।', 'Apnar charte mamlar jonno dhir somoy dekha jay, tai dhoirjo ar ekjon bhalo ukil-i sobcheye joruri.'],
  ['হ্যাঁ, {option} আপনার চার্টের সবচেয়ে মানানসই বিষয়গুলোর মধ্যে পড়ে।', 'Hyan, {option} apnar charter sobcheye mananshoi bishoygulor moddhe pore.'],
  ['{option} আপনার জন্য চলতে পারে, যদিও এটা আপনার চার্টের প্রথম পছন্দ নয়।', '{option} apnar jonno cholte pare, jodio eta apnar charter prothom pochhondo noy.'],
  ['{option} আপনার চার্টের জোরালো বিষয়গুলোর মধ্যে নেই; অন্য বিষয়গুলো এগিয়ে।', '{option} apnar charter joralo bishoygulor moddhe nei; onno bishoygulo egiye.'],
  ['সবচেয়ে সহায়ক সময় {start} থেকে {end}।', 'Sobcheye sohayok somoy {start} theke {end}.'],
  ['আসলে এটা দূরে নয়: ভালো সময় শুরু হচ্ছে {start}-এ, তাই এখন থেকেই প্রস্তুতি শুরু করুন।', 'Asole eta dure noy: bhalo somoy shuru hochhe {start}-e, tai ekhon thekei prostuti shuru korun.'],
  ['শেষ সিদ্ধান্ত নির্ভর করে আপনার কাগজপত্র আর নিয়মের ওপর, তাই কাগজপত্র সম্পূর্ণ আর ঠিকঠাক রাখুন।', 'Shesh siddhanto nirbhor kore apnar kagojpotro ar niyomer opor, tai kagojpotro sompurno ar thikthak rakhun.'],
  ['অনুগ্রহ করে একজন উকিলকে পাশে রাখুন; প্রতিটি আইনি পদক্ষেপে তিনিই পথ দেখাবেন।', 'Onugroho kore ekjon ukilke pashe rakhun; protiti aini podokkhepe tinii poth dekhaben.'],
  ['একজন কাউন্সেলর বা বিশ্বস্ত কারও সঙ্গে খোলাখুলি কথা বললে সত্যিই সাহায্য হয়।', 'Ekjon counsellor ba bishshosto karo sathe kholakhuli kotha bolle sotyii sahajjo hoy.'],
  ['কখনও খুব ভারী লাগলে টেলি-মানস (14416) বিনামূল্যে আর গোপনে কথা বলার সুযোগ দেয়।', 'Kokhono khub bhari lagle Tele-MANAS (14416) binamulye ar gopone kotha bolar shujog dey.'],
  ['বড় আর্থিক সিদ্ধান্তের জন্য একজন আর্থিক পরামর্শদাতার সাহায্যে পরিকল্পনা করুন।', 'Boro arthik siddhanter jonno ekjon financial adviser-er sahajje porikolpona korun.'],
  ['শরীরের কোনো সমস্যায় অবশ্যই ডাক্তার দেখান।', 'Shorirer kono shomoshyay oboshyoi daktar dekhan.'],
  ['এর পাশাপাশি আপনার ডাক্তার বা ফার্টিলিটি বিশেষজ্ঞের পরামর্শ নিতে থাকুন; চিকিৎসার দিকটা তাঁরাই সবচেয়ে ভালো বোঝাবেন।', 'Er pashapashi apnar daktar ba fertility specialist-er poramorsho nite thakun; chikitsar dikta tarai sobcheye bhalo bojhaben.'],
  ['আপনি যা বলছেন তাতে এখনই চিকিৎসা দরকার: এখনই 112-এ ফোন করুন বা কাছের হাসপাতাল বা ডাক্তারের কাছে যান। চার্ট দিয়ে এটা কখনও বিচার করা যায় না, আর এতে দেরি করা ঠিক নয়।', 'Apni ja bolchhen tate ekhoni chikitsa dorkar: ekhoni 112-e phone korun ba kachher haspatal ba daktarer kachhe jan. Chart diye eta kokhono bichar kora jay na, ar ete deri kora thik noy.'],
  ['আপনার নিরাপত্তাই আগে। বিপদে থাকলে 112 বা মহিলা হেল্পলাইন 181-এ ফোন করুন, আর বিশ্বস্ত কারও সঙ্গে কথা বলুন। কোনো গ্রহের হিসেব যেন আপনাকে বিপদের মধ্যে রেখে না দেয়, আর এতে আপনার কোনো দোষ নেই।', 'Apnar nirapotta-i age. Bipode thakle 112 ba mohila helpline 181-e phone korun, ar bishshosto karo sathe kotha bolun. Kono grohor hiseb jeno apnake bipoder moddhe rekhe na dey, ar ete apnar kono dosh nei.'],
  ['একজন কাউন্সেলর আপনার পরের পদক্ষেপগুলো নিরাপদে, নিজের মতো করে ঠিক করতে সাহায্য করতে পারেন।', 'Ekjon counsellor apnar porer podokkhepgulo nirapode, nijer moto kore thik korte sahajjo korte paren.'],
  ['এতে কারও দোষ খোঁজার দরকার নেই।', 'Ete karo dosh khojar dorkar nei.'],
  ['সিদ্ধান্তটা আপনার নিজের, আর এর জন্য সময় নেওয়াই ভালো।', 'Siddhantota apnar nijer, ar er jonno somoy neoai bhalo.'],
  ['যেটা আপনার নিজের বিশ্বাসের সঙ্গে মেলে সেটাই নিন; কোনো আচার-অনুষ্ঠানের চেয়ে আপনার সিদ্ধান্তই বড়।', 'Jeta apnar nijer bishshasher sathe mele setai nin; kono achar-onushthaner cheye apnar siddhantoi boro.'],
  ['জানানোর জন্য ধন্যবাদ।', 'Jananor jonno dhonnobad.'],
  ['স্বাগত, কাজে লেগেছে জেনে খুশি হলাম। যখন খুশি জিজ্ঞেস করবেন।', 'Swagoto, kaje legeche jene khushi holam. Jokhon khushi jiggesh korben.'],
  ['আমি ভালো আছি, ধন্যবাদ! আমি সাগা, আপনার জ্যোতিষ সঙ্গী। আপনার কাজ, সম্পর্ক বা সামনের বছরটা কেমন যাবে, তা নিয়ে জানতে চান?', 'Ami bhalo achhi, dhonnobad! Ami Saga, apnar jyotish shongi. Apnar kaj, somporko ba samner bochhorta kemon jabe, ta niye jante chan?'],
  ['এটা আমার কাজের বাইরে; আমি আপনার কুষ্ঠি নিয়ে কথা বলার জন্য আছি। চাইলে আপনার কাজের জোরের দিক বা এই বছরের সবচেয়ে ভালো সময় নিয়ে বলতে পারি।', 'Eta amar kajer baire; ami apnar kushti niye kotha bolar jonno achhi. Chaile apnar kajer jorer dik ba ei bochhorer sobcheye bhalo somoy niye bolte pari.'],
  ['আমি লটারির নম্বর বা শেয়ার বাজারের টিপস দিই না: কোনো কুষ্ঠি এগুলো বলতে পারে না, আর এতে টাকা লাগানো নিরাপদ নয়।', 'Ami lotterir number ba share bajarer tips dii na: kono kushti egulo bolte pare na, ar ete taka lagano nirapod noy.'],
  ['দুঃখিত, উত্তরটা কাজে লাগল না। বলুন কী জানতে চান, যেমন কোন কাজ আপনার জন্য ঠিক বা পরিবর্তন কবে হতে পারে, আমি স্পষ্ট করে বলব।', 'Dukkhito, uttorta kaje laglo na. Bolun ki jante chan, jemon kon kaj apnar jonno thik ba poriborton kobe hote pare, ami sposhto kore bolbo.'],
  ['আমি সাহায্য করতে আছি। আপনার কুষ্ঠি নিয়ে যা খুশি জিজ্ঞেস করুন, যেমন কোন কাজ আপনার জন্য ঠিক বা পরিবর্তন কবে হতে পারে।', 'Ami sahajjo korte achhi. Apnar kushti niye ja khushi jiggesh korun, jemon kon kaj apnar jonno thik ba poriborton kobe hote pare.'],
  ['হ্যাঁ, আপনার চার্টে বিয়ে স্পষ্ট দেখা যায়; প্রশ্নটা শুধু সময়ের, হবে কি না তার নয়।', 'Hyan, apnar charte biye sposhto dekha jay; proshnota shudhu somoyer, hobe ki na tar noy.'],
  ['দুঃখিত, কথাটা স্পষ্ট না হয়ে থাকলে সহজ করে বলি:', 'Dukkhito, kothata sposhto na hoye thakle sohoj kore boli:'],
  ['জাত, গায়ের রং, ধর্ম বা আপনি কাকে ভালোবাসবেন, তা কুষ্ঠি ঠিক করে না, আর আমি এসব আন্দাজও করব না।', 'Jat, gayer rong, dhormo ba apni kake bhalobashben, ta kushti thik kore na, ar ami esob andajo korbo na.'],
  ['তবে আপনার সঙ্গী স্বভাবে কেমন হবেন আর কোথায় দেখা হতে পারে, তা বলা যায়।', 'Tobe apnar shongi swobhabe kemon hoben ar kothay dekha hote pare, ta bola jay.'],
  ['আপনি কে আর কাকে ভালোবাসেন, তা আপনিই ঠিক করেন; কুষ্ঠি তা ঠিক করে না, আর এখানে প্রতিটি উত্তরই সম্মানের। চাইলে আপনার সম্পর্ক বা সামনের বছর নিয়ে বলতে পারি।', 'Apni ke ar kake bhalobashen, ta apnii thik koren; kushti ta thik kore na, ar ekhane protiti uttor-i sommaner. Chaile apnar somporko ba samner bochhor niye bolte pari.'],
  ['কুষ্ঠি থেকে কারও নাম বা নামের প্রথম অক্ষর জানা যায় না, তাই আমি আন্দাজ করব না।', 'Kushti theke karo naam ba namer prothom okkhor jana jay na, tai ami andaj korbo na.'],
  ['আমি শিশুর লিঙ্গ বলি না, মজা করেও না: ভারতে জন্মের আগে তা জানা আইনত নিষিদ্ধ, কারণ এর অপব্যবহার হয়েছে, আর কোনো কুষ্ঠি তা দেখাতেও পারে না।', 'Ami shishur lingo boli na, moja koreo na: Bharote jonmer age ta jana ainoto nishiddho, karon er opobyabohar hoyeche, ar kono kushti ta dekhateo pare na.'],
  ['বরং আপনার পরিবার আর ঘরের সামনের মাসগুলো নিয়ে আনন্দের সঙ্গে বলতে পারি।', 'Borong apnar paribar ar ghorer samner mashgulo niye anonder sathe bolte pari.'],
  ['উনি অসুস্থ শুনে খুব খারাপ লাগছে।', 'Uni oshustho shune khub kharap lagchhe.'],
  ['কোন রোগ বা তা কতটা গুরুতর, তা কুষ্ঠি থেকে বলা যায় না; সেটা শুধু ডাক্তারের পরীক্ষাতেই জানা যায়।', 'Kon rog ba ta kotota guruttor, ta kushti theke bola jay na; seta shudhu daktarer porikkhatei jana jay.'],
  ['ডাক্তারের পরামর্শ ছাড়া কোনো ওষুধ বন্ধ বা বদল করবেন না: কোনো রত্ন বা প্রতিকার চিকিৎসার বিকল্প নয়।', 'Daktarer poramorsho chhara kono oshudh bondho ba bodol korben na: kono rotno ba protikar chikitsar bikolpo noy.'],
  ['এখানে সার্জনের মতামতই আগে; অপারেশন কেমন হবে তা কুষ্ঠি থেকে বলা যায় না।', 'Ekhane surgeon-er motamot-i age; operation kemon hobe ta kushti theke bola jay na.'],
  ['সবচেয়ে বেশি সাহায্য করে বিশ্রাম, ডাক্তারের প্রতিটি নির্দেশ মেনে চলা আর পরিবারের পাশে থাকা।', 'Sobcheye beshi sahajjo kore bishram, daktarer protiti nirdesh mene chola ar paribarer pashe thaka.'],
  ['{name} অসুস্থ শুনে খারাপ লাগছে। কুষ্ঠি থেকে চিকিৎসার ফল বলা যায় না; যে ডাক্তাররা দেখছেন, তাঁরাই সেটা বলতে পারবেন।', '{name} oshustho shune kharap lagchhe. Kushti theke chikitsar fol bola jay na; je daktarra dekhchhen, tarai seta bolte parben.'],
  ['পাশে থাকা, তাঁর রুটিন শান্ত রাখা আর নিজের ঘুম ও বিশ্রামের যত্ন নেওয়া পুরো পরিবারকে সাহায্য করে।', 'Pashe thaka, tar routine shanto rakha ar nijer ghum o bishramer jotno neoa puro paribarke sahajjo kore.'],
  ['আপনার চার্ট থেকে অন্য কারও মনের কথা পড়া যায় না; সেটা তিনিই বলতে পারেন।', 'Apnar chart theke onno karo moner kotha pora jay na; seta tinii bolte paren.'],
  ['জানার সবচেয়ে ভালো উপায় হলো চাপ না দিয়ে তাঁর সঙ্গে শান্তভাবে, সৎভাবে কথা বলা।', 'Janar sobcheye bhalo upay holo chap na diye tar sathe shantobhabe, sotbhabe kotha bola.'],
  ['শাস্ত্রে কোনো দেশের নাম বলা থাকে না, তাই আমি কোনো দেশ বেছে দেব না; চার্ট দেখায় বিদেশে থাকার টান কতটা আর কখন।', 'Shastre kono desher naam bola thake na, tai ami kono desh beche debo na; chart dekhay bideshe thakar tan kotota ar kokhon.'],
  ['কাল সর্প সেই প্রাচীন শাস্ত্রে নেই যেগুলো এই অ্যাপ মেনে চলে, তাই এ নিয়ে ভয়ের কিছু নেই।', 'Kal Sorpo sei prachin shastre nei jegulo ei app mene chole, tai e niye bhoyer kichhu nei.'],
  ['পুরোহিতমশাইয়ের পরামর্শ মানলে সেটা আপনার সিদ্ধান্ত; মনের শান্তির জন্য সাধারণ শৃঙ্খলা আর দয়াই যথেষ্ট।', 'Purohitmoshaier poramorsho manle seta apnar siddhanto; moner shantir jonno sadharon shrinkhola ar doyai jotheshto.'],
  ['গৃহপ্রবেশ বা বিয়ের মতো অনুষ্ঠানের দিন প্রথা মেনে পরিবারের পুরোহিত ঠিক করেন; মুহূর্ত ট্যাব কাজ শুরু, কেনাকাটা, সই আর যাত্রার মতো কাজের জন্য।', 'Grihoprobesh ba biyer moto onushthaner din protha mene paribarer purohit thik koren; Muhurto tab kaj shuru, kenakata, shoi ar jatrar moto kajer jonno.'],
  ['যে দিনটা আপনি নিজে বেছে নেন, যেমন সই বা কোনো অনুষ্ঠান, তার জন্য মুহূর্ত ট্যাব ভালো দিন দেখায়।', 'Je dinta apni nije beche nen, jemon shoi ba kono onushthan, tar jonno Muhurto tab bhalo din dekhay.'],
  ['বুঝতে পারছি আপনি একটা তারিখ চান, কিন্তু কুষ্ঠি কোনো ঘটনাকে মাস আর সময়ের পরিসর পর্যন্ত বলতে পারে, নির্দিষ্ট একটা দিন নয়।', 'Bujhte parchhi apni ekta tarikh chan, kintu kushti kono ghotonake mash ar somoyer porisor porjonto bolte pare, nirdishto ekta din noy.'],
  ['হ্যাঁ, তবুও আপনার চার্ট থেকে অনেক কিছু বলা যায়।', 'Hyan, tobuo apnar chart theke onek kichhu bola jay.'],
  ['জন্মসময় ছাড়াও চার্ট থেকে কাজের উত্তর পাওয়া যায়।', 'Jonmo somoy chharao chart theke kajer uttor paoa jay.'],
  ['তার পরে সেরে ওঠা আর শক্তির জন্য আপনার চার্টে {start} থেকে {end} পর্যন্ত {kind} সময়।', 'Tar pore sere otha ar shoktir jonno apnar charte {start} theke {end} porjonto {kind} somoy.'],
  ['জন্মসময় ছাড়া আমি আপনার চন্দ্ররাশি থেকে ঘর গুনি; তাতেও কাজের ছবি পাওয়া যায়, শুধু সময়টা আনুমানিক থাকে।', 'Jonmo somoy chhara ami apnar chondrorashi theke ghor guni; tateo kajer chhobi paoa jay, shudhu somoyta anumanik thake.'],
  ['জন্মের সময়টা পেলে (জন্ম সার্টিফিকেট, হাসপাতালের রেকর্ড বা পরিবারের কারও মনে থাকলে), প্রোফাইলে যোগ করুন, উত্তর আরও নিখুঁত হবে।', 'Jonmer somoyta pele (jonmo certificate, haspataler record ba paribarer karo mone thakle), profile-e jog korun, uttor aro nikhut hobe.'],
  ['এটা আনুমানিক, কারণ জন্মসময় ছাড়া লগ্ন আর ঘর ঠিক করা যায় না, আর জীবনচক্রের তারিখগুলো একটু সরে যেতে পারে।', 'Eta anumanik, karon jonmo somoy chhara lagno ar ghor thik kora jay na, ar jibonchokrer tarikhgulo ektu sore jete pare.'],
  ['এটা কি আপনার অভিজ্ঞতার সঙ্গে মেলে? মিললে বোঝা যায় আপনার জন্মসময়ও ঠিক আছে।', 'Eta ki apnar obhigyotar sathe mele? Mille bojha jay apnar jonmo somoy-o thik ache.'],
  ['পিছনে তাকালে {year} একটা ভারী সময়ের মধ্যে পড়ে: {why}।', 'Pichhone takale {year} ekta bhari somoyer moddhe pore: {why}.'],
  ['পিছনে তাকালে {year} আপনার চার্টে মোটামুটি সহায়ক বছর ছিল: {why}।', 'Pichhone takale {year} apnar charte motamuti sohayok bochhor chhilo: {why}.'],
  ['আপনার চার্টে সরকারি চাকরির ভালো সমর্থন আছে: কর্তৃত্বের গ্রহ জোরালো।', 'Apnar charte sorkari chakrir bhalo somorthon ache: kortritter groho joralo.'],
  ['আপনার চার্টে সরকারি চাকরির জন্য ভালো সমর্থন আছে: কর্তৃত্বের গ্রহ, যা সরকারের প্রতীক, জোরালো আর আপনার কাজের দিকের সঙ্গে যুক্ত।', 'Apnar charte sorkari chakrir jonno bhalo somorthon ache: kortritter groho, ja sorkarer protik, joralo ar apnar kajer diker sathe jukto.'],
  ['আপনার চার্টে সরকারি চাকরির মোটামুটি সম্ভাবনা আছে; প্রস্তুতিই অনেকটা ঠিক করবে।', 'Apnar charte sorkari chakrir motamuti sombhabona ache; prostuti-i onekta thik korbe.'],
  ['আপনার চার্টে সরকারি চাকরির মোটামুটি সম্ভাবনা আছে: কর্তৃত্বের গ্রহ স্থির, তবে খুব প্রবল নয়, তাই প্রস্তুতিই অনেকটা ঠিক করবে।', 'Apnar charte sorkari chakrir motamuti sombhabona ache: kortritter groho sthir, tobe khub probol noy, tai prostuti-i onekta thik korbe.'],
  ['সরকারি চাকরি চার্টের সবচেয়ে জোরালো টান নয়, তাই একটা বেসরকারি বিকল্পও খোলা রাখুন।', 'Sorkari chakri charter sobcheye joralo tan noy, tai ekta besorkari bikolpo-o khola rakhun.'],
  ['সরকারি চাকরি চার্টের সবচেয়ে জোরালো টান নয়; আপনার মানানসই ক্ষেত্রে বেসরকারি কাজ বেশি স্বাভাবিক দেখায়, তাই দুটো পথই খোলা রাখুন।', 'Sorkari chakri charter sobcheye joralo tan noy; apnar mananshoi khetre besorkari kaj beshi swabhabik dekhay, tai duto poth-i khola rakhun.'],
  ['নিয়মিত মক টেস্ট দিন আর দুর্বল অংশ রিভিশন করতে থাকুন।', 'Niyomito mock test din ar durbol ongsho revision korte thakun.'],
  ['সামনের মাসগুলোয় পরীক্ষার মতো পরিবেশে মক টেস্ট দিন আর দুর্বল অংশগুলো নিয়মিত রিভিশন করুন; বেশি ঘণ্টার চেয়ে নিয়মিত পড়াই বেশি কাজের।', 'Samner mashgulote porikkhar moto poribeshe mock test din ar durbol ongshogulo niyomito revision korun; beshi ghontar cheye niyomito porai beshi kajer.'],
  ['বাড়ির লোক বিয়ের জন্য চাপ দিলে তাঁদের বলা ঠিক যে আপনি আগে পড়াশোনা শেষ করতে চান; কোনো শিক্ষক, স্কুলের কাউন্সেলর বা চাইল্ডলাইন (1098) তাঁদের সঙ্গে কথা বলতে সাহায্য করতে পারে।', 'Barir lok biyer jonno chap dile tader bola thik je apni age porashona shesh korte chan; kono shikkhok, school-er counsellor ba Childline (1098) tader sathe kotha bolte sahajjo korte pare.'],
  ['পরীক্ষা দিলে লম্বা সময়ের চেয়ে রোজের শান্ত পড়া আর অনুশীলন বেশি কাজের; এই বয়সে পরামর্শদাতা বা চুক্তিভিত্তিক কাজও দেখার মতো।', 'Porikkha dile lomba somoyer cheye rojer shanto pora ar onushilon beshi kajer; ei boyoshe poramorshodata ba chuktibhittik kaj-o dekhar moto.'],
  ['প্রতি সপ্তাহে মক টেস্ট আর নিয়মিত রিভিশন নিয়ে প্রস্তুতি নিন।', 'Proti soptahe mock test ar niyomito revision niye prostuti nin.'],
  ['রোজের নির্দিষ্ট সময়, প্রতি সপ্তাহে একটা মক টেস্ট আর নিয়মিত রিভিশন নিয়ে প্রস্তুতি নিন, আর একটা বেসরকারি বিকল্পও খোলা রাখুন।', 'Rojer nirdishto somoy, proti soptahe ekta mock test ar niyomito revision niye prostuti nin, ar ekta besorkari bikolpo-o khola rakhun.'],
  ['প্রতি মাসে আগে একটা নির্দিষ্ট অংশ সঞ্চয় করুন, তিন মাসের খরচ আলাদা রাখুন, আর দুর্বল মাসগুলোয় ধার দেওয়া বা বড় ঝুঁকি এড়িয়ে চলুন।', 'Proti mashe age ekta nirdishto ongsho sonchoy korun, tin masher khoroch alada rakhun, ar durbol mashgulote dhar deoa ba boro jhuki eriye cholun.'],
  ['সব ঋণের তালিকা করুন, সবচেয়ে দামি ঋণটা আগে শোধ করুন, আর কিস্তি বাদ পড়ার আগেই ব্যাংকের সঙ্গে পুনর্গঠনের কথা বলুন; শোধ করার মধ্যেও প্রতি মাসে একটু সঞ্চয় করুন।', 'Sob rriner talika korun, sobcheye dami rrinta age shodh korun, ar kisti bad porar agei banker sathe punorgothoner kotha bolun; shodh korar moddheo proti mashe ektu sonchoy korun.'],
  ['শান্তভাবে আর লিখিতভাবে খোঁজ নিন, আর কত টাকা দিয়েছিলেন তার হিসেব রাখুন; চার্ট ভালো সময় দেখাতে পারে, অন্যজনের সিদ্ধান্ত নয়।', 'Shantobhabe ar likhitobhabe khoj nin, ar koto taka diyechhilen tar hiseb rakhun; chart bhalo somoy dekhate pare, onnojoner siddhanto noy.'],
  ['পাকা করার আগে বাজেট, ঋণ আর বিমার কাগজপত্র দেখে নিন আর একবার টেস্ট ড্রাইভ করুন; গাড়ি নেওয়ার দিনের জন্য মুহূর্ত ট্যাব দেখুন।', 'Paka korar age budget, rrin ar bimar kagojpotro dekhe nin ar ekbar test drive korun; gari neoar diner jonno Muhurto tab dekhun.'],
  ['{who} সঙ্গে আপনার সম্পর্কে ভরসার ইঙ্গিত আছে, তাই সমর্থন পাওয়ার ভালো সম্ভাবনা আছে, যদিও ওঁর নিজের পরিস্থিতিও গুরুত্বপূর্ণ।', '{who} sathe apnar somporke bhorshar ingit ache, tai somorthon paoar bhalo sombhabona ache, jodio onar nijer poristhiti-o gurutvopurno.'],
  ['সমর্থন পাওয়া সম্ভব, তবে স্পষ্ট আর শান্তভাবে বলতে হবে: আপনার চার্টে {who} সঙ্গে সম্পর্কে কিছুটা টানাপোড়েন আছে।', 'Somorthon paoa sombhob, tobe sposhto ar shantobhabe bolte hobe: apnar charte {who} sathe somporke kichhuta tanaporen ache.'],
  ['পাকা করার আগে বাজেট, কাগজপত্র আর আইনি মালিকানা যাচাই করুন; রেজিস্ট্রির দিনের জন্য মুহূর্ত ট্যাব দেখুন।', 'Paka korar age budget, kagojpotro ar aini malikana jachai korun; registryr diner jonno Muhurto tab dekhun.'],
  ['আপনার চার্টে অংশীদারি মোটামুটি সহায়ক: আপনার অংশীদারির দিক আর নিজের দিক মিলে কাজ করে। প্রতিটি ভাগ আর দায়িত্ব লিখিতভাবে ঠিক করুন।', 'Apnar charte ongshidari motamuti sohayok: apnar ongshidarir dik ar nijer dik mile kaj kore. Protiti bhag ar dayitto likhitobhabe thik korun.'],
  ['আপনার চার্টে অংশীদারি একটু ধীর দেখায়; নিয়ন্ত্রণ নিজের হাতে রাখাই আপনার পক্ষে ভালো, তাই এগোলে স্পষ্ট চুক্তি আর ছোট শুরু করুন।', 'Apnar charte ongshidari ektu dhir dekhay; niyontron nijer hate rakhai apnar pokkhe bhalo, tai egole sposhto chukti ar chhoto shuru korun.'],
  ['এখন থেকেই আবেদন শুরু করুন আর সেই সময়ের মধ্যে বদলান।', 'Ekhon thekei abedon shuru korun ar sei somoyer moddhe bodlan.'],
  ['জোরালো সময় শুরু হলেই বদলের সমর্থন মেলে, তাই এখন থেকেই আবেদন শুরু করুন আর সেই সময়ের মধ্যে বদলান।', 'Joralo somoy shuru holei bodoler somorthon mele, tai ekhon thekei abedon shuru korun ar sei somoyer moddhe bodlan.'],
  ['আপাতত যেখানে আছেন সেখানেই এগোনো ভালো, বদল করুন জোরালো সময়ে।', 'Apatoto jekhane achhen sekhanei egono bhalo, bodol korun joralo somoye.'],
  ['আপাতত যেখানে আছেন সেখানেই এগোনো ভালো, আর জোরালো সময়ে বদলান; ততদিন বিকল্পগুলো তৈরি রাখুন।', 'Apatoto jekhane achhen sekhanei egono bhalo, ar joralo somoye bodlan; totodin bikolpogulo toiri rakhun.'],
  ['হাতে অফার আসার আগে চাকরি ছাড়বেন না: এখনই আবেদন করুন যাতে বদলটা ওই সময়ের মধ্যে হয়, আর এখনকার আয় বজায় রাখুন।', 'Hate offer asar age chakri chharben na: ekhoni abedon korun jate bodolta oi somoyer moddhe hoy, ar ekhonkar aay bojay rakhun.'],
  ['প্রতি সপ্তাহে কথা বলার একটা শান্ত সময় ঠিক করুন, আগে শুনুন, আর ঝগড়ার মাঝে বড় সিদ্ধান্ত নেবেন না।', 'Proti soptahe kotha bolar ekta shanto somoy thik korun, age shunun, ar jhogrhar majhe boro siddhanto neben na.'],
  ['এখানে তাঁর সিদ্ধান্তই সবচেয়ে বড়; যা আপনার হাতে আছে তাতে মন দিন, আর চাপ ছাড়াই সম্পর্ককে সুযোগ দিন।', 'Ekhane tar siddhantoi sobcheye boro; ja apnar hate ache tate mon din, ar chap chhara-i somporkoke shujog din.'],
  ['বাবা-মায়ের সঙ্গে আগেভাগে শান্তভাবে কথা বলুন, মানুষটিকে চেনার সুযোগ দিন, আর তাঁদের সময় দিন।', 'Baba-mayer sathe agebhage shantobhabe kotha bolun, manushtike chenar shujog din, ar tader somoy din.'],
  ['ছোট অভ্যাস গড়ুন: সপ্তাহে একবার একসঙ্গে খাওয়া, আর কে কী করবে তা নিয়ে স্পষ্ট, নরম কথা বলা।', 'Chhoto obhyash gorun: soptahe ekbar ekshathe khaoa, ar ke ki korbe ta niye sposhto, norom kotha bola.'],
  ['মামলা ইতিমধ্যে চললে, {start} থেকে {end} সময়টা বিষয়টা মেটানোর জন্য সবচেয়ে ভালো দেখায়।', 'Mamla itimoddhe chalu thakle, {start} theke {end} somoyta bishoyta metanor jonno sobcheye bhalo dekhay.'],
  ['চার্টে আপনার সম্পর্কের দিকে একটা টানাপোড়েনের সময় দেখা যায়, যা মোটামুটি {start} থেকে হালকা হয়; আপনার বিয়ের সিদ্ধান্ত চার্ট নেয় না।', 'Charte apnar somporker dike ekta tanaporener somoy dekha jay, ja motamuti {start} theke halka hoy; apnar biyer siddhanto chart ney na.'],
  ['তাহলে আসল প্রশ্ন হলো আপনাদের বিয়ে সামনে কেমন যাবে: {start} থেকে {end} সময়টা আপনাদের দুজনের জন্য বিশেষ করে ভালো।', 'Tahole asol proshno holo apnader biye samne kemon jabe: {start} theke {end} somoyta apnader dujoner jonno bishesh kore bhalo.'],
  ['সন্তানের পরিকল্পনা থাকলে, এই সময়টা তার জন্যও ভালো।', 'Santaner porikolpona thakle, ei somoyta tar jonno-o bhalo.'],
  ['আপনাদের দুজনের 36-এর মধ্যে {score} গুণ মেলে, যাকে প্রথায় {verdict} বলা হয়।', 'Apnader dujoner 36-er moddhe {score} gun mele, jake prothay {verdict} bola hoy.'],
  ['আপনাদের সবচেয়ে ভালো দিক: {good}।', 'Apnader sobcheye bhalo dik: {good}.'],
  ['যে একটা দিকে কাজ করতে হবে: {work}।', 'Je ekta dike kaj korte hobe: {work}.'],
  ['অনেক সুখী দম্পতির গুণ কম মেলে; একে অপরের সঙ্গে কথা বলা আর পাশে থাকাই সংখ্যার চেয়ে বেশি জরুরি।', 'Onek sukhi dompotir gun kom mele; ek opor-er sathe kotha bola ar pashe thakai sonkhyar cheye beshi joruri.'],
  ['বিয়ে করবেন কি না, সেটা আপনার সিদ্ধান্ত; শুধু গুণের সংখ্যা দিয়ে তা ঠিক হওয়া উচিত নয়।', 'Biye korben ki na, seta apnar siddhanto; shudhu guner sonkhya diye ta thik hoya uchit noy.'],
  ['পরিবার যে নাড়ি দোষের কথা বলছে: {nadi}। পুরো ছবিটা নিয়ে তাঁদের সঙ্গে শান্তভাবে কথা বলুন।', 'Paribar je nari dosher kotha bolchhe: {nadi}. Puro chhobita niye tader sathe shantobhabe kotha bolun.'],
  ['পুরো বিবরণ কম্প্যাটিবিলিটি স্ক্রিনে আছে।', 'Puro biboron Compatibility screen-e ache.'],
  ['মিল দেখার জন্য তাঁর জন্মতারিখ, সময় আর জায়গা লাগবে: প্রোফাইলে যোগ করুন, তারপর কম্প্যাটিবিলিটি স্ক্রিন খুলুন বা আবার জিজ্ঞেস করুন।', 'Mil dekhar jonno tar jonmo tarikh, somoy ar jayga lagbe: profile-e jog korun, tarpor Compatibility screen khulun ba abar jiggesh korun.'],
  ['এটা মজবুত করতে প্রতি সপ্তাহে পরিকল্পনা আর দুশ্চিন্তা নিয়ে একটা ধীরস্থির কথা বলুন, আর মতভেদ আসার আগেই ঠিক করুন সেটা কীভাবে সামলাবেন।', 'Eta mojbut korte proti soptahe porikolpona ar dushchinta niye ekta dhirsthir kotha bolun, ar motobhed asar agei thik korun seta kibhabe samlaben.'],
  ['এর উত্তর দিতে ওঁর নিজের জন্মের তথ্য লাগবে। ওঁকে প্রোফাইলে যোগ করে ওঁর চ্যাটে জিজ্ঞেস করুন।', 'Er uttor dite onar nijer jonmer tottho lagbe. Onake profile-e jog kore onar chat-e jiggesh korun.'],
  ['আপনার দুটো প্রোফাইল সেভ করা আছে: {names}। কোন জনের কথা বলছেন? তাঁর চ্যাট খুলে জিজ্ঞেস করুন বা নামটা বলুন।', 'Apnar duto profile save kora ache: {names}. Kon joner kotha bolchhen? Tar chat khule jiggesh korun ba naamta bolun.'],
  ['এই আনন্দটা দেখা যায় আপনার সন্তানদের নিজেদের কুষ্ঠিতে; ছেলে বা মেয়ের জন্মের তথ্য যোগ করলে তাঁদের পরিবারের সময় দেখতে পারি। আপনার নিজের কুষ্ঠিতে ঘরে সুখের বছর দেখা যায়, আর তা কীভাবে কাটাবেন সেটা আপনার সিদ্ধান্ত।', 'Ei anondota dekha jay apnar santander nijeder kushtite; chhele ba meyer jonmer tottho jog korle tader paribarer somoy dekhte pari. Apnar nijer kushtite ghore sukher bochhor dekha jay, ar ta kibhabe kataben seta apnar siddhanto.'],
  ['এই বছরগুলো কীভাবে কাটাবেন সেটা আপনার সিদ্ধান্ত; চার্ট বলে ধীরস্থির ছন্দ, পরিবারের সঙ্গে সময় আর নিজের অভিজ্ঞতা ভাগ করে নেওয়ার কথা।', 'Ei bochhorgulo kibhabe kataben seta apnar siddhanto; chart bole dhirsthir chhondo, paribarer sathe somoy ar nijer obhigyota bhag kore neoar kotha.'],
  ['এ নিয়ে ভাবলে একজন ফার্টিলিটি বিশেষজ্ঞ ডাক্তারের পরামর্শ নিন।', 'E niye bhable ekjon fertility specialist daktarer poramorsho nin.'],
  ['ততদিন নিয়মিত ঘুম আর রোজ একটু হাঁটা সবচেয়ে বেশি সাহায্য করে।', 'Totodin niyomito ghum ar roj ektu hanta sobcheye beshi sahajjo kore.'],
  ['ততদিন নিয়মিত ঘুম, রোজ একটু হাঁটা আর প্রতিদিন কিছুটা শান্ত সময় সবচেয়ে বেশি সাহায্য করে।', 'Totodin niyomito ghum, roj ektu hanta ar protidin kichhuta shanto somoy sobcheye beshi sahajjo kore.'],
  ['আপনি যা অনুভব করছেন তার কিছুটা আপনার চার্টের এখনকার পর্বের সঙ্গে মেলে: {why}।', 'Apni ja onubhob korchhen tar kichhuta apnar charter ekhonkar porber sathe mele: {why}.'],
  ['আপনার চার্টে এখন কম শক্তির একটা সময় দেখা যায়: {why}।', 'Apnar charte ekhon kom shoktir ekta somoy dekha jay: {why}.'],
  ['তাড়াতাড়ি রাগ সাধারণত অনেক উদ্যমের সঙ্গে আসে: রোজ ব্যায়াম, উত্তর দেওয়ার আগে দশটা শ্বাসের বিরতি আর পর্যাপ্ত ঘুম এই শক্তিকে ঠিক পথে চালায়।', 'Taratari rag sadharonoto onek udyomer sathe ase: roj byayam, uttor deoar age doshta shwasher birati ar porjapto ghum ei shoktike thik pothe chalay.'],
  ['আপনার জন্য মনের শান্তি পাওয়া সম্ভব দেখায়, আর সহজ, নিয়মিত অনুশীলনে তা বাড়ে।', 'Apnar jonno moner shanti paoa sombhob dekhay, ar sohoj, niyomito onushilone ta bare.'],
  ['কোনো দামি কিছু করার দরকার নেই। {planet}-এর জন্য প্রথাগত প্রতিকারগুলো বিনামূল্যে: {items}।', 'Kono dami kichhu korar dorkar nei. {planet}-er jonno prothagoto protikargulo binamulye: {items}.'],
  ['এগুলো এমন প্রতিকার যাতে কোনো আচার নেই: {items}।', 'Egulo emon protikar jate kono achar nei: {items}.'],
  ['এগুলো বিনামূল্যে আর ঐচ্ছিক; যেগুলো আপনার বিশ্বাসের সঙ্গে মেলে সেগুলো নিন, বাকিটা আপনার চেষ্টাই করবে।', 'Egulo binamulye ar oichchhik; jegulo apnar bishshasher sathe mele segulo nin, bakita apnar cheshtai korbe.'],
  ['প্রথা অনুযায়ী {gem}-কে {planet}-এর সঙ্গে যুক্ত ধরা হয়, তবে এটা দরকার নেই: ভয় থেকে কখনও রত্ন পরবেন না, আর এটা চেষ্টা বা চিকিৎসার বিকল্প নয়। তবুও ভাবলে কোনো যোগ্য মানুষের সঙ্গে কথা বলুন আর বেশি খরচ করবেন না।', 'Protha onujayi {gem}-ke {planet}-er sathe jukto dhora hoy, tobe eta dorkar nei: bhoy theke kokhono rotno porben na, ar eta cheshta ba chikitsar bikolpo noy. Tobuo bhable kono joggo manusher sathe kotha bolun ar beshi khoroch korben na.'],
  ['কোনো পাথর কাজ তাড়াতাড়ি করায় না; ভালো সময়ে নিয়মিত রুটিন আর চেষ্টাই অনেক বেশি কাজ করে।', 'Kono pathor kaj taratari koray na; bhalo somoye niyomito routine ar cheshtai onek beshi kaj kore.'],
  ['আজ আপনার শুভ রং {colour} আর শুভ সংখ্যা {number}, যা {planet}-এর সঙ্গে যুক্ত।', 'Aaj apnar shubho rong {colour} ar shubho sonkhya {number}, ja {planet}-er sathe jukto.'],
  ['আপনার শুভ সংখ্যা {number}, যা আপনার চন্দ্ররাশির গ্রহ {planet} থেকে আসে; আজকের সংখ্যা {today}।', 'Apnar shubho sonkhya {number}, ja apnar chondrorashir groho {planet} theke ase; ajker sonkhya {today}.'],
  ['আপনার শুভ বার {weekday}, যা আপনার চন্দ্ররাশির গ্রহ {planet}-এর দিন।', 'Apnar shubho bar {weekday}, ja apnar chondrorashir groho {planet}-er din.'],
  ['আজকের সবচেয়ে ভালো সময় {time}।', 'Ajker sobcheye bhalo somoy {time}.'],
  ['একে একটা হালকা ইঙ্গিত ভাবুন, নিয়ম নয়; টুডে স্ক্রিনে এটা রোজ দেখা যায়।', 'Eke ekta halka ingit bhabun, niyom noy; Today screen-e eta roj dekha jay.'],
  ['{activity}-এর জন্য সামনের সবচেয়ে ভালো দিন {days}, শুভ তিথিতে আর রাহু কাল বাদ দিয়ে।', '{activity}-er jonno samner sobcheye bhalo din {days}, shubho tithite ar Rahu Kal bad diye.'],
  ['সামনের কয়েক দিনে {activity}-এর জন্য পরিষ্কার সময় নেই; মুহূর্ত ট্যাবে পরের সপ্তাহগুলো দেখুন।', 'Samner koek dine {activity}-er jonno porishkar somoy nei; Muhurto tab-e porer soptahgulo dekhun.'],
  ['এই দিনগুলো আপনার নিজের কুষ্ঠির সঙ্গেও মেলে: সেদিনের নক্ষত্র আপনার জন্মনক্ষত্র থেকে গুনলে শুভ (তারা বল), আর চাঁদ আপনার জন্মরাশি থেকে ভালো জায়গায় থাকে (চন্দ্র বল)।', 'Ei dingulo apnar nijer kushtir sathe-o mele: sediner nokkhotro apnar jonmonokkhotro theke gunle shubho (Tara Bol), ar chand apnar jonmorashi theke bhalo jaygay thake (Chondro Bol).'],
  ['এই দিনগুলো আপনার জন্মনক্ষত্র থেকে গোনা অশুভ তারাও এড়িয়ে যায় (তারা বল); জন্মরাশি থেকে চাঁদের অবস্থান মাঝারি, তাই দেওয়া সময়ের মধ্যেই কাজ করুন।', 'Ei dingulo apnar jonmonokkhotro theke gona oshubho tarao eriye jay (Tara Bol); jonmorashi theke chander obosthan majhari, tai deoa somoyer moddhei kaj korun.'],
  ['সামনের পরিষ্কার দিনগুলোর কোনোটাতেই আপনার জন্মনক্ষত্র থেকে গোনা শুভ তারা নেই, তাই এগুলো পঞ্জিকা অনুযায়ী সেরা দিন; দেওয়া সময়ের মধ্যেই কাজ করুন।', 'Samner porishkar dingulor konotatei apnar jonmonokkhotro theke gona shubho tara nei, tai egulo ponjika onujayi sera din; deoa somoyer moddhei kaj korun.'],
  ['আরও বিকল্প মুহূর্ত ট্যাবে পাবেন।', 'Aro bikolpo Muhurto tab-e paben.'],
  ['অপারেশনের তারিখ আগে ডাক্তার ঠিক করেন; ডাক্তার বিকল্প দিলে তবেই মুহূর্ত দেখা যায়।', 'Operation-er tarikh age daktar thik koren; daktar bikolpo dile tobei muhurto dekha jay.'],
  ['হ্যাঁ: আপনার চার্টে মঙ্গল একটা প্রথাগত মাঙ্গলিক অবস্থানে আছে।', 'Hyan: apnar charte Mongol ekta prothagoto Manglik obosthane ache.'],
  ['হালকাভাবে: মঙ্গল একটা দিক থেকে মাঙ্গলিক অবস্থানে, প্রধান দিক থেকে নয়।', 'Halkabhabe: Mongol ekta dik theke Manglik obosthane, prodhan dik theke noy.'],
  ['মঙ্গল মাঙ্গলিক অবস্থানে আছে, তবে আপনার চার্টে তা কেটে যায় ({why}), তাই এটা খাটে না।', 'Mongol Manglik obosthane ache, tobe apnar charte ta kete jay ({why}), tai eta khate na.'],
  ['না: আপনার চার্টে মঙ্গল মাঙ্গলিক অবস্থানে নেই।', 'Na: apnar charte Mongol Manglik obosthane nei.'],
  ['এটা খুবই সাধারণ, প্রায় অর্ধেক কুষ্ঠিতে থাকে, আর আসলে এর মানে শুধু কুষ্ঠি যত্ন করে মেলানো; এটা কোনো অশুভ লক্ষণ নয়।', 'Eta khubi sadharon, pray ordhek kushtite thake, ar asole er mane shudhu kushti jotno kore melano; eta kono oshubho lokkhon noy.'],
  ['আপনি এখন সাড়ে সাতির মধ্যে, তার {phase} পর্বে; এটা মোটামুটি {end}-এ শেষ হয়।', 'Apni ekhon Sare Sati-r moddhe, tar {phase} porbe; eta motamuti {end}-e shesh hoy.'],
  ['আপনি এখন সাড়ে সাতির মধ্যে নেই; পরেরটা মোটামুটি {start}-এ শুরু হবে।', 'Apni ekhon Sare Sati-r moddhe nei; porerta motamuti {start}-e shuru hobe.'],
  ['এটা একটু ধীর, পরিশ্রমের সময়, মূলত শক্তি, মন আর টাকার জন্য; এটা বিয়ে, চাকরি বা পড়াশোনা আটকায় না।', 'Eta ektu dhir, porishromer somoy, mulot shokti, mon ar takar jonno; eta biye, chakri ba porashona atkay na.'],
  ['সাড়ে সাতি হলো প্রায় সাড়ে সাত বছরের সময়, যখন শনি আপনার চন্দ্ররাশি আর তার দুপাশের রাশি পার হয়।', 'Sare Sati holo pray sare sat bochhorer somoy, jokhon Shoni apnar chondrorashi ar tar dupasher rashi par hoy.'],
  ['এখন আপনার {maha}-এর মহাদশা {end} পর্যন্ত চলছে, তার মধ্যে {antar}-এর অন্তর্দশা {aEnd} পর্যন্ত।', 'Ekhon apnar {maha}-er mahadasha {end} porjonto cholchhe, tar moddhe {antar}-er antordasha {aEnd} porjonto.'],
  ['সহজ কথায়, এই পর্বে আপনার জীবনের ঝোঁক থাকে {area} দিকে।', 'Sohoj kothay, ei porbe apnar jiboner jhonk thake {area} dike.'],
  ['চার্টের ওই জায়গায় {planet} আপনার {area} দিকে {nature} আনে: {effect}', 'Charter oi jaygay {planet} apnar {area} dike {nature} ane: {effect}'],
  ['{year} সবচেয়ে জোরালো দেখায় {a1}{a2}-এর জন্য: এদের সবচেয়ে ভালো সময় এই বছরেই পড়ে।', '{year} sobcheye joralo dekhay {a1}{a2}-er jonno: eder sobcheye bhalo somoy ei bochhorei pore.'],
  ['সে সময় টাকা আর শক্তি সাবধানে চালান, কারণ শনি তখন আপনার চন্দ্ররাশির ওপর চাপ দেয়।', 'Se somoy taka ar shokti sabdhane chalan, karon Shoni tokhon apnar chondrorashir opor chap dey.'],
  ['{month}-এ আপনার জীবনচক্রের একটা নতুন অংশও শুরু হয়, যা মন টানে {area} দিকে।', '{month}-e apnar jibonchokrer ekta notun ongsho-o shuru hoy, ja mon tane {area} dike.'],
  ['সেই বছর {a1}-কে সবার আগে রাখুন।', 'Sei bochhor {a1}-ke shobar age rakhun.'],
  ['আপনার জন্য একটা সহজ অনুশীলন ভালো: {practice}।', 'Apnar jonno ekta sohoj onushilon bhalo: {practice}.'],
  ['ওই সময়ে {planetGen} অন্তর্দশা চলে, যা আপনার চার্টে {topic} সঙ্গে যুক্ত: {link}।', 'Oi somoye {planetGen} antordasha chole, ja apnar charte {topic} sathe jukto: {link}.'],
  ['এই ইন্টারভিউয়ের ফল নির্ভর করে সেটা কেমন হয়েছে আর সংস্থার কী দরকার তার ওপর; চার্ট শুধু দেখায় সময়টা আপনার কতটা পাশে আছে।', 'Ei interview-er fol nirbhor kore seta kemon hoyeche ar songsthar ki dorkar tar opor; chart shudhu dekhay somoyta apnar kotota pashe ache.'],
  ['ঠিক তখনই বৃহস্পতি আর শনি দুজনেই চার্টের ওই দিকের পাশে থাকে, যা কাজ এগোনোর পুরনো লক্ষণ।', 'Thik tokhoni Brihoshpoti ar Shoni dujonei charter oi diker pashe thake, ja kaj egonor puronon lokkhon.'],
  ['তখন বৃদ্ধির গ্রহ বৃহস্পতিও চার্টের ওই দিকের পাশে থাকে।', 'Tokhon briddhir groho Brihoshpoti-o charter oi diker pashe thake.'],
  ['তখন বৃহস্পতি আর শনির অবদান কম, তাই বেশিরভাগ কাজ করে জীবনচক্রই।', 'Tokhon Brihoshpoti ar Shonir obodan kom, tai beshirbhag kaj kore jibonchokroi.'],
  ['এটা দেরিতে আসে, কারণ এখনকার জীবনচক্র অন্য দিকে টানে: {now}।', 'Eta derite ase, karon ekhonkar jibonchokro onno dike tane: {now}.'],
  ['এর আগে {start} থেকে {end}-এর একটা বিকল্পও আছে; একটু হালকা, তবে কাজে লাগানো ভালো।', 'Er age {start} theke {end}-er ekta bikolpo-o ache; ektu halka, tobe kaje lagano bhalo.'],
  ['এখন {planetGen} অন্তর্দশা {end} পর্যন্ত চলছে; বড় পদক্ষেপের চেয়ে দক্ষতা আর প্রস্তুতির জন্য এটা ভালো।', 'Ekhon {planetGen} antordasha {end} porjonto cholchhe; boro podokkheper cheye dokkhota ar prostutir jonno eta bhalo.'],
  ['এ ছাড়া {start} থেকে {end} পর্যন্ত আপনার চার্ট {areaGen} জন্যও সক্রিয়।', 'E chhara {start} theke {end} porjonto apnar chart {areaGen} jonno-o sokriyo.'],
  ['যে {start} থেকে {end}-এর সময়ের কথা বললাম,', 'Je {start} theke {end}-er somoyer kotha bollam,'],
  ['আপনার চার্টে শুধু ভ্রমণ নয়, দীর্ঘদিন বিদেশে থাকার সত্যিকারের টান দেখা যায়।', 'Apnar charte shudhu bhromon noy, dirghodin bideshe thakar sotyikarer tan dekha jay.'],
  ['আপনার চার্ট বিদেশে চিরকালের জন্য থিতু হওয়ার চেয়ে কাজের সুযোগ আর ভ্রমণের দিকে বেশি টানে।', 'Apnar chart bideshe chirokaler jonno thitu hoyar cheye kajer shujog ar bhromoner dike beshi tane.'],
  ['আপনার চার্ট বিদেশ ভ্রমণ আর পড়াশোনার দিকে টানে, তবে দীর্ঘদিনের ঠিকানা বাড়ির কাছেই।', 'Apnar chart bidesh bhromon ar porashonar dike tane, tobe dirghodiner thikana barir kachhei.'],
  ['{a} আর {b}-এর মধ্যে আপনার চার্ট {pick}-এর দিকে টানে: {why}।', '{a} ar {b}-er moddhe apnar chart {pick}-er dike tane: {why}.'],
  ['{a} আর {b} দুটোকেই আপনার চার্ট প্রায় সমান সমর্থন করে, তাই নিজের আগ্রহ আর একটা ছোট অভিজ্ঞতা দিয়ে ঠিক করুন।', '{a} ar {b} dutokei apnar chart pray soman somorthon kore, tai nijer agroho ar ekta chhoto obhigyota diye thik korun.'],
  ['আপনার চার্ট {kind}-এর দিকে টানে: {why}।', 'Apnar chart {kind}-er dike tane: {why}.'],
  ['আপনার চার্টে পদ আর কাজের জন্য একটা সহায়ক যোগও আছে: {how}।', 'Apnar charte pod ar kajer jonno ekta sohayok jog-o ache: {how}.'],
  ['ধনের জন্যও একটা সহায়ক যোগ আছে: {how}।', 'Dhoner jonno-o ekta sohayok jog ache: {how}.'],
  ['আপনার চার্টের একটা সহায়ক যোগ এটাকে আরও বাড়ায়: {how}।', 'Apnar charter ekta sohayok jog etake aro baray: {how}.'],
  ['জ্ঞানের গ্রহ আপনার চাঁদের সঙ্গে জোরালোভাবে আছে, যা সমর্থন আর সুনামের লক্ষণ', 'gyaner groho apnar chander sathe joralobhabe ache, ja somorthon ar sunamer lokkhon'],
  ['{p} নিজের সেরা অবস্থায় একটা গুরুত্বপূর্ণ জায়গায় আছে, যা একটা স্বাভাবিক, জোরালো ধরন দেয়', '{p} nijer sera obosthay ekta gurutvopurno jaygay ache, ja ekta swabhabik, joralo dhoron dey'],
  ['আপনার পদ আর ভাগ্য চালানো গ্রহগুলো একসঙ্গে কাজ করে', 'apnar pod ar bhagyo chalano grohogulo ekshathe kaj kore'],
  ['আপনার আয় আর ভাগ্যের গ্রহগুলো পরস্পর যুক্ত', 'apnar aay ar bhagyer grohogulo poraspor jukto'],
  ['কষ্টগুলো চেষ্টার পরে উন্নতিতে বদলে যায়', 'koshtogulo cheshtar pore unnotite bodle jay'],
  ['আপনার জীবনের দুটো দিক একে অপরের পাশে ঘনিষ্ঠভাবে থাকে', 'apnar jiboner duto dik ek opor-er pashe ghonishthobhabe thake'],
  ['চার্টের একটা দুর্বল দিক নরম হয়ে যায়, আর চেষ্টায় শক্তি হয়ে উঠতে পারে', 'charter ekta durbol dik norom hoye jay, ar cheshtay shokti hoye uthte pare'],
  ['কমলা', 'komla'],
  ['সাদা', 'sada'],
  ['লাল', 'lal'],
  ['সবুজ', 'sobuj'],
  ['হলুদ', 'holud'],
  ['নীল', 'nil'],
  ['সূর্য', 'Surjo'],
  ['চাঁদ', 'Chand'],
  ['মঙ্গল', 'Mongol'],
  ['বুধ', 'Budh'],
  ['বৃহস্পতি', 'Brihoshpoti'],
  ['শুক্র', 'Shukro'],
  ['শনি', 'Shoni'],
  ['রাহু', 'Rahu'],
  ['কেতু', 'Ketu'],
  ['চুনি', 'chuni'],
  ['মুক্তো', 'mukto'],
  ['প্রবাল', 'probal'],
  ['পান্না', 'panna'],
  ['পোখরাজ', 'pokhraj'],
  ['হীরে', 'hire'],
  ['নীলা', 'nila'],
  ['গোমেদ', 'gomed'],
  ['বৈদূর্য', 'boidurjo'],
  ['নতুন কাজ শুরু করা', 'notun kaj shuru kora'],
  ['সই করা', 'shoi kora'],
  ['কেনাকাটা', 'kenakata'],
  ['যাত্রা', 'jatra'],
  ['খুব ভালো মিল', 'khub bhalo mil'],
  ['ভালো মিল', 'bhalo mil'],
  ['মাঝারি মিল', 'majhari mil'],
  ['কম গুণ', 'kom gun'],
  ['কাছাকাছি মূল্যবোধ', 'kachhakachhi mulyobodh'],
  ['একে অপরের অগ্রাধিকারকে সম্মান করা', 'ek opor-er ogradhikarke sommaan kora'],
  ['একে অপরের প্রতি স্বাভাবিক টান', 'ek opor-er proti swabhabik tan'],
  ['সিদ্ধান্তে সমান ভাগ', 'siddhante soman bhag'],
  ['একসঙ্গে ভালো ভাগ্য', 'ekshathe bhalo bhagyo'],
  ['কঠিন সময়ে ধৈর্য', 'kothin somoye dhoirjo'],
  ['রোজকার স্বচ্ছন্দ সঙ্গ', 'rojkar swachchhondo shongo'],
  ['রোজকার অভ্যাস আর স্বস্তি', 'rojkar obhyash ar swosti'],
  ['বন্ধুত্বপূর্ণ ভাবনা', 'bondhuttopurno bhabna'],
  ['একে অপরের দিক থেকে দেখা', 'ek opor-er dik theke dekha'],
  ['মেলানো স্বভাব', 'melano swobhab'],
  ['চাপের মধ্যে কথা বলা', 'chaper moddhe kotha bola'],
  ['একে অপরের সহায়ক চন্দ্ররাশি', 'ek opor-er sohayok chondrorashi'],
  ['টাকা আর পরিবারের পরিকল্পনা', 'taka ar paribarer porikolpona'],
  ['আবেগের সুস্থ ছন্দ', 'abeger sustho chhondo'],
  ['একে অপরকে জায়গা দেওয়া', 'ek oporke jayga deoa'],
  ['কর্তৃত্বের গ্রহ', 'kortritter groho'],
  ['মনের গ্রহ', 'moner groho'],
  ['শক্তির গ্রহ', 'shoktir groho'],
  ['বুদ্ধির গ্রহ', 'buddhir groho'],
  ['বৃদ্ধির গ্রহ', 'briddhir groho'],
  ['প্রেম আর স্বাচ্ছন্দ্যের গ্রহ', 'prem ar swachchhondyer groho'],
  ['শৃঙ্খলার গ্রহ', 'shrinkholar groho'],
  ['উচ্চাকাঙ্ক্ষার বিন্দু', 'uchchakankkhar bindu'],
  ['মনোযোগ আর গভীরতার বিন্দু', 'monojog ar gobhirotar bindu'],
  ['এটা আপনার {area} দিকটা চালায়', 'eta apnar {area} dikta chalay'],
  ['এটা আছে আপনার {area} দিকে', 'eta ache apnar {area} dike'],
  ['আপনাদের দুজনের কুষ্ঠিতে প্রথাগত নিয়মে তা কেটে যায়', 'apnader dujoner kushtite prothagoto niyome ta kete jay'],
  ['কাগজে এটা আছে, তবে এটা আটটার মধ্যে একটা দিক, আর স্বাস্থ্য বা সন্তান নিয়ে নিশ্চিত কিছু বলে না', 'kagoje eta ache, tobe eta athtar moddhe ekta dik, ar shasthyo ba santan niye nishchit kichhu bole na'],
  ['আপনাদের কুষ্ঠিতে নাড়ি দোষ নেই', 'apnader kushtite nari dosh nei'],
  ['মঙ্গল নিজের রাশিতে আছে', 'Mongol nijer rashite ache'],
  ['মঙ্গল উচ্চস্থ', 'Mongol uchchostho'],
  ['সেই রাশির প্রথাগত ব্যতিক্রম খাটে', 'sei rashir prothagoto byatikrom khate'],
  ['বৃহস্পতি সেই অবস্থানকে রক্ষা করে', 'Brihoshpoti sei obosthanke rokkha kore'],
  ['প্রথম', 'prothom'],
  ['মাঝের (সবচেয়ে ভারী)', 'majher (sobcheye bhari)'],
  ['শেষ', 'shesh'],
  ['কর্তৃত্ব আর অহং', 'kortritto ar ohong'],
  ['আবেগ আর যত্ন', 'abeg ar jotno'],
  ['শক্তি আর উদ্যম', 'shokti ar udyom'],
  ['ভাবনা আর কথা', 'bhabna ar kotha'],
  ['বৃদ্ধি আর বোধ', 'briddhi ar bodh'],
  ['স্বাচ্ছন্দ্য আর আকর্ষণ', 'swachchhondyo ar akorshon'],
  ['দায়িত্ব আর ধৈর্য', 'dayitto ar dhoirjo'],
  ['প্রবল আকাঙ্ক্ষা আর অন্যরকম পথ', 'probol akankkha ar onnorokom poth'],
  ['নির্লিপ্ততা আর গভীরতা', 'nirliptota ar gobhirota'],
  ['একে সচেতনভাবে সামলাতে হয়, এটা কোনো অশুভ লক্ষণ নয়।', 'eke sochetonbhabe samlate hoy, eta kono oshubho lokkhon noy.'],
  ['আর হ্যাঁ, আপনার চার্টে সত্যিই এটা ওখানে আছে।', 'Ar hyan, apnar charte sotyii eta okhane ache.'],
  ['তবে আপনার নিজের চার্টে এটা অন্য জায়গায়, তাই এটা সাধারণ কথা।', 'Tobe apnar nijer charte eta onno jaygay, tai eta sadharon kotha.'],
  ['পথের কথা বললে, আপনার চার্ট বেশি টানে এই দিকে: {label}, কারণ {why}।', 'Pother kotha bolle, apnar chart beshi tane ei dike: {label}, karon {why}.'],
  ['আপনার টাকা সবচেয়ে সহজে আসে {items} থেকে।', 'Apnar taka sobcheye sohoje ase {items} theke.'],
  ['চার্টে এখন যা দেখা যায়: {items}। এটা একটা পর্ব, শেষ নয়।', 'Charte ekhon ja dekha jay: {items}. Eta ekta porbo, shesh noy.'],
  ['এর মধ্যে দেখা যায়: {items}।', 'Er moddhe dekha jay: {items}.'],
  ['{who} সঙ্গে আপনার চার্টে দেখা যায়: {items}।', '{who} sathe apnar charte dekha jay: {items}.'],
  ['এর কিছুটা এখনকার পর্বের জন্য: {why}।', 'Er kichhuta ekhonkar porber jonno: {why}.'],
  ['এই বিষয়', 'ei bishoy'],
  ['জোরালো, সহায়ক', 'joralo, sohayok'],
  ['ভালো সম্ভাবনার সহায়ক', 'bhalo sombhabonar sohayok'],
  ['আপনার সুস্থতার জন্য সবচেয়ে কাজের অভ্যাস হলো {items}।', 'Apnar susthotar jonno sobcheye kajer obhyash holo {items}.'],
  ['এখন আপনি এই পর্বে আছেন: {items}।', 'Ekhon apni ei porbe achhen: {items}.'],
  ['এটা যদি ওঁর নিজের বিষয় হয়, ওঁর জন্মের তথ্য প্রোফাইলে যোগ করলে ওঁর কুষ্ঠি সরাসরি দেখতে পারব।', 'Eta jodi onar nijer bishoy hoy, onar jonmer tottho profile-e jog korle onar kushti sorasori dekhte parbo.'],
  ['{p} অন্তর্দশা চলে {e} পর্যন্ত', '{p} antordasha chole {e} porjonto'],
  ['আইটি', 'IT'],
  ['ফিনান্স', 'finance'],
  ['শিক্ষকতা', 'shikkhokota'],
  ['কর্পোরেট কাজ', 'corporate kaj'],
  ['ইঞ্জিনিয়ারিং', 'engineering'],
  ['ডিজাইন', 'design'],
  ['ডাক্তারি', 'daktari'],
  ['সরকারি চাকরি', 'sorkari chakri'],
  ['সেলস', 'sales'],
  ['বেসরকারি চাকরি', 'besorkari chakri'],
  ['এমবিএ', 'MBA'],
  ['এমএস', 'MS'],
  ['বিজ্ঞান', 'biggan'],
  ['কমার্স', 'commerce'],
  ['ধ্যান', 'dhyan'],
  ['ভক্তি', 'bhokti'],
  ['ভাইয়ের', 'bhaiyer'],
  ['বোনের', 'boner'],
  ['বাবার', 'babar'],
  ['মায়ের', 'mayer'],
  ['বাবা-মায়ের', 'baba-mayer'],
  ['ভাইবোনের', 'bhaiboner'],
  ['শ্বশুরবাড়ির', 'shoshurbarir'],
  ['বাড়ির লোকের', 'barir loker'],
  ['নেতৃত্ব আর কর্তৃত্বের গ্রহ', 'netritto ar kortritter groho'],
  ['যত্ন আর আবেগের গ্রহ', 'jotno ar abeger groho'],
  ['শক্তি আর সাহসের গ্রহ', 'shokti ar shahosher groho'],
  ['বুদ্ধি আর যোগাযোগের গ্রহ', 'buddhi ar jogajoger groho'],
  ['জ্ঞান আর বৃদ্ধির গ্রহ', 'gyan ar briddhir groho'],
  ['সৌন্দর্য আর সৃজনশীলতার গ্রহ', 'soundorjo ar srijonshilotar groho'],
  ['শৃঙ্খলা আর পরিশ্রমের গ্রহ', 'shrinkhola ar porishromer groho'],
  ['উচ্চাকাঙ্ক্ষা আর নতুন পথের বিন্দু', 'uchchakankkha ar notun pother bindu'],
  ['সূক্ষ্ম নবাংশ চার্টে আপনার কাজের দিকটা চালায় {p}', 'sukkhmo nobangsho charte apnar kajer dikta chalay {p}'],
  ['আপনার কেরিয়ার চার্টে কাজের দায়িত্ব {p}-এর হাতে', 'apnar career charte kajer dayitto {p}-er hate'],
  ['আপনার সূর্য থেকে গুনলেও আপনার {area} দিকটা চালায় {p}', 'apnar surjo theke gunleo apnar {area} dikta chalay {p}'],
  ['আপনার চাঁদ থেকে গুনলেও আপনার {area} দিকটা চালায় {p}', 'apnar chand theke gunleo apnar {area} dikta chalay {p}'],
  ['আপনার চার্টে সঙ্গীর ইঙ্গিত দেয় {p}', 'apnar charte shongir ingit dey {p}'],
  ['বিয়ের চার্টও {p}-এর দিকে ইঙ্গিত করে', 'biyer chart-o {p}-er dike ingit kore'],
  ['চার্টের একটা সূক্ষ্ম ভাগও {p}-এর দিকে ইঙ্গিত করে', 'charter ekta sukkhmo bhag-o {p}-er dike ingit kore'],
  ['{p} আপনার চার্টের একটা সহায়ক যোগের অংশ', '{p} apnar charter ekta sohayok joger ongsho'],
  ['আপনার {area} দিকটা চালায় {p}', 'apnar {area} dikta chalay {p}'],
  ['{pg} নজর আছে আপনার {area} দিকে', '{pg} nojor ache apnar {area} dike'],
  ['{p} আছে আপনার {area} দিক চালানো গ্রহের সঙ্গে', '{p} ache apnar {area} dik chalano grohor sathe'],
  ['আপনার চার্টে কাজের দিশা দেখায় {p}', 'apnar charte kajer disha dekhay {p}'],
  ['{p} আপনার চার্টে জোরালো', '{p} apnar charte joralo'],
  ['{p} স্বভাবতই জীবনের এই দিকের সঙ্গে জড়িত', '{p} swobhabotoi jiboner ei diker sathe jorito'],
  ['সরকারি ও নেতৃত্বের কাজ', 'sorkari o netritter kaj'],
  ['সরকারি, প্রশাসন আর নেতৃত্বের কাজ', 'sorkari, proshashon ar netritter kaj'],
  ['সিভিল সার্ভিস, সরকারি দপ্তর, টিম লিড বা ম্যানেজার, নীতি-সংক্রান্ত কাজ', 'civil service, sorkari doptor, team lead ba manager, niti-songkranto kaj'],
  ['সিভিল সার্ভিস', 'civil service'],
  ['সরকারি দপ্তর', 'sorkari doptor'],
  ['টিম লিড বা ম্যানেজার', 'team lead ba manager'],
  ['নীতি-সংক্রান্ত কাজ', 'niti-songkranto kaj'],
  ['সেবা ও মানুষের সঙ্গে কাজ', 'seba o manusher sathe kaj'],
  ['যত্ন, আতিথেয়তা আর মানুষের সঙ্গে কাজ', 'jotno, atitheyota ar manusher sathe kaj'],
  ['স্বাস্থ্যসেবা, হোটেল ও পর্যটন, কাস্টমার সার্ভিস, এইচআর', 'swasthyoseba, hotel o porjoton, customer service, HR'],
  ['স্বাস্থ্যসেবা', 'swasthyoseba'],
  ['হোটেল ও পর্যটন', 'hotel o porjoton'],
  ['কাস্টমার সার্ভিস', 'customer service'],
  ['এইচআর', 'HR'],
  ['ইঞ্জিনিয়ারিং ও কারিগরি কাজ', 'engineering o karigori kaj'],
  ['ইঞ্জিনিয়ারিং, কারিগরি আর উদ্যমের কাজ', 'engineering, karigori ar udyomer kaj'],
  ['মেকানিক্যাল বা সিভিল ইঞ্জিনিয়ারিং, প্রতিরক্ষা বা পুলিশ, সার্জারি, খেলা, রিয়েল এস্টেট', 'mechanical ba civil engineering, protirokkha ba police, surgery, khela, real estate'],
  ['মেকানিক্যাল বা সিভিল ইঞ্জিনিয়ারিং', 'mechanical ba civil engineering'],
  ['প্রতিরক্ষা বা পুলিশ', 'protirokkha ba police'],
  ['সার্জারি', 'surgery'],
  ['খেলা', 'khela'],
  ['রিয়েল এস্টেট', 'real estate'],
  ['প্রযুক্তি ও ডেটা', 'projukti o data'],
  ['প্রযুক্তি, ডেটা আর যোগাযোগের কাজ', 'projukti, data ar jogajoger kaj'],
  ['সফটওয়্যার, ডেটা বিশ্লেষণ, লেখালেখি ও কনটেন্ট, সেলস, হিসাবরক্ষণ', 'software, data bishleshon, lekhalekhi o content, sales, hisabrokkhon'],
  ['সফটওয়্যার', 'software'],
  ['ডেটা বিশ্লেষণ', 'data bishleshon'],
  ['লেখালেখি ও কনটেন্ট', 'lekhalekhi o content'],
  ['হিসাবরক্ষণ', 'hisabrokkhon'],
  ['পরামর্শ ও ফিনান্সের কাজ', 'poramorsho o finance-er kaj'],
  ['শিক্ষা, আইন, অর্থ আর পরামর্শের কাজ', 'shikkha, ain, ortho ar poramorshor kaj'],
  ['শিক্ষকতা বা ট্রেনিং, আইন, ব্যাংকিং ও ফিনান্স, কনসাল্টিং, কাউন্সেলিং', 'shikkhokota ba training, ain, banking o finance, consulting, counselling'],
  ['শিক্ষকতা বা ট্রেনিং', 'shikkhokota ba training'],
  ['আইন', 'ain'],
  ['ব্যাংকিং ও ফিনান্স', 'banking o finance'],
  ['কনসাল্টিং', 'consulting'],
  ['কাউন্সেলিং', 'counselling'],
  ['ডিজাইন ও সৃজনশীল মিডিয়া', 'design o srijonshil media'],
  ['ডিজাইন, শিল্প, মিডিয়া আর সৃজনশীল কাজ', 'design, shilpo, media ar srijonshil kaj'],
  ['UI/UX বা প্রোডাক্ট ডিজাইন, গ্রাফিক ডিজাইন, মিডিয়া ও মার্কেটিং, ফ্যাশন', 'UI/UX ba product design, graphic design, media o marketing, fashion'],
  ['UI/UX বা প্রোডাক্ট ডিজাইন', 'UI/UX ba product design'],
  ['গ্রাফিক ডিজাইন', 'graphic design'],
  ['মিডিয়া ও মার্কেটিং', 'media o marketing'],
  ['ফ্যাশন', 'fashion'],
  ['পরিচালনা ও সিস্টেমের কাজ', 'porichalona o system-er kaj'],
  ['পরিচালনা, সিস্টেম আর দীর্ঘমেয়াদি গোছানো কাজ', 'porichalona, system ar dirghomeyadi gochhano kaj'],
  ['পরিচালনা ও প্রজেক্ট ম্যানেজমেন্ট, ইনফ্রাস্ট্রাকচার বা ব্যাকএন্ড ইঞ্জিনিয়ারিং, উৎপাদন শিল্প, সরকারি পরিষেবা, গবেষণা', 'porichalona o project management, infrastructure ba backend engineering, utpadon shilpo, sorkari porisheba, gobeshona'],
  ['পরিচালনা ও প্রজেক্ট ম্যানেজমেন্ট', 'porichalona o project management'],
  ['ইনফ্রাস্ট্রাকচার বা ব্যাকএন্ড ইঞ্জিনিয়ারিং', 'infrastructure ba backend engineering'],
  ['উৎপাদন শিল্প', 'utpadon shilpo'],
  ['সরকারি পরিষেবা', 'sorkari porisheba'],
  ['গবেষণা', 'gobeshona'],
  ['নতুন প্রযুক্তি ও এআই', 'notun projukti o AI'],
  ['নতুন প্রযুক্তি, এআই, বিদেশি সংস্থা আর আলাদা পথ', 'notun projukti, AI, bideshi songstha ar alada poth'],
  ['এআই ও নতুন প্রযুক্তি, স্টার্টআপ, বিদেশি বা বহুজাতিক সংস্থা, ডিজিটাল মিডিয়া', 'AI o notun projukti, startup, bideshi ba bohujatik songstha, digital media'],
  ['এআই ও নতুন প্রযুক্তি', 'AI o notun projukti'],
  ['স্টার্টআপ', 'startup'],
  ['বিদেশি বা বহুজাতিক সংস্থা', 'bideshi ba bohujatik songstha'],
  ['ডিজিটাল মিডিয়া', 'digital media'],
  ['গবেষণা ও বিশেষ কারিগরি কাজ', 'gobeshona o bishesh karigori kaj'],
  ['গবেষণা, কোডিং আর বিশেষ কারিগরি কাজ', 'gobeshona, coding ar bishesh karigori kaj'],
  ['গবেষণা, কোডিং, ডেটা সায়েন্স, নির্দিষ্ট প্রযুক্তিতে দক্ষতা', 'gobeshona, coding, data science, nirdishto projuktite dokkhota'],
  ['কোডিং', 'coding'],
  ['ডেটা সায়েন্স', 'data science'],
  ['নির্দিষ্ট প্রযুক্তিতে দক্ষতা', 'nirdishto projuktite dokkhota'],
  ['আত্মবিশ্বাসী, নীতিবান আর নেতৃত্ব দিতে পারেন এমন', 'attobishshashi, nitiban ar netritto dite paren emon'],
  ['যত্নশীল, আবেগপ্রবণ আর পরিবারমুখী', 'jotnoshil, abegprobon ar paribarmukhi'],
  ['উদ্যমী, স্পষ্টবাদী আর আগলে রাখার মতো', 'udyomi, sposhtobadi ar agle rakhar moto'],
  ['রসিক, কথা বলতে ভালোবাসেন আর বুদ্ধিমান', 'roshik, kotha bolte bhalobashen ar buddhiman'],
  ['জ্ঞানী, দয়ালু আর শিক্ষিত', 'gyani, doyalu ar shikkhito'],
  ['আকর্ষণীয়, শিল্পমনা আর স্নেহময়', 'akorshoniyo, shilpomona ar snehomoy'],
  ['পরিণত, দায়িত্বশীল আর বিশ্বস্ত, হয়তো বয়সে একটু বড়', 'porinoto, dayittoshil ar bishshosto, hoyto boyoshe ektu boro'],
  ['উচ্চাকাঙ্ক্ষী আর আলাদা ধরনের, হয়তো ভিন্ন পরিবেশ থেকে', 'uchchakankkhi ar alada dhoroner, hoyto bhinno poribesh theke'],
  ['চাপা স্বভাবের, আধ্যাত্মিক আর স্বাধীনচেতা', 'chapa swobhaber, adhyatmik ar swadhincheta'],
  ['সম্ভবত প্রথম পা আপনিই বাড়াবেন', 'sombhoboto prothom pa apnii barben'],
  ['পরিবারের মাধ্যমে', 'paribarer madhyome'],
  ['বন্ধু, ভাইবোন বা সোশ্যাল মিডিয়ার মাধ্যমে', 'bondhu, bhaibon ba social media-r madhyome'],
  ['বাড়ির কাছেই, পরিবারের চেনাজানার মধ্যে', 'barir kachhei, paribarer chenajanar moddhe'],
  ['প্রেম, পড়াশোনা বা কোনো শখের সূত্রে', 'prem, porashona ba kono shokher sutre'],
  ['কাজের জায়গায় বা সেবার সূত্রে', 'kajer jaygay ba sebar sutre'],
  ['সম্বন্ধ বা কোনো অংশীদারির সূত্রে', 'sombondho ba kono ongshidarir sutre'],
  ['হঠাৎ, অপ্রত্যাশিত ভাবে', 'hothat, oprottashito bhabe'],
  ['ভ্রমণ, শিক্ষক বা পড়াশোনার জায়গার সূত্রে', 'bhromon, shikkhok ba porashonar jaygar sutre'],
  ['কাজ বা কেরিয়ারের পরিচিতির মধ্যে', 'kaj ba careerer porichitir moddhe'],
  ['বন্ধু আর চেনাজানার বড় বৃত্তের মাধ্যমে', 'bondhu ar chenajanar boro britter madhyome'],
  ['বাড়ি থেকে দূরে, বিদেশে বা অনলাইনে', 'bari theke dure, bideshe ba online-e'],
  ['স্থির বেতন, সরকারি কাজ বা উঁচু পদ', 'sthir beton, sorkari kaj ba unchu pod'],
  ['মানুষের সঙ্গে কাজ, খাবার, হোটেল বা রোজকার জিনিস', 'manusher sathe kaj, khabar, hotel ba rojkar jinish'],
  ['সম্পত্তি, ইঞ্জিনিয়ারিং বা হাতে-কলমে কারিগরি দক্ষতা', 'sompotti, engineering ba hate-kolome karigori dokkhota'],
  ['দক্ষতা, ব্যবসা-বাণিজ্য, ফ্রিল্যান্সিং আর কমিশন', 'dokkhota, byabsa-banijyo, freelancing ar commission'],
  ['পরামর্শ, শিক্ষকতা, ফিনান্স আর দীর্ঘমেয়াদি বিনিয়োগ', 'poramorsho, shikkhokota, finance ar dirghomeyadi biniyog'],
  ['সৃজনশীল কাজ, ডিজাইন, সৌন্দর্য, শৌখিন জিনিস বা শিল্প', 'srijonshil kaj, design, soundorjo, shoukhin jinish ba shilpo'],
  ['দীর্ঘদিনের স্থির কাজ আর ধৈর্য ধরে সঞ্চয়', 'dirghodiner sthir kaj ar dhoirjo dhore sonchoy'],
  ['প্রযুক্তি, বিদেশি উৎস বা নতুন যুগের কাজ (ফাটকা এড়িয়ে চলুন)', 'projukti, bideshi utso ba notun juger kaj (phatka eriye cholun)'],
  ['বিশেষ দক্ষতা বা গবেষণা, আর মাঝে মাঝে হঠাৎ লাভ', 'bishesh dokkhota ba gobeshona, ar majhe majhe hothat labh'],
  ['রাষ্ট্রবিজ্ঞান, জনপ্রশাসন বা ম্যানেজমেন্ট', 'rashtrobiggan, jonoproshashon ba management'],
  ['রাষ্ট্রবিজ্ঞান বা ম্যানেজমেন্ট', 'rashtrobiggan ba management'],
  ['মনোবিজ্ঞান, নার্সিং, হোটেল ম্যানেজমেন্ট বা খাদ্যবিজ্ঞান', 'monobiggan, nursing, hotel management ba khaddobiggan'],
  ['মনোবিজ্ঞান, নার্সিং বা হোটেল ম্যানেজমেন্ট', 'monobiggan, nursing ba hotel management'],
  ['ইঞ্জিনিয়ারিং, ডাক্তারি বা স্পোর্টস সায়েন্স', 'engineering, daktari ba sports science'],
  ['ইঞ্জিনিয়ারিং বা ডাক্তারি', 'engineering ba daktari'],
  ['কম্পিউটার সায়েন্স, গণিত, কমার্স, ভাষা বা সাংবাদিকতা', 'computer science, gonit, commerce, bhasha ba sangbadikota'],
  ['কম্পিউটার সায়েন্স, গণিত বা কমার্স', 'computer science, gonit ba commerce'],
  ['আইন, ফিনান্স, শিক্ষা, ম্যানেজমেন্ট বা দর্শন', 'ain, finance, shikkha, management ba dorshon'],
  ['আইন, ফিনান্স বা শিক্ষা', 'ain, finance ba shikkha'],
  ['ডিজাইন, চারুকলা, সঙ্গীত, ফ্যাশন বা স্থাপত্য', 'design, charukola, songit, fashion ba sthapotyo'],
  ['ডিজাইন, চারুকলা বা স্থাপত্য', 'design, charukola ba sthapotyo'],
  ['সিভিল বা মেকানিক্যাল ইঞ্জিনিয়ারিং, ভূতত্ত্ব, গবেষণা বা জনপ্রশাসন', 'civil ba mechanical engineering, bhutottwo, gobeshona ba jonoproshashon'],
  ['সিভিল ইঞ্জিনিয়ারিং বা গবেষণা', 'civil engineering ba gobeshona'],
  ['কম্পিউটার সায়েন্স ও এআই, বিদেশি ভাষা, এভিয়েশন বা মিডিয়া', 'computer science o AI, bideshi bhasha, aviation ba media'],
  ['কম্পিউটার সায়েন্স ও এআই, বা মিডিয়া', 'computer science o AI, ba media'],
  ['গবেষণা, গণিত, কোডিং বা জীববিজ্ঞান', 'gobeshona, gonit, coding ba jibbiggan'],
  ['গবেষণা, কোডিং বা জীববিজ্ঞান', 'gobeshona, coding ba jibbiggan'],
  ['নেতৃত্ব আর আত্মবিশ্বাস', 'netritto ar attobishshash'],
  ['অহং; মাঝে মাঝে অন্যদের এগোতে দিন', 'ohong; majhe majhe onnoder egote din'],
  ['সহমর্মিতা আর মানুষের প্রতি যত্ন', 'sohomormita ar manusher proti jotno'],
  ['মেজাজের ওঠানামা; বিশ্রামের যত্ন নিন', 'mejajer othanama; bishramer jotno nin'],
  ['সাহস আর উদ্যম', 'shahosh ar udyom'],
  ['অধৈর্য আর হঠাৎ রাগ', 'odhoirjo ar hothat rag'],
  ['দ্রুত চিন্তা আর কথা বলার দক্ষতা', 'druto chinta ar kotha bolar dokkhota'],
  ['অতিরিক্ত ভাবনা', 'otirikto bhabna'],
  ['জ্ঞান আর অন্যকে পথ দেখানোর গুণ', 'gyan ar onnoke poth dekhanor gun'],
  ['বেশি প্রতিশ্রুতি দিয়ে ফেলা', 'beshi protishruti diye phela'],
  ['রুচি, আকর্ষণ আর মিলিয়ে চলার গুণ', 'ruchi, akorshon ar miliye cholar gun'],
  ['আরামের প্রতি বেশি টান', 'aramer proti beshi tan'],
  ['শৃঙ্খলা, ধৈর্য আর লেগে থাকার শক্তি', 'shrinkhola, dhoirjo ar lege thakar shokti'],
  ['নিজের ওপর সন্দেহ আর কাজ ফেলে রাখা', 'nijer opor sondeho ar kaj phele rakha'],
  ['উচ্চাকাঙ্ক্ষা আর নতুন ভাবনা', 'uchchakankkha ar notun bhabna'],
  ['অস্থিরতা', 'osthirota'],
  ['মনোযোগ, গভীরতা আর অন্তর্দৃষ্টি', 'monojog, gobhirota ar ontordrishti'],
  ['দূরে সরে থাকা; মানুষের সঙ্গে যুক্ত থাকুন', 'dure sore thaka; manusher sathe jukto thakun'],
  ['সকালের রোদ, নিয়ম করে ওঠা আর হৃদয় ও চোখের যত্ন', 'sokaler rod, niyom kore otha ar hridoy o chokher jotno'],
  ['ভালো ঘুম, যথেষ্ট জল আর মনের বিশ্রাম', 'bhalo ghum, jotheshto jol ar moner bishram'],
  ['চাপ কমাতে নিয়মিত ব্যায়াম, আর চোট থেকে সাবধান', 'chap komate niyomito byayam, ar chot theke sabdhan'],
  ['স্ক্রিন থেকে বিরতি, শ্বাসের ব্যায়াম আর স্নায়ুর বিশ্রাম', 'screen theke birati, shwasher byayam ar snayur bishram'],
  ['হালকা খাবার আর ওজন ও সুগারের দিকে নজর', 'halka khabar ar ojon o sugarer dike nojor'],
  ['সুষম খাবার, কম মিষ্টি আর যথেষ্ট জল', 'sushom khabar, kom mishti ar jotheshto jol'],
  ['স্ট্রেচিং, উষ্ণতা আর নিয়মিত রুটিন, হাড় আর গাঁটের জন্য', 'stretching, ushnota ar niyomito routine, har ar ganter jonno'],
  ['নির্দিষ্ট রুটিন আর কম স্ক্রিন টাইম, যাতে অস্থিরতা কমে', 'nirdishto routine ar kom screen time, jate osthirota kome'],
  ['সাদামাটা খাবার, হজমের যত্ন আর নিয়মিত চেকআপ', 'sadamata khabar, hojomer jotno ar niyomito checkup'],
  ['রাজধানী বা প্রশাসনিক শহর', 'rajdhani ba proshashonik shohor'],
  ['জল বা সমুদ্রের কাছের জায়গা', 'jol ba samudrer kachher jayga'],
  ['ব্যস্ত শিল্প বা টেক শহর', 'byasto shilpo ba tech shohor'],
  ['বাণিজ্যিক শহর', 'banijjik shohor'],
  ['শিক্ষা আর সংস্কৃতির শহর', 'shikkha ar sangskritir shohor'],
  ['প্রাণবন্ত, সৃজনশীল আর খোলামেলা শহর', 'pranobonto, srijonshil ar kholamela shohor'],
  ['পুরনো, শান্ত বা শিল্প শহর', 'puronon, shanto ba shilpo shohor'],
  ['বড় আন্তর্জাতিক শহর', 'boro antorjatik shohor'],
  ['শান্ত, ছোট জায়গা', 'shanto, chhoto jayga'],
  ['বিদেশে থাকা বা কাজ করা', 'bideshe thaka ba kaj kora'],
  ['নিজের এলাকার কাছেই জীবন গড়া', 'nijer elakar kachhei jibon gora'],
  ['বিদেশে কাজের সুযোগ বা ভ্রমণ, তবে শিকড় বাড়িতেই', 'bideshe kajer shujog ba bhromon, tobe shikor barite-i'],
  ['আপনার অংশীদারি আর পরিশ্রমের দিক জোরালো, আর বাণিজ্যের গ্রহ তাদের পাশে আছে', 'apnar ongshidari ar porishromer dik joralo, ar banijyer groho tader pashe ache'],
  ['আপনার রোজকার কাজ আর কেরিয়ারের দিক ব্যবসার দিকের চেয়ে বেশি স্থির', 'apnar rojkar kaj ar careerer dik byabsar diker cheye beshi sthir'],
  ['আপনার কেরিয়ার আর ব্যবসার দিক প্রায় সমান জোরালো', 'apnar career ar byabsar dik pray soman joralo'],
  ['নিজের ব্যবসা বা স্বাধীন কাজ', 'nijer byabsa ba swadhin kaj'],
  ['চাকরি, কোনো প্রতিষ্ঠানে স্থির উন্নতির সঙ্গে', 'chakri, kono protishthane sthir unnotir sathe'],
  ['আগে চাকরি, সঙ্গে ধীরে ধীরে বাড়ানো একটা পাশের ব্যবসা', 'age chakri, sathe dhire dhire barano ekta pasher byabsa'],
  ['অহং আর ভিন্ন মূল্যবোধ, যেখানে সময়ের সঙ্গে সম্মান বাড়ে', 'ohong ar bhinno mulyobodh, jekhane somoyer sathe sommaan bare'],
  ['গভীর যত্ন, তবে আবেগের কিছু ওঠানামা', 'gobhir jotno, tobe abeger kichhu othanama'],
  ['তাড়াতাড়ি রাগ আর জোরালো মত, তবে ভেতরে সত্যিকারের টান', 'taratari rag ar joralo mot, tobe bhetore sotyikarer tan'],
  ['অনেক কথা আর তর্ক, যেখানে স্পষ্ট কথাই বেশিরভাগ মিটিয়ে দেয়', 'onek kotha ar torko, jekhane sposhto kothai beshirbhag mitiye dey'],
  ['আন্তরিকতা, পথ দেখানো আর সত্যিকারের ভরসা', 'antorikota, poth dekhano ar sotyikarer bhorsha'],
  ['স্নেহ আর মিলেমিশে থাকার ইচ্ছে', 'sneho ar milemishe thakar ichchhe'],
  ['দায়িত্ব আর খানিক দূরত্ব, কোনো স্থায়ী ফাটল নয়', 'dayitto ar khanik durotto, kono sthayi phatol noy'],
  ['মিশ্র ইঙ্গিত আর অস্থিরতা, যা সততায় শান্ত হয়', 'mishro ingit ar osthirota, ja sototay shanto hoy'],
  ['খানিকটা মনের দূরত্ব, যেখানে একে অপরকে জায়গা দেওয়া কাজে দেয়', 'khanikta moner durotto, jekhane ek oporke jayga deoa kaje dey'],
  ['বাড়ির', 'barir'],
  ['নিজের উদাহরণে পথ দেখানো আর নীতিতে চলা', 'nijer udahorone poth dekhano ar nitite chola'],
  ['সকালের রোদে কয়েক মুহূর্ত শান্ত থেকে দিনের সংকল্প করা', 'sokaler rode koek muhurto shanto theke diner songkolpo kora'],
  ['ভক্তি আর অন্যের যত্ন', 'bhokti ar onner jotno'],
  ['প্রতিদিন সকালে কয়েক মিনিট প্রার্থনা, গান বা জপ', 'protidin sokale koek minute prarthona, gan ba jop'],
  ['নিয়মিত অনুশীলন আর সাহস', 'niyomito onushilon ar shahosh'],
  ['রোজ একই সময়ে যোগ বা হাঁটা, সাধনার মতো করে', 'roj ekoi somoye jog ba hanta, sadhonar moto kore'],
  ['শেখা, লেখা আর শেখানো', 'shekha, lekha ar shekhano'],
  ['প্রতি রাতে দশ মিনিট ডায়েরি লেখা', 'proti rate dosh minute diary lekha'],
  ['জ্ঞান আর বোধ ভাগ করে নেওয়া', 'gyan ar bodh bhag kore neoa'],
  ['রোজ কোনো ভালো বইয়ের কয়েক লাইন পড়া আর শেখা কথা ভাগ করা', 'roj kono bhalo boier koek line pora ar shekha kotha bhag kora'],
  ['সৌন্দর্য, গান আর শিল্পের মধ্য দিয়ে ভক্তি', 'soundorjo, gan ar shilper moddho diye bhokti'],
  ['গান, সংগীত বা শান্ত সময়ের জন্য একটা ছোট পরিচ্ছন্ন জায়গা রাখা', 'gan, songit ba shanto somoyer jonno ekta chhoto porichchhonno jayga rakha'],
  ['সেবা আর নিয়মিত, সৎ কাজ', 'seba ar niyomito, sot kaj'],
  ['প্রতিদিন দশ মিনিট শান্ত থাকা আর একটা সেবার কাজ', 'protidin dosh minute shanto thaka ar ekta sebar kaj'],
  ['খোলা মনে নতুন পথ আর ভাবনা খোঁজা', 'khola mone notun poth ar bhabna khoja'],
  ['একটা অনুশীলন পুরো এক মাস করে দেখা, তারপর বিচার করা', 'ekta onushilon puro ek mash kore dekha, tarpor bichar kora'],
  ['ধ্যান আর ভেতরের শান্তি', 'dhyan ar bhetorer shanti'],
  ['সকালে বা রাতে দশ মিনিট চুপচাপ বসা', 'sokale ba rate dosh minute chupchap bosa'],
  ['ভোরে উঠে সকালের রোদে বসা, বাবা আর গুরুজনদের সম্মান করা, আর চাইলে গায়ত্রী মন্ত্র বা আদিত্য হৃদয়', 'bhore uthe sokaler rode bosa, baba ar gurujonder sommaan kora, ar chaile Gayatri mantra ba Aditya Hridoy'],
  ['ভোরে ওঠা, সকালের রোদ নেওয়া আর প্রতি সপ্তাহে কোনো বয়স্ক মানুষকে সাহায্য করা', 'bhore otha, sokaler rod neoa ar proti soptahe kono boyosko manushke sahajjo kora'],
  ['নিয়মিত ঘুম, জলের কাছে কিছুটা সময়, মায়ের সঙ্গে কথা বলা, আর চাইলে শিবের প্রার্থনা; কোনো দরকারি মানুষকে জল বা দুধ দেওয়া', 'niyomito ghum, joler kachhe kichhuta somoy, mayer sathe kotha bola, ar chaile Shiber prarthona; kono dorkari manushke jol ba dudh deoa'],
  ['নিয়মিত ঘুম, জলের কাছে সময় আর মায়ের সঙ্গে কথা বলা', 'niyomito ghum, joler kachhe somoy ar mayer sathe kotha bola'],
  ['রোজ ব্যায়াম, রাগকে খেলায় বদলানো, ভাইবোনদের সাহায্য, আর চাইলে হনুমান চালিসা', 'roj byayam, ragke khelay bodlano, bhaibondor sahajjo, ar chaile Hanuman Chalisa'],
  ['রোজ ব্যায়াম, শক্তির জন্য কোনো খেলা আর ভাইবোনদের সাহায্য', 'roj byayam, shoktir jonno kono khela ar bhaibondor sahajjo'],
  ['রোজ কিছু শেখা, হিসেব পরিষ্কার রাখা, ছাত্রছাত্রীদের সাহায্য, আর চাইলে বিষ্ণু সহস্রনাম', 'roj kichhu shekha, hiseb porishkar rakha, chhatrochhatrider sahajjo, ar chaile Bishnu Sohosronam'],
  ['রোজ কিছু শেখা, হিসেব পরিষ্কার রাখা আর কোনো ছাত্রকে সাহায্য', 'roj kichhu shekha, hiseb porishkar rakha ar kono chhatroke sahajjo'],
  ['পড়া বা পড়ানো, শিক্ষকদের সম্মান, বই বা খাবার দান, আর চাইলে বৃহস্পতিবারের প্রার্থনা', 'pora ba porano, shikkhokder sommaan, boi ba khabar dan, ar chaile Brihoshpotibarer prarthona'],
  ['পড়া বা পড়ানো, কোনো শিক্ষককে ধন্যবাদ আর বই দান', 'pora ba porano, kono shikkhokke dhonnobad ar boi dan'],
  ['শিল্প বা গান, ঘর পরিষ্কার আর সুন্দর রাখা, সঙ্গীকে সম্মান, আর চাইলে লক্ষ্মীর প্রার্থনা', 'shilpo ba gan, ghor porishkar ar sundor rakha, shongike sommaan, ar chaile Lokkhir prarthona'],
  ['শিল্প বা গান, পরিচ্ছন্ন ঘর আর সঙ্গীর প্রতি নরম ব্যবহার', 'shilpo ba gan, porichchhonno ghor ar shongir proti norom byabohar'],
  ['শিল্প বা গান, ঘর আর কাজের টেবিল পরিষ্কার আর সুন্দর রাখা, সহকর্মীদের সঙ্গে ভদ্র ব্যবহার, আর চাইলে লক্ষ্মীর প্রার্থনা', 'shilpo ba gan, ghor ar kajer table porishkar ar sundor rakha, sohokormider sathe bhodro byabohar, ar chaile Lokkhir prarthona'],
  ['শিল্প বা গান, পরিচ্ছন্ন কাজের টেবিল আর সহকর্মীদের সঙ্গে ভদ্র ব্যবহার', 'shilpo ba gan, porichchhonno kajer table ar sohokormider sathe bhodro byabohar'],
  ['শৃঙ্খলা আর সময়ানুবর্তিতা, বয়স্ক মানুষ বা শ্রমিকদের সেবা, আর চাইলে শনিবার হনুমান চালিসা', 'shrinkhola ar somoyanubortita, boyosko manush ba shromikder seba, ar chaile Shonibar Hanuman Chalisa'],
  ['নিয়মিত রুটিন, সময় মেনে চলা আর বয়স্ক মানুষ বা শ্রমিকদের সাহায্যে সময় দেওয়া', 'niyomito routine, somoy mene chola ar boyosko manush ba shromikder sahajje somoy deoa'],
  ['স্ক্রিন আর নেশা কমানো, সৎ থাকা, পশুদের সাহায্য, আর চাইলে দুর্গার প্রার্থনা', 'screen ar nesha komano, sot thaka, poshuder sahajjo, ar chaile Durgar prarthona'],
  ['কম স্ক্রিন টাইম, সততা আর পশুদের সাহায্য', 'kom screen time, sotota ar poshuder sahajjo'],
  ['ধ্যান, রাস্তার পশুদের যত্ন, আর চাইলে গণেশ বন্দনা', 'dhyan, rastar poshuder jotno, ar chaile Ganesh bondona'],
  ['কয়েক মিনিট শান্ত বসা আর রাস্তার পশুদের যত্ন', 'koek minute shanto bosa ar rastar poshuder jotno'],
  ['প্রেম করে বিয়ে', 'prem kore biye'],
  ['দেখাশোনা করে বিয়ে, যেখানে ভালোবাসা ধীরে ধীরে বাড়ে', 'dekhashona kore biye, jekhane bhalobasha dhire dhire bare'],
  ['পরিবারের সম্মতিতে প্রেমের বিয়ে', 'paribarer sommotite premer biye'],
  ['আপনার প্রেমের দিক আর সম্পর্কের দিক চালানো গ্রহেরা একসঙ্গে কাজ করে', 'apnar premer dik ar somporker dik chalano grohera ekshathe kaj kore'],
  ['প্রেমের গ্রহ আপনার রোমান্সের দিকের গ্রহের সঙ্গে আছে', 'premer groho apnar romance-er diker grohor sathe ache'],
  ['আপনার সম্পর্কের দিকে একটা অন্যরকম ছোঁয়া আছে', 'apnar somporker dike ekta onnorokom chhoa ache'],
  ['আপনার সম্পর্কের দিক পরিবার, প্রথা আর আশীর্বাদের সঙ্গে যুক্ত', 'apnar somporker dik paribar, protha ar ashirbader sathe jukto'],
  ['জ্ঞানের গ্রহ আপনার সম্পর্কের দিকে নজর রাখে', 'gyaner groho apnar somporker dike nojor rakhe'],
  ['কোনো একটা টান প্রবল নয়, তাই দেখা হওয়ার পথ খোলা', 'kono ekta tan probol noy, tai dekha hoyar poth khola'],
  ['এই দুটোর বাইরে আপনার চার্ট সবচেয়ে বেশি টানে এই ক্ষেত্রগুলোয়: {items}।', 'Ei dutor baire apnar chart sobcheye beshi tane ei khetrogulote: {items}.'],
  ['এই দুটোর বাইরে আপনার চার্ট সবচেয়ে বেশি টানে এই বিষয়গুলোয়: {items}।', 'Ei dutor baire apnar chart sobcheye beshi tane ei bishoygulote: {items}.'],
  ['এই দুটোর বাইরে আপনার চার্ট এদিকে ইঙ্গিত করে: {items}।', 'Ei dutor baire apnar chart ei dike ingit kore: {items}.'],
  ['আপনার চার্ট সবচেয়ে স্পষ্টভাবে দেখায় এই দিকগুলো: {items}।', 'Apnar chart sobcheye sposhtobhabe dekhay ei dikgulo: {items}.'],
  ['আপনার জন্য সবচেয়ে মানানসই ক্ষেত্রগুলো হলো {items}।', 'Apnar jonno sobcheye mananshoi khetrogulo holo {items}.'],
  ['আপনার চার্ট এমন সঙ্গীর কথা বলে, যিনি {items}।', 'Apnar chart emon shongir kotha bole, jini {items}.'],
  ['আপনার জন্য মানানসই মানুষটি সম্ভবত {items}।', 'Apnar jonno mananshoi manushti sombhoboto {items}.'],
  ['আপনার আয়ের সবচেয়ে ভালো উৎস হলো {items}।', 'Apnar ayer sobcheye bhalo utso holo {items}.'],
  ['আপনার জন্য সবচেয়ে মানানসই বিষয় হলো {items}।', 'Apnar jonno sobcheye mananshoi bishoy holo {items}.'],
  ['পড়াশোনার জন্য আপনার চার্ট যেদিকে টানে: {items}।', 'Porashonar jonno apnar chart jedike tane: {items}.'],
  ['আপনার সবচেয়ে বড় শক্তি: {items}।', 'Apnar sobcheye boro shokti: {items}.'],
  ['আপনার মধ্যে যা সবচেয়ে চোখে পড়ে তা হলো {items}।', 'Apnar moddhe ja sobcheye chokhe pore ta holo {items}.'],
  ['আপনার চার্ট বলে এগুলোর দিকে নজর দিন: {items}।', 'Apnar chart bole egulor dike nojor din: {items}.'],
  ['আপনার চার্টের ঝোঁক এই দিকে: {items}।', 'Apnar charter jhonk ei dike: {items}.'],
  ['আপনার চার্টের ঝোঁক হলো {items}।', 'Apnar charter jhonk holo {items}.'],
  ['আপনার চার্ট বেশি টানে এই দিকে: {items}।', 'Apnar chart beshi tane ei dike: {items}.'],
  ['আপনার জন্য বেশি মানানসই হলো {items}।', 'Apnar jonno beshi mananshoi holo {items}.'],
  ['{who} সঙ্গে সম্পর্কে আছে: {items}।', '{who} sathe somporke ache: {items}.'],
  ['আপনার সম্পর্কে চার্ট দেখায়: {items}। এটা একটা ধরন, শেষ নয়।', 'Apnar somporke chart dekhay: {items}. Eta ekta dhoron, shesh noy.'],
  ['আপনার সম্পর্কগুলোয় বারবার দেখা যায়: {items}।', 'Apnar somporkogulote barbar dekha jay: {items}.'],
  ['আপনার চার্ট আপনার পথ হিসেবে দেখায়: {items}।', 'Apnar chart apnar poth hishebe dekhay: {items}.'],
  ['আপনার জীবনে অর্থ আনে এই বিষয়: {items}।', 'Apnar jibone ortho ane ei bishoy: {items}.'],
  ['আপনার জন্য সবচেয়ে সহজ প্রতিকার: {items}।', 'Apnar jonno sobcheye sohoj protikar: {items}.'],
  ['আপনাকে সবচেয়ে বেশি সাহায্য করে: {items}।', 'Apnake sobcheye beshi sahajjo kore: {items}.'],
  ['আপনার জন্য বেশি সম্ভাব্য পথ: {items}।', 'Apnar jonno beshi sombhabbo poth: {items}.'],
  ['আপনি যা অনুভব করছেন, তা আসে আপনার জীবনের এখনকার চক্র থেকে: {items}।', 'Apni ja onubhob korchhen, ta ase apnar jiboner ekhonkar chokro theke: {items}.'],
  ['এখন কেন এমন লাগছে, তার কারণ: {items}।', 'Ekhon keno emon lagchhe, tar karon: {items}.'],
  ['এই ধরনের কাজগুলো দেখুন: {examples}।', 'Ei dhoroner kajgulo dekhun: {examples}.'],
  ['কারণ {reasons}।', 'Karon {reasons}.'],
  ['দেখা হওয়ার সম্ভাবনা {meet}।', 'Dekha hoyar sombhabona {meet}.'],
  ['যে দিকটায় নজর রাখা দরকার: {weak}।', 'Je diktay nojor rakha dorkar: {weak}.'],
  ['আপনার জন্য মানানসই জায়গা হলো {place}।', 'Apnar jonno mananshoi jayga holo {place}.'],
  ['যেটাই করুন, আপনার জন্য সবচেয়ে মানানসই ক্ষেত্র হলো {field}।', 'Jetai korun, apnar jonno sobcheye mananshoi khetro holo {field}.'],
  ['পা বাড়ানোর ভালো সময় {start} থেকে {end}।', 'Pa baranor bhalo somoy {start} theke {end}.'],
  ['এই দক্ষতাগুলো বায়োডেটার শুরুতে রাখুন, আর যেখানে এগুলোই কাজের মূল অংশ সেখানে আবেদন করুন।', 'Ei dokkhotagulo biodatar shurute rakhun, ar jekhane eguloi kajer mul ongsho sekhane abedon korun.'],
  ['কোনো বাঁধা ছবির বদলে এই গুণগুলো খুঁজুন, আর ভরসাকে নিজের মতো করে গড়ে উঠতে দিন।', 'Kono bandha chhobir bodole ei gungulo khujun, ar bhorshake nijer moto kore gore uthte din.'],
  ['আগে এগুলোর ওপর জোর দিন, প্রতি মাসে নির্দিষ্ট অংশ সঞ্চয় করুন, আর ঝুঁকির বাজি ছোট রাখুন।', 'Age egulor opor jor din, proti mashe nirdishto ongsho sonchoy korun, ar jhukir baji chhoto rakhun.'],
  ['লম্বা ডিগ্রির আগে প্রথম বিষয়টার একটা ছোট কোর্স করে দেখুন।', 'Lomba degreer age prothom bishoytar ekta chhoto course kore dekhun.'],
  ['কাজে আর সম্পর্কে এগুলোর ওপর ভরসা রাখুন, আর এমন কাজ বেছে নিন যেখানে এগুলো রোজ কাজে লাগে।', 'Kaje ar somporke egulor opor bhorsha rakhun, ar emon kaj beche nin jekhane egulo roj kaje lage.'],
  ['বড় বদলের চেয়ে রোজকার ছোট অভ্যাসই বেশি কাজের।', 'Boro bodoler cheye rojkar chhoto obhyashi beshi kajer.'],
  ['আগে কিছুদিন গিয়ে দেখুন, আর সিদ্ধান্ত নিন যখন কাজের দিক থেকেও সেটা ঠিক মনে হয়।', 'Age kichhudin giye dekhun, ar siddhanto nin jokhon kajer dik theke-o seta thik mone hoy.'],
  ['বড় টাকা ঢালার আগে ছোট করে চেষ্টা করে দেখুন।', 'Boro taka dhalar age chhoto kore cheshta kore dekhun.'],
  ['ছোট করে শুরু করুন আর রোজ করুন; বড় সিদ্ধান্তের চেয়ে অনুশীলন থেকেই অর্থ আসে।', 'Chhoto kore shuru korun ar roj korun; boro siddhanter cheye onushilon thekei ortho ase.'],
  ['পরিবারের সঙ্গে আগেভাগে খোলাখুলি কথা বলুন; পথ যেটাই হোক, এতে সাহায্য হয়।', 'Paribarer sathe agebhage kholakhuli kotha bolun; poth jetai hok, ete sahajjo hoy.'],
  ['এখনকার ধীর গতি ব্যর্থতা নয়, প্রস্তুতি; নিয়ম মেনে চলুন আর যা শুরু করেন তা শেষ করুন।', 'Ekhonkar dhir goti byarthota noy, prostuti; niyom mene cholun ar ja shuru koren ta shesh korun.'],
  ['সব মিলিয়ে আপনার জন্য সহায়ক চক্র', 'sob miliye apnar jonno sohayok chokro'],
  ['এমন চক্র যা দেয় কম, পরিশ্রম চায় বেশি', 'emon chokro ja dey kom, porishrom chay beshi'],
  ['এখন বড় আর ছোট চক্র দুদিকে টানে, তাই টানাপোড়েন বেশি।', 'Ekhon boro ar chhoto chokro dudike tane, tai tanaporen beshi.'],
  ['দুটো চক্র মিলে খরচ আর পরিশ্রম বাড়ায়।', 'Duto chokro mile khoroch ar porishrom baray.'],
  ['{start} থেকে শুরু হওয়া পরের ছোট চক্র {topic} সঙ্গে যুক্ত, তাই তখন পথ খোলে।', '{start} theke shuru hoya porer chhoto chokro {topic} sathe jukto, tai tokhon poth khole.'],
  ['পরের ছোট চক্র শুরু হয় {start}-এ আর মন আবার অন্য দিকে যায়।', 'Porer chhoto chokro shuru hoy {start}-e ar mon abar onno dike jay.'],
  ['আপনার {P}-এর লম্বা পর্ব, যা জীবনের ঝোঁক রাখে {area} দিকে', 'apnar {P}-er lomba porbo, ja jiboner jhonk rakhe {area} dike'],
  ['{end} পর্যন্ত {P}-এর ছোট পর্ব, যার ঝোঁক {area} দিকে', '{end} porjonto {P}-er chhoto porbo, jar jhonk {area} dike'],
  ['আপনার চন্দ্ররাশির ওপর দিয়ে শনির চলা, একটা ধীর পর্ব যা ধৈর্য আর ভালো অভ্যাসের ফল দেয়', 'apnar chondrorashir opor diye Shonir chola, ekta dhir porbo ja dhoirjo ar bhalo obhyasher fol dey'],
  ['শনির এমন একটা যাত্রা যা বদল আনে আর ধৈর্য চায়', 'Shonir emon ekta jatra ja bodol ane ar dhoirjo chay'],
  ['বাড়ি আর মনের শান্তির ব্যাপারে শনি ধৈর্য চায়', 'bari ar moner shantir byapare Shoni dhoirjo chay'],
  ['আপনার চন্দ্ররাশির ওপর দিয়ে শনির চলা, মনের জন্য ধীর আর পরীক্ষার সময়, যা {end} নাগাদ হালকা হবে', 'apnar chondrorashir opor diye Shonir chola, moner jonno dhir ar porikkhar somoy, ja {end} nagad halka hobe'],
  ['হঠাৎ বদলের সঙ্গে শনির একটা ভারী যাত্রা, যা {end} নাগাদ কাটবে', 'hothat bodoler sathe Shonir ekta bhari jatra, ja {end} nagad katbe'],
  ['বাড়ি আর মনের শান্তির ওপর শনির চাপ, যা {end} নাগাদ কাটবে', 'bari ar moner shantir opor Shonir chap, ja {end} nagad katbe'],
  ['এই চক্র {topic} দিকে বেশি সাড়া দেয় না, তাই সব ধীর মনে হয়।', 'Ei chokro {topic} dike beshi sara dey na, tai sob dhir mone hoy.'],
  ['এই চক্র {topic} পাশে আছে, তাই এখনকার টানা চেষ্টাই ভিত গড়ে।', 'Ei chokro {topic} pashe ache, tai ekhonkar tana cheshtai bhit gore.'],
  ['আপনার কাজের', 'apnar kajer'],
  ['ব্যবসার', 'byabsar'],
  ['টাকাপয়সার', 'takapoisar'],
  ['বিয়ের', 'biyer'],
  ['স্বাস্থ্যের', 'swasthyer'],
  ['বাড়ি আর সম্পত্তির', 'bari ar sompottir'],
  ['পরিবার বাড়ার', 'paribar barar'],
  ['বিদেশযাত্রার', 'bideshjatrar'],
  ['আইনি বিষয়ের', 'aini bishoyer'],
  ['আপনার পরিকল্পনার', 'apnar porikolponar'],
  ['স্পষ্ট করে বললে, আপনার সবচেয়ে জোরালো দিক হলো {item}।', 'Sposhto kore bolle, apnar sobcheye joralo dik holo {item}.'],
  ['আপনার চার্টে সঙ্গীর এই গুণগুলো দেখা যায়: {item}।', 'Apnar charte shongir ei gungulo dekha jay: {item}.'],
  ['যেমন বললাম, আপনার টাকা সবচেয়ে সহজে আসে {item} থেকে।', 'Jemon bollam, apnar taka sobcheye sohoje ase {item} theke.'],
  ['যেমন বললাম, আপনার সবচেয়ে বড় শক্তি হলো {item}।', 'Jemon bollam, apnar sobcheye boro shokti holo {item}.'],
  ['ওঁর মধ্যে এই গুণগুলোও থাকতে পারে: {item}, কারণ {why}।', 'Onar moddhe ei gungulo-o thakte pare: {item}, karon {why}.'],
  ['আরেকটা শক্তি হলো {item}, কারণ {why}।', 'Arekta shokti holo {item}, karon {why}.'],
  ['এগুলোও দেখে নিতে পারেন: {examples}।', 'Egulo-o dekhe nite paren: {examples}.'],
  ['এর মধ্যে একটা কাজ বেছে নিন, সামনের এক মাসে তার মূল দক্ষতাটা শিখুন আর একটা ছোট প্রজেক্টে দেখান।', 'Er moddhe ekta kaj beche nin, samner ek mashe tar mul dokkhotata shikhun ar ekta chhoto project-e dekhan.'],
  ['দেখুন রোজকার আচরণে কার মধ্যে এই গুণগুলো আছে, শুধু প্রথম দেখায় নয়।', 'Dekhun rojkar acharone kar moddhe ei gungulo ache, shudhu prothom dekhay noy.'],
  ['প্রথমটা দিয়ে আয়ের একটা ছোট পথ শুরু করুন, আর প্রতিটা লাভের কিছু অংশ জমান।', 'Prothomta diye ayer ekta chhoto poth shuru korun, ar protita labher kichhu ongsho jomaan.'],
  ['বেছে নেওয়ার আগে এই ক্ষেত্রগুলোয় কাজ করছেন এমন দুজনের সঙ্গে কথা বলুন।', 'Beche neoar age ei khetrogulote kaj korchhen emon dujoner sathe kotha bolun.'],
  ['কোনো বন্ধুকে জিজ্ঞেস করুন আপনার মধ্যে এগুলো কোথায় দেখেন, আর এই সপ্তাহে জেনেবুঝে কাজে লাগান।', 'Kono bondhuke jiggesh korun apnar moddhe egulo kothay dekhen, ar ei soptahe jenebujhe kaje lagan.'],
  ['একটা অভ্যাস বেছে নিন, আরেকটা যোগ করার আগে তিন সপ্তাহ সেটা ধরে রাখুন।', 'Ekta obhyash beche nin, arekta jog korar age tin soptah seta dhore rakhun.'],
  ['সিদ্ধান্তের আগে সেখানে যে কাজ পাবেন তার সঙ্গে এখনকার কাজের তুলনা করুন।', 'Siddhanter age sekhane je kaj paben tar sathe ekhonkar kajer tulona korun.'],
  ['ভাবনাটা যাচাই করার সময় স্থির আয় বজায় রাখুন, আর সেটা নিজের খরচ তুলতে পারলে তবেই বাড়ান।', 'Bhabnata jachai korar somoy sthir aay bojay rakhun, ar seta nijer khoroch tulte parle tobei baran.'],
  ['এই সপ্তাহে ওঁদের জন্য একটা কাজ বেছে নিন, ওঁরা আগে এগোবেন সেই অপেক্ষা না করে।', 'Ei soptahe onader jonno ekta kaj beche nin, onara age egoben sei opekkha na kore.'],
  ['দুজনেই নিজের সবচেয়ে বড় প্রয়োজন লিখুন, আর একবারে একটা বিষয় নিয়ে কথা বলুন।', 'Dujonei nijer sobcheye boro proyojon likhun, ar ekbare ekta bishoy niye kotha bolun.'],
  ['লিখে রাখুন কোন জিনিসে দিনটা অর্থপূর্ণ লাগল; সেখানেই আপনার পথ দেখা যাবে।', 'Likhe rakhun kon jinishe dinta orthopurno laglo; sekhanei apnar poth dekha jabe.'],
  ['একটা অনুশীলন বেছে নিন, আরেকটা যোগ করার আগে চল্লিশ দিন সেটা ধরে রাখুন।', 'Ekta onushilon beche nin, arekta jog korar age chollish din seta dhore rakhun.'],
  ['মানুষটিকে আগেভাগে পরিবারের সঙ্গে আলাপ করান, যাতে দুদিকেই ভরসা তৈরি হয়।', 'Manushtike agebhage paribarer sathe alap koran, jate dudikei bhorsha toiri hoy.'],
  ['এই সময়টায় দক্ষতা আর সঞ্চয় বাড়ান; পরের চক্র এখনকার প্রস্তুতির ফল দেয়।', 'Ei somoytay dokkhota ar sonchoy baran; porer chokro ekhonkar prostutir fol dey.'],
  ['আরেকটা ভালো দিক হলো {item}, কারণ {why}।', 'Arekta bhalo dik holo {item}, karon {why}.'],
  ['চাইলে এগুলোর কোনো একটা নিয়ে বিস্তারিত, বা সময় নিয়ে জিজ্ঞেস করুন।', 'Chaile egulor kono ekta niye bistarito, ba somoy niye jiggesh korun.'],
  ['এ পর্যন্ত যা বললাম, তার মধ্যে এরপর চেষ্টা করার মতো: {item}।', 'E porjonto ja bollam, tar moddhe erpor cheshta korar moto: {item}.'],
  ['ঋণ শোধ', 'rrin shodh'],
  ['টাকা ফেরত পাওয়া', 'taka ferot paoa'],
  ['ঋণ মঞ্জুর হওয়া', 'rrin monjur hoya'],
  ['গাড়ি কেনা', 'gari kena'],
  ['সম্পর্ক ভালো হওয়া', 'somporko bhalo hoya'],
  ['ততদিন প্রতিটা কিস্তি সময়ে শোধ করুন আর খরচ বাজেটের মধ্যে রাখুন; ঋণদাতারা প্রথমে এই রেকর্ডটাই দেখেন।', 'Totodin protita kisti somoye shodh korun ar khoroch budget-er moddhe rakhun; rrindatara prothome ei recordtai dekhen.'],
  ['তার আগে যাঁরা আপনার কাজ জানেন তাঁদের সঙ্গে যোগাযোগ করুন; পরামর্শ, পথ দেখানো বা পার্ট-টাইম কাজ এই সময়ে ভালো মানায়।', 'Tar age jara apnar kaj janen tader sathe jogajog korun; poramorsho, poth dekhano ba part-time kaj ei somoye bhalo manay.'],
  ['তার আগে নিজের অভিজ্ঞতাকে সামনে আনুন: অন্যদের পথ দেখান আর যে কাজটা সবচেয়ে ভালো জানেন সেটা নিন।', 'Tar age nijer obhigyotake samne anun: onnoder poth dekhan ar je kajta sobcheye bhalo janen seta nin.'],
  ['তার আগে পড়া বা অনুশীলনের একটা শান্ত, নিয়মিত অভ্যাস ওই সময়ে সবচেয়ে কাজে দেবে।', 'Tar age pora ba onushiloner ekta shanto, niyomito obhyash oi somoye sobcheye kaje debe.'],
  ['{p} আছে আপনার {area} দিকে', '{p} ache apnar {area} dike'],
  ['{p} আপনার {area} দিকটা চালায়', '{p} apnar {area} dikta chalay'],
  ['{p}-এর নজর আছে আপনার {area} দিকে', '{p}-er nojor ache apnar {area} dike'],
  ['{p} আছে আপনার {area} দিকের অধিপতির সঙ্গে', '{p} ache apnar {area} diker odhipotir sathe'],
  ['{p} স্বভাবতই {topicGen} সঙ্গে জড়িত', '{p} swobhabotoi {topicGen} sathe jorito'],
  ['শিক্ষার', 'shikkhar'],
  ['পড়াশোনার', 'porashonar'],
  ['প্রেমের', 'premer'],
  ['সন্তানের', 'santaner'],
  ['আপনার চার্ট কোনো এক দিকে বেশি ঝোঁকে না, তাই সবচেয়ে স্বাভাবিক পথ: {item}।', 'Apnar chart kono ek dike beshi jhonke na, tai sobcheye swabhabik poth: {item}.'],
  ['এই সময়ে এই গুণগুলো পরামর্শ, পথ দেখানো বা পার্ট-টাইম কাজে সবচেয়ে মানায়; এমন কাজ বেছে নিন যা ক্লান্ত না করে আপনাকে ব্যস্ত রাখে।', 'Ei somoye ei gungulo poramorsho, poth dekhano ba part-time kaje sobcheye manay; emon kaj beche nin ja klanto na kore apnake byasto rakhe.'],
  ['আগে চাকরিতে এগোন; পাশে কিছু করতে চাইলে সেটা ছোট আর পার্ট-টাইম রাখুন।', 'Age chakrite egon; pashe kichhu korte chaile seta chhoto ar part-time rakhun.'],
  ['এর মূল কারণ: {x}।', 'Er mul karon: {x}.'],
  ['হ্যাঁ, এতে শনির ভূমিকা আছে: {x}।', 'Hyan, ete Shonir bhumika ache: {x}.'],
  ['এখন শনি মূল চাপ নয়; বড় কারণ হলো: {x}।', 'Ekhon Shoni mul chap noy; boro karon holo: {x}.'],
  ['এর সঙ্গে: {x}।', 'Er sathe: {x}.'],
  ['এই পর্বের সঙ্গে চলার একটা বিনামূল্যের প্রথাগত উপায়: {practice}।', 'Ei porber sathe cholar ekta binamulyer prothagoto upay: {practice}.'],
  ['শনি সবকিছু ধীর করে আর ধৈর্যের পরীক্ষা নেয়; এটা ফল আটকায় না, নিয়মিত পরিশ্রমেরই ফল দেয়।', 'Shoni sobkichhu dhir kore ar dhoirjer porikkha ney; eta fol atkay na, niyomito porishromeri fol dey.'],
  ['এটা একটা পর্ব, যার শেষ আছে; আপনার সম্পর্কে কোনো রায় নয়।', 'Eta ekta porbo, jar shesh ache; apnar somporke kono ray noy.'],
  ['ওঁর', 'onar'],
  ['আমি ভালো আছি, ধন্যবাদ!', 'Ami bhalo achhi, dhonnobad!'],
  ['বিয়ে', 'biye'],
  ['প্রেম', 'prem'],
  ['নতুন চাকরি', 'notun chakri'],
  ['কাজে উন্নতি', 'kaje unnoti'],
  ['ব্যবসা', 'byabsa'],
  ['টাকাপয়সা', 'takapoisa'],
  ['বাড়ি বা সম্পত্তি কেনা', 'bari ba sompotti kena'],
  ['সন্তান', 'santan'],
  ['পড়াশোনা', 'porashona'],
  ['বিদেশযাত্রা', 'bideshjatra'],
  ['সুস্থতা', 'susthota'],
  ['আইনি বিষয়', 'aini bishoy'],
  ['ভাগ্য', 'bhagyo'],
  ['নতুন চাকরির', 'notun chakrir'],
  ['কাজে উন্নতির', 'kaje unnotir'],
  ['বাড়ি বা সম্পত্তি কেনার', 'bari ba sompotti kenar'],
  ['সুস্থতার', 'susthotar'],
  ['ভাগ্যের', 'bhagyer'],
  ['ঋণ শোধের', 'rrin shodher'],
  ['টাকা ফেরত পাওয়ার', 'taka ferot paoar'],
  ['ঋণ মঞ্জুর হওয়ার', 'rrin monjur hoyar'],
  ['গাড়ি কেনার', 'gari kenar'],
  ['সম্পর্ক ভালো হওয়ার', 'somporko bhalo hoyar'],
  ['ওই সময়ে সম্বন্ধের কথায় সাড়া দিন, আর পরিবার-বন্ধুদের জানান যে আপনি প্রস্তুত।', 'Oi somoye sombondher kothay sara din, ar paribar-bondhuder janan je apni prostut.'],
  ['ওই সময়ে মানুষের সঙ্গে মিশুন, মন খোলা রাখুন।', 'Oi somoye manusher sathe mishun, mon khola rakhun.'],
  ['তার আগের মাসগুলোয় বায়োডেটা গুছিয়ে নিন, দক্ষতা বাড়ান আর আবেদন করতে থাকুন।', 'Tar ager mashgulote biodata guchhiye nin, dokkhota baran ar abedon korte thakun.'],
  ['তার আগে নিজের কাজটা সবার চোখে পড়ান, আর সময় এলে স্পষ্ট করে উন্নতির কথা বলুন।', 'Tar age nijer kajta shobar chokhe poran, ar somoy ele sposhto kore unnotir kotha bolun.'],
  ['তার আগে পরিকল্পনা আর সঞ্চয় করুন, শুরু বা বাড়ানোর কাজটা ওই সময়েই করুন।', 'Tar age porikolpona ar sonchoy korun, shuru ba baranor kajta oi somoyei korun.'],
  ['ততদিন নিয়মিত সঞ্চয় করুন, ঝুঁকির বাজি এড়িয়ে চলুন; ওই সময়ে লাভ সহজে আসে।', 'Totodin niyomito sonchoy korun, jhukir baji eriye cholun; oi somoye labh sohoje ase.'],
  ['তার আগে জায়গা দেখে রাখুন আর টাকার ব্যবস্থা করুন, যাতে ওই সময়ে কেনাটা পাকা করতে পারেন।', 'Tar age jayga dekhe rakhun ar takar byabostha korun, jate oi somoye kenata paka korte paren.'],
  ['তার আগে দুজনেই শরীরের যত্ন নিন, আর চিকিৎসার যেকোনো বিষয়ে ডাক্তারের সঙ্গে কথা বলুন।', 'Tar age dujonei shorirer jotno nin, ar chikitsar jekono bishoye daktarer sathe kotha bolun.'],
  ['তার আগে রোজ নিয়ম করে পড়াশোনা করলে ওই সময়ে সবচেয়ে বেশি কাজে দেবে।', 'Tar age roj niyom kore porashona korle oi somoye sobcheye beshi kaje debe.'],
  ['তার আগে কাগজপত্র, সঞ্চয় আর আবেদন তৈরি রাখুন।', 'Tar age kagojpotro, sonchoy ar abedon toiri rakhun.'],
  ['ততদিন নিয়মিত ঘুম, খাওয়া আর হাঁটাচলাই সবচেয়ে বেশি সাহায্য করে।', 'Totodin niyomito ghum, khaoa ar hantachalai sobcheye beshi sahajjo kore.'],
  ['কাগজপত্র গুছিয়ে রাখুন আর উকিলের পরামর্শ মেনে চলুন; পারলে জরুরি পদক্ষেপগুলো ওই সময়েই নিন।', 'Kagojpotro guchhiye rakhun ar ukiler poramorsho mene cholun; parle joruri podokkhepgulo oi somoyei nin.'],
  ['যে কাজগুলো আপনার কাছে সবচেয়ে জরুরি, সেগুলো ওই সময়েই শুরু করুন।', 'Je kajgulo apnar kachhe sobcheye joruri, segulo oi somoyei shuru korun.'],
  ['নিজের', 'nijer'],
  ['টাকা আর পরিবারের', 'taka ar paribarer'],
  ['পরিশ্রম আর দক্ষতার', 'porishrom ar dokkhotar'],
  ['সৃজনশীলতা আর পড়াশোনার', 'srijonshilota ar porashonar'],
  ['রোজকার কাজ আর স্বাস্থ্যের', 'rojkar kaj ar swasthyer'],
  ['সম্পর্কের', 'somporker'],
  ['পরিবর্তনের', 'poriborttoner'],
  ['ভাগ্য আর শিক্ষার', 'bhagyo ar shikkhar'],
  ['কাজের', 'kajer'],
  ['লাভ আর বন্ধুদের', 'labh ar bondhuder'],
  ['বিদেশ আর খরচের', 'bidesh ar khorocher'],
  ['রবিবার', 'Sunday'],
  ['সোমবার', 'Monday'],
  ['মঙ্গলবার', 'Tuesday'],
  ['বুধবার', 'Wednesday'],
  ['বৃহস্পতিবার', 'Thursday'],
  ['শুক্রবার', 'Friday'],
  ['শনিবার', 'Saturday'],
  ['{a}, সঙ্গে {b}', '{a}, sathe {b}'],
  ['{a} আর {b}', '{a} ar {b}'],
  ['আর {x}', 'ar {x}'],
  ['{a}, {b}', '{a}, {b}'],
  ['{a} বা {b}', '{a} ba {b}'],
  ['{a}, {b} ({c})', '{a}, {b} ({c})'],
  ['{a}; {b}', '{a}; {b}'],
  ['{p}-এর অন্তর্দশা চলেছিল {s} থেকে {e}, আর শনি আপনার চন্দ্ররাশির ওপর চাপ দিচ্ছিল', '{p}-er antordasha cholechhilo {s} theke {e}, ar Shoni apnar chondrorashir opor chap dichchhilo'],
  ['{p}-এর অন্তর্দশা চলেছিল {s} থেকে {e}', '{p}-er antordasha cholechhilo {s} theke {e}'],
  ['এই সময়টা পড়ে {name}-এর জীবনের {P}-এর পর্বে, আর {link}।', 'Ei somoyta pore {name}-er jiboner {P}-er porbe, ar {link}.'],
  ['এই সময়টা পড়ে {name}-এর জীবনের {P}-এর পর্বে, যা {name2}-এর চার্টে {areaGen} সঙ্গে যুক্ত।', 'Ei somoyta pore {name}-er jiboner {P}-er porbe, ja {name2}-er charte {areaGen} sathe jukto.'],
  ['{p} আছে {name}-এর {area} দিকে', '{p} ache {name}-er {area} dike'],
  ['{p} {name}-এর {area} দিকটা চালায়', '{p} {name}-er {area} dikta chalay'],
  ['{p}-এর নজর আছে {name}-এর {area} দিকে', '{p}-er nojor ache {name}-er {area} dike'],
  ['{p} আছে {name}-এর {area} দিকের অধিপতির সঙ্গে', '{p} ache {name}-er {area} diker odhipotir sathe'],
  ['নমস্কার! আমি সাগা। আপনার কুষ্ঠি নিয়ে যা খুশি জিজ্ঞেস করুন — প্রেম, কাজ, টাকা, পরিবার, বা সামনের মাসগুলো কেমন যাবে।', 'Nomoshkar! Ami Saga. Apnar kushti niye ja khushi jiggesh korun — prem, kaj, taka, paribar, ba samner mashgulo kemon jabe.'],
  ['নমস্কার! আমি সাগা। {name}-এর কুষ্ঠি নিয়ে যা খুশি জিজ্ঞেস করুন — প্রেম, কাজ, টাকা, পরিবার, বা সামনের মাসগুলো কেমন যাবে।', 'Nomoshkar! Ami Saga. {name}-er kushti niye ja khushi jiggesh korun — prem, kaj, taka, paribar, ba samner mashgulo kemon jabe.'],
  ['আপনি আমাকে বলেছেন বলে আমি সত্যিই খুশি। এটা আপনাকে একা বইতে হবে না। দয়া করে এখনই কারও সঙ্গে কথা বলুন: টেলি-মানস নম্বরে 14416 (বা 1-800-891-4416) ফোন করুন। এটা বিনামূল্যে, 24×7 খোলা, আর আপনার ভাষায় কথা বলা যায়। আপনি বিপদে থাকলে বা এই ভাবনা থেকে কিছু করে ফেলতে পারেন মনে হলে এখনই 112-এ ফোন করুন। পারলে বিশ্বস্ত কাউকে জানান আর তাঁর কাছে থাকুন।', 'Apni amake bolechhen bole ami sotyii khushi. Eta apnake eka boite hobe na. Doya kore ekhoni karo sathe kotha bolun: Tele-MANAS number-e 14416 (ba 1-800-891-4416) phone korun. Eta binamulye, 24×7 khola, ar apnar bhashay kotha bola jay. Apni bipode thakle ba ei bhabna theke kichhu kore phelte paren mone hole ekhoni 112-e phone korun. Parle bishshosto kauke janan ar tar kachhe thakun.'],
  ['এর জন্য একজন ডাক্তার অবশ্যই দেখান।', 'Er jonno ekjon daktar oboshyoi dekhan.'],
  ['এ ব্যাপারে একজন উকিলের পরামর্শ অবশ্যই নিন।', 'E byapare ekjon ukiler poramorsho oboshyoi nin.'],
  ['সন্তান ছেলে হবে না মেয়ে, তা কোনো কুষ্ঠি বলতে পারে না, আর ভারতে জন্মের আগে শিশুর লিঙ্গ জানা আইনত নিষিদ্ধ। প্রতিটি সন্তানই আশীর্বাদ। চাইলে জিজ্ঞেস করুন, সামনের মাসগুলো আপনার পরিবার আর ঘরের জন্য কেমন যাবে।', 'Santan chhele hobe na meye, ta kono kushti bolte pare na, ar Bharote jonmer age shishur lingo jana ainoto nishiddho. Protiti santani ashirbad. Chaile jiggesh korun, samner mashgulo apnar paribar ar ghorer jonno kemon jabe.'],
  ['কুষ্ঠি থেকে কারও নাম বা নামের প্রথম অক্ষর জানা যায় না, তাই আন্দাজ করাটা ঠিক হবে না। তবে প্রেম আর বিয়ের সময় কখন ভালো, আর কেমন সঙ্গী আপনার জন্য মানানসই, তা দেখা যায়। এর যেকোনোটা জিজ্ঞেস করুন।', 'Kushti theke karo naam ba namer prothom okkhor jana jay na, tai andaj korata thik hobe na. Tobe prem ar biyer somoy kokhon bhalo, ar kemon shongi apnar jonno mananshoi, ta dekha jay. Er jekonota jiggesh korun.'],
  ['দুঃখিত, কথাটা স্পষ্ট না হয়ে থাকলে সহজ করে বলি: {x}', 'Dukkhito, kothata sposhto na hoye thakle sohoj kore boli: {x}'],
  ['কুষ্ঠি থেকে চিকিৎসার ফল বলা যায় না; যে ডাক্তাররা দেখছেন, তাঁরাই সেটা বলতে পারবেন।', 'Kushti theke chikitsar fol bola jay na; je daktarra dekhchhen, tarai seta bolte parben.'],
];
