/**
 * Settings → On-device model → Change model: replaces the installed model
 * with another one from the catalog (utils/model-catalog.ts).
 *
 *   1. download + verify (size, SHA-256) the new model into models/<id>/
 *      next to the old one; chats keep using the old model meanwhile and
 *      Cancel / a failure (offline, no space, hash mismatch) leaves it as it was;
 *   2. commit: unload the old model, write the new install record, activate
 *      its adapter, delete the old files, persist the choice;
 *   3. wipe what the old model wrote: every chat (all gurus, Krishna, past
 *      conversations) with titles and chips, cached chart readings, cached
 *      report text, horoscope caches, the answer cache, saved answers.
 *      profiles and the journal stay. Readings / reports / titles / chips are
 *      regenerated by the new model on demand;
 *   4. warm the new model.
 * A "wipe owed" flag is written before the commit and cleared after the
 * wipe, so a kill in between finishes the wipe at the next launch
 * (resumePendingModelSwitch, app/_layout.tsx).
 *
 * Resume: until the commit, the switch is recorded in MMKV
 * (model_switch_pending_v1, with the catalog entry). A killed app, or a
 * switch that ran out of retries offline, keeps its partial files; the
 * download continues from them (Android: HTTP Range from the .part size; iOS:
 * resume data checkpointed to MMKV every 24 MB) at the next launch once setup
 * is ready, or when the picker is reopened (resumeInterruptedSwitch). The
 * SHA-256 check still runs on the finished files. Cancel, a hash mismatch or
 * an unavailable file clears the record and the partial files.
 */
import { AppState, Platform } from 'react-native';
import * as Device from 'expo-device';
import Constants from 'expo-constants';
import { create } from 'zustand';
import { Storage } from './storage';
import { Cache } from './cache';
import { clearChatsAndModelText } from './database';
import { isRunnableAdapter } from './agent/adapters';
import {
  NoSpaceError, beginModelSwitch, commitSwitchedModel, discardSwitchDownload, downloadForSwitch, endModelSwitch,
  freeDiskBytes, getInstallMarker, useModelSetup, warmSwitchedModel, type DownloadControl,
} from './model-download';
import { backoffDelayMs, errorMessage, parsePendingSwitch, planSwitchResume, type PendingSwitch } from './model-download-logic';
import {
  INITIAL_SWITCH_STATE, MODEL_SWITCH_WIPE_SQL, canCancelSwitch, classifySwitchError, deviceSupport, isModelDerivedKey,
  pendingWipeAction, reduceSwitch, selectionToStore, shouldRetrySwitch, switchActive,
  type CatalogEntry, type DeviceInfo, type PendingWipe, type SwitchEvent, type SwitchFailure, type SwitchState,
} from './model-catalog';
import { useChatStore } from '@/stores/chat-store';
import { useThreadStore } from '@/stores/thread-store';
import { useSeenStore } from '@/stores/seen-store';

export const useModelSwitch = create<SwitchState>(() => INITIAL_SWITCH_STATE);
/** The running switch continues an interrupted download (the picker says so). */
export const useSwitchResumed = create<{ resumed: boolean }>(() => ({ resumed: false }));

function readPending(): PendingSwitch<CatalogEntry> | null {
  const p = parsePendingSwitch<CatalogEntry>(Storage.getModelSwitchPending());
  return p && typeof p.entry === 'object' && !!p.entry.spec && p.entry.id === p.id ? p : null;
}

function dispatch(e: SwitchEvent) {
  useModelSwitch.setState((s) => reduceSwitch(s, e));
}

function log(...args: unknown[]) {
  if (__DEV__) console.log('[model-switch]', ...args);
}

/** What the device-support filter needs (expo-device; RAM / ABI unknown → not filtered). */
export function getDeviceInfo(): DeviceInfo {
  let totalMemoryBytes: number | null = null;
  let cpuArchitectures: string[] | null = null;
  try { totalMemoryBytes = Device.totalMemory ?? null; } catch { /* unavailable */ }
  try { cpuArchitectures = Device.supportedCpuArchitectures ?? null; } catch { /* unavailable */ }
  return {
    platform: Platform.OS,
    totalMemoryBytes,
    cpuArchitectures,
    freeDiskBytes: freeDiskBytes(),
    runnableAdapters: (['gemma21', 'instruct'] as const).filter((a) => isRunnableAdapter(a)),
    appVersion: Constants.expoConfig?.version ?? '0.0.0',
  };
}

export type SwitchResult = { ok: true } | { ok: false; failure: SwitchFailure | 'cancelled' };

let _ctl: DownloadControl | null = null;
/** The running switch, until it has fully unwound (a cancel is still settling). */
let _inflight: Promise<SwitchResult> | null = null;

class SwitchError extends Error {
  readonly failure: SwitchFailure | 'cancelled';
  constructor(failure: SwitchFailure | 'cancelled', message: string) {
    super(message);
    this.failure = failure;
  }
}

const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

/** A switch can start: none running, and first-launch setup isn't mid-download. */
export function canStartSwitch(): boolean {
  if (_inflight || switchActive(useModelSwitch.getState())) return false;
  const p = useModelSetup.getState().phase;
  return p !== 'checking' && p !== 'downloading' && p !== 'verifying';
}

/** Replace the installed model with `entry` (see the file comment). Never rejects. */
export function switchModel(entry: CatalogEntry): Promise<SwitchResult> {
  if (!canStartSwitch()) return Promise.resolve({ ok: false, failure: 'busy' });
  useSwitchResumed.setState({ resumed: false });
  _inflight = run(entry).finally(() => { _inflight = null; });
  return _inflight;
}

let _pickerOpen = false;
/** The picker (app/settings/model.tsx) is on screen and reports the result itself. */
export function setModelPickerOpen(open: boolean): void {
  _pickerOpen = open;
}

/** A switch resumed at launch finished while the picker was closed: say so (the chats were cleared). */
function noticeResumedDone(entry: CatalogEntry): void {
  if (_pickerOpen) return;
  try {
    const { showDialog } = require('../components/overlays/store') as typeof import('../components/overlays/store');
    const i18n = (require('./i18n') as typeof import('./i18n')).default;
    showDialog({
      title: i18n.t('settings:modelPicker.doneTitle'),
      message: i18n.t('settings:modelPicker.doneMessage', { name: entry.name }),
    });
  } catch { /* no UI (tests) */ }
  dispatch({ type: 'reset' });
}

/** Cancel before the new model starts replacing the old one; later it is ignored. */
export function cancelModelSwitch(): void {
  if (!_ctl || !canCancelSwitch(useModelSwitch.getState())) return;
  _ctl.cancelled = true;
  try { _ctl.task?.cancel(); } catch { /* finished */ }
  dispatch({ type: 'cancel' });
}

/** Back to idle after a finished / cancelled / failed switch (the picker dismissed its card). */
export function resetModelSwitch(): void {
  dispatch({ type: 'reset' });
  useSwitchResumed.setState({ resumed: false });
}

/** The switch running now (also one resumed at launch), so the picker can follow it to the end. */
export function currentSwitch(): Promise<SwitchResult> | null {
  return _inflight;
}

/**
 * Continue an interrupted switch download (see the file comment), or null
 * when there is none / one can't start now. A stale or already-installed
 * record is dropped with its partial files.
 */
export function resumeInterruptedSwitch(): Promise<SwitchResult> | null {
  if (_inflight) return _inflight;
  const p = readPending();
  const action = planSwitchResume(p, getInstallMarker()?.version ?? null, new Date());
  if (action === 'none') {
    if (Storage.getModelSwitchPending()) Storage.clearModelSwitchPending(); // malformed
    return null;
  }
  if (action === 'drop') {
    Storage.clearModelSwitchPending();
    discardSwitchDownload(p!.version).catch(() => {});
    log('dropped interrupted switch', p!.id);
    return null;
  }
  if (!canStartSwitch()) return null;
  log('resuming interrupted switch', p!.id);
  const entry = p!.entry;
  const res = switchModel(entry);
  useSwitchResumed.setState({ resumed: true });
  return res.then((r) => {
    if (r.ok) noticeResumedDone(entry);
    return r;
  });
}

/** At launch: resume an interrupted switch once setup is ready and the app is in front. */
function scheduleSwitchResume(): void {
  if (!Storage.getModelSwitchPending()) return;
  let done = false;
  let unsub: (() => void) | null = null;
  const tryStart = () => {
    if (done || useModelSetup.getState().phase !== 'ready' || AppState.currentState !== 'active') return;
    done = true;
    unsub?.();
    resumeInterruptedSwitch();
  };
  unsub = useModelSetup.subscribe(tryStart);
  tryStart();
}

async function run(entry: CatalogEntry): Promise<SwitchResult> {
  dispatch({ type: 'reset' });
  const support = deviceSupport(entry, getDeviceInfo(), false);
  if (!support.ok) {
    // An interrupted download of a model this device can't take any more goes.
    if (readPending()?.id === entry.id) {
      Storage.clearModelSwitchPending();
      await discardSwitchDownload(entry.spec.version).catch(() => {});
    }
    const failure: SwitchFailure = support.reason === 'disk' ? 'no-space' : 'unsupported';
    dispatch({ type: 'fail', failure, message: `unsupported: ${support.reason}` });
    return { ok: false, failure };
  }

  // Record the switch until its commit, so a kill or a lost connection resumes
  // it; a different model's leftover download goes.
  const prev = readPending();
  if (prev && prev.version !== entry.spec.version) await discardSwitchDownload(prev.version).catch(() => {});
  const pending: PendingSwitch<CatalogEntry> = {
    entry, id: entry.id, version: entry.spec.version,
    startedAt: prev && prev.version === entry.spec.version ? prev.startedAt : new Date().toISOString(),
  };
  Storage.setModelSwitchPending(JSON.stringify(pending));

  dispatch({ type: 'start', targetId: entry.id, total: entry.sizeBytes });
  const ctl: DownloadControl = { cancelled: false, task: null, checkpoints: true };
  _ctl = ctl;
  await beginModelSwitch();
  try {
    // 1. Download + verify next to the installed model.
    for (let attempt = 0; ; attempt++) {
      try {
        await downloadForSwitch(entry.spec, ctl, {
          start: (received) => dispatch({ type: 'progress', received }),
          progress: (received) => dispatch({ type: 'progress', received }),
          verify: () => dispatch({ type: 'verify' }),
        });
        break;
      } catch (e) {
        if (e instanceof NoSpaceError) throw new SwitchError('no-space', errorMessage(e));
        const failure = ctl.cancelled ? 'cancelled' : classifySwitchError(e);
        if (!shouldRetrySwitch(failure, attempt)) throw new SwitchError(failure, errorMessage(e));
        log(`retry ${attempt + 1}: ${errorMessage(e)}`);
        dispatch({ type: 'retrying' });
        await sleep(backoffDelayMs(attempt, Math.random()));
        // Backgrounded (iOS suspends the download): wait to be back.
        while (AppState.currentState !== 'active' && !ctl.cancelled) await sleep(1000);
        if (ctl.cancelled) throw new SwitchError('cancelled', 'cancelled while waiting to retry');
      }
    }
    if (ctl.cancelled || useModelSwitch.getState().phase !== 'verifying') throw new SwitchError('cancelled', 'cancelled after verify');

    // 2. Commit (no cancel from here on). The pending record goes once the new
    // install record is written: a kill before that resumes into verify + commit.
    dispatch({ type: 'install' });
    _ctl = null;
    Storage.setModelSwitchWipe(JSON.stringify({ to: entry.id } satisfies PendingWipe));
    await commitSwitchedModel(entry.spec);
    Storage.clearModelSwitchPending();
    Storage.setSelectedModel(selectionToStore(entry));

    // 3. Wipe what the old model wrote.
    dispatch({ type: 'clear' });
    try {
      await wipeModelData();
      Storage.clearModelSwitchWipe();
    } catch (e) {
      // Retried at the next launch (the flag stays).
      log('wipe failed; owed at next launch', errorMessage(e));
    }

    // 4. Warm the new model.
    warmSwitchedModel();
    dispatch({ type: 'done' });
    log('switched to', entry.id);
    return { ok: true };
  } catch (e) {
    const failure = e instanceof SwitchError ? e.failure : 'error';
    log('switch stopped', failure, errorMessage(e));
    if (failure === 'cancelled') dispatch({ type: 'cancel' });
    else dispatch({ type: 'fail', failure, message: errorMessage(e) });
    // The installed model was never touched. Partial files go (cancel, hash
    // mismatch, file gone, no space), except after a dropped connection: those
    // stay with the pending record, and the next launch or the picker resumes.
    if (failure !== 'offline') {
      Storage.clearModelSwitchPending();
      await discardSwitchDownload(entry.spec.version).catch(() => {});
    }
    return { ok: false, failure };
  } finally {
    _ctl = null;
    endModelSwitch();
  }
}

/**
 * Clears everything the previous model wrote (utils/model-catalog.ts lists it)
 * from SQLite, MMKV and the in-memory stores. Saved answers, profiles and the
 * journal stay.
 */
export async function wipeModelData(): Promise<void> {
  await clearChatsAndModelText(MODEL_SWITCH_WIPE_SQL);
  const keys = Storage.clearModelDerivedKeys(isModelDerivedKey);
  Cache.clear();
  useChatStore.setState({ messages: {}, isTyping: {}, status: {}, streaming: {} });
  const emptied: Record<string, []> = {};
  for (const pid of Object.keys(useThreadStore.getState().threads)) emptied[pid] = [];
  useThreadStore.setState({ threads: emptied });
  useSeenStore.setState({ seen: {} });
  log('wiped chats and model caches;', keys, 'cache keys');
}

/**
 * App launch, after the database is open and before stores are hydrated:
 * finishes a switch's wipe that a kill interrupted (or drops the flag when
 * the switch never committed).
 */
export async function resumePendingModelSwitch(): Promise<void> {
  // An interrupted download (not yet committed) resumes once setup is ready.
  scheduleSwitchResume();
  const raw = Storage.getModelSwitchWipe();
  if (!raw) return;
  let pending: PendingWipe | null = null;
  try { pending = JSON.parse(raw) as PendingWipe; } catch { pending = null; }
  const action = pendingWipeAction(pending && typeof pending.to === 'string' ? pending : null, getInstallMarker()?.version ?? null);
  if (action === 'wipe') {
    try { await wipeModelData(); } catch (e) { log('pending wipe failed', errorMessage(e)); return; }
  }
  Storage.clearModelSwitchWipe();
}
